### ISSUE TITLE
Add a note for restarting atom after installation

### ISSUE THREAD

**Issue by da-vaibhav** [prettier/prettier-atom#101]
The settings panel is not shown if you installed the package via command line, although it shows entire ReadMe contents.
A note in the [installation](https://github.com/prettier/prettier-atom#installation) section should be added saying 'Please restart atom after package installation'. That would be helpful for quick start.

**Comment by kentcdodds** [comment]
Could you [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by robwise** [comment]
Fixed in https://github.com/prettier/prettier-atom/pull/102
