### ISSUE TITLE
Jsx Bracket Same Line doesn't work?

### ISSUE THREAD

**Issue by jefffriesen** [prettier/prettier-atom#103]
Does this work for people? I see the ticket closed [here](https://github.com/prettier/prettier-atom/issues/52) and the options in the settings

My settings are this:
<img width="629" alt="screen shot 2017-03-26 at 9 16 49 am" src="https://cloud.githubusercontent.com/assets/445733/24332541/68275958-1205-11e7-87ac-09280418852c.png">
<img width="590" alt="screen shot 2017-03-26 at 9 18 17 am" src="https://cloud.githubusercontent.com/assets/445733/24332542/6bacf420-1205-11e7-925d-8be1ce6cb135.png">

Before saving (bracket on same line)
<img width="359" alt="screen shot 2017-03-26 at 9 17 16 am" src="https://cloud.githubusercontent.com/assets/445733/24332545/729fcc62-1205-11e7-807e-db23e2d1f56f.png">

After saving (bracket on it's own line)
<img width="331" alt="screen shot 2017-03-26 at 9 17 09 am" src="https://cloud.githubusercontent.com/assets/445733/24332547/7aa1cdf2-1205-11e7-81fb-9a4a1926bd3c.png">

Was there a regression? Seems like my settings are correct and eslint isn't overriding.  Also not sure why there are two checkmarks in the settings for `Jsx Bracket Same Line`. 

I'm on prettier-atom 0.24.0

**Comment by robwise** [comment]
> Also not sure why there are two checkmarks in the settings for Jsx Bracket Same Line.

This is an atom bug unfortunately. The one without the description is sort of a "ghost" of a previous settings schema and isn't connected to anything.

I will check this out and report back!

**Comment by robwise** [comment]
@jefffriesen I just checked and this is because prettier only keeps the `>` on the same line if it's a non-self-closing tag.

```jsx
const Foo = () => (
  <Blahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
    prop111111111="hello"
    prop222222222222222="hello">
    {props.children}
  </Blahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh>
);
```

```jsx
const Foo = () => (
  <Blahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
    prop111111111="hello"
    prop222222222222222="hello"
  />
);
```

**Comment by jefffriesen** [comment]
Ok, got it. I didn't realize that. I'm not crazy about that decision, but that's the beauty of prettier - I can learn to stop caring and just submit!

Now at least I know it's not a bug.
