### ISSUE TITLE
Bookmarks are gone after running prettier format

### ISSUE THREAD

**Issue by oriSomething** [prettier/prettier-atom#105]
Bookmarks are gone after running prettier format.
I'm not sure if it's an **atom bug** with files that are updated by changes in the file system. But even if it's an Atom bug. We might need to consider to add a work around it.

![screenshots](https://cloud.githubusercontent.com/assets/2685242/24447159/b67278c0-1478-11e7-8a76-327a50520315.png)

**Comment by robwise** [comment]
@oriSomething Does this happen when prettier-atom is turned off and you turn eslint auto-fix on? If not, then I can look at the linter-eslint repo and try and reverse-engineer how they're working around this.

**Comment by oriSomething** [comment]
Yes, with `linter-eslint` the bookmarks stay in place.

Thanks

**Comment by robwise** [comment]
Okay I will see if we can't reverse-engineer what they're doing

**Comment by robwise** [comment]
@oriSomething I checked and eslint's fix on save _does_ remove bookmarks: 

![](https://cl.ly/110y0F1c0i08/Screen%20Recording%202017-04-02%20at%2005.25%20AM.gif)

I'm not really sure how to get around this because now there's the question of what was I trying to bookmark on that line and where did it go, and that requires a lot more intelligence. If you want to take a crack at it, that would be awesome. Otherwise, I'm not sure how to implement so I'm going to close for now.

**Comment by oriSomething** [comment]
Leave it open. I'll try to address this, though I think the checkbox of this setting will have the title "Experimental"

**Comment by robwise** [comment]
Oh okay, awesome! 

In the meantime, I'm going to cut a release because we just merged #113 which will probably help with removing bookmarks unnecessarily if the text isn't changed (if that was happening).

**Comment by oriSomething** [comment]
After some research and the fact prettier doesn't support `sourcemaps` I think there is no a good solution that can be maid in reasonable amount of time.
For now, there are other "work arounds" or more correct using different ways for bookmarking in Atom:

- [Nuclide outline view](https://nuclide.io/docs/features/outline-view/) - it's not a bookmarks manager but it gives okay way to navigate to symbols location in files unlike atom's <kbd>⌘</kbd>+<kbd>r</kbd>
- [comment-anchors](https://github.com/callodacity/comment-anchors) - which gives you the ability to navigate through `// MARK:` comments as in XCode
