### ISSUE TITLE
better guide on usage with eslintrc

### ISSUE THREAD

**Issue by souporserious** [prettier/prettier-atom#107]
First off, thank you for such an amazing plugin! Sorry if this is trivial and I'm misunderstanding things, but it seems that just adding an `.eslintrc` file like in the [README](https://github.com/prettier/prettier-atom#usage) does not work for me. If I run `eslintrc --init` and have it create a file, everything seems to work fine. I guess I'm just not sure what is required to run `eslint` alongside `prettier`. Should I be able to just check the box in prettier-atom settings and add an `.eslintrc` file and it should work? Or are there other requirements as far as having `eslint` installed locally or globally or something? Sorry, I'm not an avid user of `eslint` and would just like to get the no semicolon option to work.

**Comment by souporserious** [comment]
Sorry 😅  I believe it was because I'm using `es6` code, by adding:
```
"env": {
    "es6": true
  },
```
everything seems to work as expected. Maybe it can be referenced in the docs or something?

**Comment by souporserious** [comment]
Ok, so I tried starting a new project with just my `.eslintrc` and a `foo.js` file and it didn't work, so I guess back to my original question 😓

**Comment by robwise** [comment]
>  I tried starting a new project with just my .eslintrc and a foo.js file and it didn't work

Can you be a bit more specific?

**Comment by souporserious** [comment]
Sorry 😞  I don't think I was understanding eslint correctly. It seems that depending on what style of Javascript I'm writing it works or doesn't. Right now if I'm missing some option or a plugin, eslint seems to fail silently and it falls back to the regular Prettier options.

**Comment by souporserious** [comment]
Is it possible a warning can be thrown when that happens?

**Comment by robwise** [comment]
I don't think that's actually what's going on though, in fact people are complaining about the fact that we _aren't_ doing this: https://github.com/prettier/prettier-atom/issues/71

**Comment by souporserious** [comment]
Dang, I thought that was it 😕. Any idea what might be causing it?

**Comment by robwise** [comment]
I'm still not sure what the problem you're having is. Can you give me an example of:

1. a short snippet of code before running prettier
2. the code after running prettier
3. an explanation of what you had expected to see instead of #2
4. your eslintrc
