### ISSUE TITLE
Atom-Prettier is not paying attention to eslint max-len rule configured per file

### ISSUE THREAD

**Issue by anback** [prettier/prettier-atom#112]
Hi!

Super great work with atom-prettier! Lovin it!

See screenshot. When i configure the max-len rule like this atom-prettier does not care. It does work when i configure a max-len rule in .eslintrc.

With "work" i mean it respects the max-len rule and format the code accordingly

![image](https://cloud.githubusercontent.com/assets/2440382/24580781/a48216aa-170e-11e7-8e87-ad287517ffc8.png)

**Comment by robwise** [comment]
@anback Can you make an issue over at `prettier-eslint`, this is just the plugin that runs that in atom so we can't actually change this from this repo.
