### ISSUE TITLE
A way to enable/disable prettier via the command menu

### ISSUE THREAD

**Issue by tleunen** [prettier/prettier-atom#117]
Currently, the only shortcut we have is `format`. But it would be great to have a way to quickly enable/disable prettier.

Asking because I switch from project to another and not all of them use prettier so I have to enable or disable it manually.

![image](https://cloud.githubusercontent.com/assets/1972567/25010598/77f016ae-201f-11e7-9657-a68b139d4903.png)

**Comment by robwise** [comment]
Yeah, I think this is a good idea!

**Comment by darahak** [comment]
Do you want a toggle command just for `fix-on-save` or everything including `format`? (the shortcut would be inactive)

**Comment by robwise** [comment]
I guess just fix-on-save?

**Comment by robwise** [comment]
@darahak are you taking this one or just discussing? I can assign you if you want to take a stab at it?

**Comment by tleunen** [comment]
Yep, talking about this thing:
![image](https://cloud.githubusercontent.com/assets/1972567/25300392/fbaf4a88-26c2-11e7-834e-19d77269bd56.png)

**Comment by darahak** [comment]
@robwise Yup, I'll take this one. Since I already added one command, this seems like a natural follow-up.

**Comment by FezVrasta** [comment]
I think it would make sense to have a dotfile on the project directory to enable it.

Doing so I can keep it always on and have it active only in projects that explicitly states they make use of it.

Alternatively you may read the package.json and enable it only if it is listed as dependency.
