### ISSUE TITLE
eslint --fix doesn't run even when ESLint Integration is enabled

### ISSUE THREAD

**Issue by buunguyen** [prettier/prettier-atom#119]
Plugin version: 0.27.0. Atom version: 1.16.0.

I have both this plugin and `linter-eslint`. After disabling "Fix errors on save" in `linter-eslint` and enabling ESLint integration in this plugin, saving doesn't seem to run the eslint formatting. Enabling "Fix errors on save" in `linter-eslint` will make it work correctly but that's clearly not an ideal thing to do.

**Comment by robwise** [comment]
@buunguyen does it run the prettier formatting at least?

**Comment by buunguyen** [comment]
Yes it does run prettier. My specific test is I have an eslint rule that disallow `var`, so `var` should be converted to `const` or `let`. With "Fix errors on save" of `linter-eslint` disabled, that conversion doesn't take place, although the code gets formatted by prettier. When enabling the option, the conversion happens.

**Comment by robwise** [comment]
Hmm, this is very strange. I'm not really sure what would be causing this 😕

**Comment by buunguyen** [comment]
Is there anything I can do to help debug the issue?

**Comment by robwise** [comment]
Well, if you put a `console.log` right above this line: https://github.com/prettier/prettier-atom/blob/master/src/executePrettier.js#L33 (and then rebuild) and then start atom in development mode, does it hit that log? If not, then that means that it's not even running prettier-eslint for some reason.

**Comment by tleunen** [comment]
I'm having the same issue. It used to work, but since I updated to latest version this morning (0.28), it doesn't work anymore.

I'll try what you suggest when I get a chance @robwise

**Comment by tleunen** [comment]
After all, I think it works for me @robwise. Tested in debug and the log is hit when added at the location you mentioned. 

But I think there was a change recently around trailing commas and that's why I thought it wasn't running anymore

**Comment by robwise** [comment]
Hmm, strange. So is everything working okay now?

**Comment by robwise** [comment]
Closing, please reopen if you are still having an issue, I do want to help

**Comment by jmatsushita** [comment]
Hi there, I ran into the same bug. Adding console logs shows me that executePrettier does get executed and prettierEsLint as well, but it returns the exact same code it's passed. 

Activating `linter-eslint`'s `Fix errors on save` option does work correctly.

Maybe `prettier-eslint` doesn't find the local `.eslintrc` file?

**Comment by robwise** [comment]
@jmatsushita That's very possible, can you try running prettier-eslint-cli and see if it behaves the same way? Right now, prettier-atom will fallback to its atom settings if it can't find the eslintrc or if a corresponding rule is not defined in the eslintrc.

**Comment by therealklanni** [comment]
I ran into the same problem. This plugin only looks for `.eslintrc` not `.eslintrc.*` like ESLint does. So having `.eslintrc.json5` (for example) causes this plugin to ignore your ESLint config.

**Comment by robwise** [comment]
@therealklanni This is just the atom package, we don't actually look for the `.eslintrc` at all in this repo.Can you make an issue over at `prettier-eslint` repo?
