### ISSUE TITLE
"prettier-atom failed: Cannot find module" with shared config

### ISSUE THREAD

**Issue by Mitsunee** [prettier/prettier-atom#1190]
prettier-atom cannot find the shared config from `@foxkit/internal` ([repo](https://github.com/foxkit-js/internal)).

![Screenshot_20211005_163210](https://user-images.githubusercontent.com/19474909/136043827-82a13082-7551-4631-a2b2-49662779d0d1.png)

I have confirmed that prettier by itself is capable of finding the config and formats the file using the cli:

![Screenshot_20211005_163436](https://user-images.githubusercontent.com/19474909/136044201-80b2c49e-009a-4359-bba5-3488b11123ef.png)

**Comment by robwise** [comment]
This is a somewhat confusing use case, you are inside of a node_module which in turn has its own node modules?

**Comment by Mitsunee** [comment]
I am getting my prettier config from a devDependency that's shared across most of my projects (I will use it in all of them once this issue is adressed). https://prettier.io/docs/en/configuration.html#sharing-configurations

**Comment by Mitsunee** [comment]
closing this since atom will be discontinued, which probably means there's no point in addressing this anymore.
