### ISSUE TITLE
Option to disable if there is no local prettier config/version

### ISSUE THREAD

**Issue by bennypowers** [prettier/prettier-atom#1209]
As a contributor to many projects, some which use prettier, and other which don't, I only want prettier-atom to auto-format-on-save if the project i'm working in has a prettier config or a local version of prettier.

prettier-atom should have a settings toggle which allows users to opt-in to format on save only if there's a local config or a local version in node_modules

Otherwise, I will have to manually enable the plugin every time I open a prettier project and manually disable it each time i close said project.

Thank you for your consideration

**Comment by robwise** [comment]
@bennypowers This has been a configuration option for years?

![Image 2021-12-15 at 1 03 51 AM](https://user-images.githubusercontent.com/6173488/146147179-753b9913-c30e-45f4-a54a-d1e63f8ea2a2.jpg)

**Comment by bennypowers** [comment]
Maybe it's me, but I don't have *any* options in the settings window for 0.60.1

<img width="1500" alt="Screen Shot 2021-12-15 at 11 05 08" src="https://user-images.githubusercontent.com/1466420/146156798-5125e3ca-4c17-43af-82f4-ff32662b336b.png">
<img width="1500" alt="Screen Shot 2021-12-15 at 11 05 14" src="https://user-images.githubusercontent.com/1466420/146156819-918333be-e009-47ad-879b-78a21f7509fd.png">
<img width="1500" alt="Screen Shot 2021-12-15 at 11 05 20" src="https://user-images.githubusercontent.com/1466420/146156833-ee31a4cd-b981-4e79-9aa6-8f0121b0ee7a.png">
