### ISSUE TITLE
Add semicolon option

### ISSUE THREAD

**Issue by lowmess** [prettier/prettier-atom#124]
The ability to toggle semicolons was added in Prettier 1.0. This was the last thing stopping me from using prettier, and the only thing currently stopping me from using this!

**Comment by mkeedlinger** [comment]
I love the idea of prettier! Just waiting for this.

:+1:

**Comment by robwise** [comment]
Resolved by https://github.com/prettier/prettier-atom/pull/122, I'm cutting a release momentarily! Welcome to the party, once you start using this you won't want to go back!

**Comment by mkeedlinger** [comment]
Amazing! Thanks!
