### ISSUE TITLE
spaces between curly braces not preserved

### ISSUE THREAD

**Issue by FezVrasta** [prettier/prettier-atom#125]
If I have:

```
{ foo: bar }
```

It changes it to:

```
{foo: bar}
```

Even if I have the "Bracket Spacing" option enabled.

**Comment by robwise** [comment]
@FezVrasta I can't reproduce:

![](https://cl.ly/2n2Q3G1C2f14/Screen%20Recording%202017-04-16%20at%2010.47%20AM.gif)

Do you have eslint integration on and it's picking up something in your eslint config? Are these braces inside of JSX code, to which this rule does not apply (prettier decision)?

**Comment by FezVrasta** [comment]
Nope, I'm not using JSX, this is my ESLint config:

```
{
    "parser": "babel-eslint",
    "env": {
        "browser": true,
        "node": true,
        "es6": true
    },
    "globals": {},
    "rules": {
        "indent": ["error", 2, {"SwitchCase": 1}],
        "no-cond-assign": [ "error", "except-parens" ],
        "curly": "error",
        "eqeqeq": "error",
        "no-eq-null": "error",
        "wrap-iife": [ "error", "any" ],
        "no-use-before-define": "error",
        "new-cap": "error",
        "no-caller": "error",
        "dot-notation": "error",
        "no-undef": "error",
        "no-unused-vars": "error",
        "no-const-assign": "error",
        "prefer-const": "error",
        "no-var": "error",
        "comma-dangle": ["error", "only-multiline"]
    }
}
```

**Comment by robwise** [comment]
Where's the bracket spacing rule? http://eslint.org/docs/rules/object-curly-spacing

**Comment by FezVrasta** [comment]
Why do I need it? Prettier adds still spaces by default

**Comment by robwise** [comment]
If you run prettier-eslint directly instead of through the atom plugin, does it still do it?

**Comment by FezVrasta** [comment]
Yup, same problem. I guess it's `eslint --fix` that takes the default value of the rule and fixes them.
