### ISSUE TITLE
.eslintignore not ignoring when passed to prettier-eslint

### ISSUE THREAD

**Issue by lifeiscontent** [prettier/prettier-atom#131]
When running prettier-atom it doesn't seem .eslintignore is being used as it still runs on directories I've ignored.

**Comment by robwise** [comment]
I can't reproduce, this does seem to work still for me. Do you have any more info than this? Or maybe make a PR where you can show it not working using the `tests/fixtures` directory?

**Comment by shashanktomar** [comment]
I am also facing the same issue. My file is ignored by eslint plugin but is still picked by prettier.

**Comment by lifeiscontent** [comment]
@robwise sorry, not entirely sure how to do that.

**Comment by robwise** [comment]
@shashanktomar this could be because we are using globs instead of the ignore patterns,  see https://github.com/prettier/prettier-atom/issues/133

**Comment by robwise** [comment]
v0.29.0 is out which uses a glob matching library that is more similar to gitignore, can you guys check if this is still an issue? I will reopen if it is

**Comment by shashanktomar** [comment]
Thanks @robwise, will check it.
