### ISSUE TITLE
Code Folding lost after Format

### ISSUE THREAD

**Issue by mrbarletta** [prettier/prettier-atom#134]
Thanks for the great tool!  we are very happy with it!

I was wondering if the code that is folded could be maintained after formatting the text. 

thanks

**Comment by robwise** [comment]
I'm not sure on this, the thing is, the folded line might be removed or joined with a previous line, or split into two, so there might not really be a way to know which line should still be folded

**Comment by mrbarletta** [comment]
thats right! never thought of that so I guess its an incompatible dream :) thanks for your prompt answer!
