### ISSUE TITLE
custom iconfont format error in JSX

### ISSUE THREAD

**Issue by liuzheng644607** [prettier/prettier-atom#135]
before fromat:
```javascript
<Text class="icon moreIcon">&#xf3cc;</Text>
```

after:
![image](https://cloud.githubusercontent.com/assets/8045477/25259936/aa36d7e4-267b-11e7-92e9-6472ea9a596d.png)

the icon code #xf3cc; change to 

**Comment by robwise** [comment]
@liuzheng644607 this seems like an issue with Prettier or prettier-eslint, this is just the atom plugin
