### ISSUE TITLE
Doesn't obey settings

### ISSUE THREAD

**Issue by jelder** [prettier/prettier-atom#136]
With Single Quotes off, Bracket Spacing on, Semicolons off the plugin converts this:

```js
import { foo, bar } from "baz"
```

To this:

```js
import {foo, bar} from 'baz';
```

With those settings and that example, it shouldn't make any changes.

Version 0.28.0
![image](https://cloud.githubusercontent.com/assets/38099/25283446/cf07b90c-2681-11e7-9480-aa5e09e9c712.png)

**Comment by robwise** [comment]
@jelder do you have eslint integration on?

**Comment by jelder** [comment]
I do, and your implicit assumption that turning off eslint integration would fix my issue was correct. However, I would expect that the "Run Prettier Last" option would make Single Quote, Bracket Spacing, and Semicolons work again, but it does not.

**Comment by robwise** [comment]
If you've got the eslint integration on, it's going to interpret your eslint settings into prettier settings regardless of which order prettier is ran.

I would suggest that if you are using ESlint, which is awesome, that you configure everything in the eslintrc and forget about having to set prettier settings manually. This way you do not have to worry about keeping prettier and eslint in sync and your linter catches places you forgot to format.

**Comment by jelder** [comment]
Great. The ESLint rules I decided was close to my expectations with those three Prettier options is:

```yaml
rules:
  quotes:
    - warn
    - double
    - avoidEscape: true
      allowTemplateLiterals: true

  computed-property-spacing:
    - warn
    - never

  array-bracket-spacing:
    - warn
    - always
    - singleValue: true
      objectsInArrays: true
      arraysInArrays: true
```
