### ISSUE TITLE
Make "Format on Save > Enabled" more discoverable

### ISSUE THREAD

**Issue by gaearon** [prettier/prettier-atom#144]
I participated in a workshop aimed at JS beginners yesterday, and Atom Prettier plugin was super helpful to beginners who aren’t feeling comfortable with JS formatting conventions 👍 

One minor piece of feedback is that it’s easy to miss how to enable “Format on Save” in settings, because the checkbox just says “Enabled”. I guess the contrast of section heading might be different depending on the theme and the monitor (e.g. Windows laptops often have very low contrast).

It would help if instead of "Enabled" it said just "Format Files on Save".

**Comment by robwise** [comment]
Awesome to hear! Hmm, I can see what you mean. Yeah, I will change it.
