### ISSUE TITLE
prettier-atom not respecting line length

### ISSUE THREAD

**Issue by lionize** [prettier/prettier-atom#147]
**Version**: 0.29.0
**Prettier: Debug**: `'Uncaught Error: ENOENT: no such file or directory, open 'package.json'`

Hello! I am using `prettier-atom` for a project and it works great. It formats everything on save as expected and all of the options produce the expected output, except the line length option is not being respected. It doesn't matter what I set it to, it will still produce very long lines of code.

Here's an example:

``` javascript
export const fetchPatients = () => 
  api
  .get('/patient-profiles')
  .then(data => data.sort(sortAlphabetical);
```

Saving this line in atom produces the following:

``` javascript
export const fetchPatients = () => api.get('/patient-profiles').then(data => data.sort(sortAlphabetical);
```

That's ~30 characters longer than the default 80 char setting. Adjusting that setting lower doesn't change the result.

Now here's the result of using `./node_modules/.bin/prettier` on the file:

``` javascript
export const fetchPatients = () => 
  api.get('/patient-profiles').then(data => data.sort(sortAlphabetical);
```

This respects the line length as expected.

Does not being able to find `package.json` possibly have something to do with it?

**Comment by robwise** [comment]
@lionize It could, yes, this is very strange. prettier-atom will attempt to find your prettier package if you have one and use this instead of its packaged version of prettier. I wonder if this is a bug or something?

**Comment by robwise** [comment]
BTW, are you using eslint integration?

**Comment by lionize** [comment]
@robwise Hi Rob. Yes we are, and we have `prettier-eslint` installed as well.

**Comment by robwise** [comment]
@lionize Can you also try using `./node_modules/.bin/prettier-eslint` directly? Just making sure this is a prettier-atom problem and not a prettier-eslint problem.

**Comment by lionize** [comment]
@robwise There's no `prettier-eslint` in the `.bin` folder. I tried uninstalling and reinstalling using npm and still nothing.

**Comment by robwise** [comment]
Sorry, I should have said [prettier-eslint-cli](https://github.com/prettier/prettier-eslint-cli) as that's the one you use to invoke from the command line.

**Comment by lionize** [comment]
@robwise Man, looks like it is a `prettier-eslint` issue after all. My bad!

**Comment by robwise** [comment]
Ok no worries, closing for now
