### ISSUE TITLE
Semicolon settings not working

### ISSUE THREAD

**Issue by ikzjfr0** [prettier/prettier-atom#148]
Atom version 1.16.0 under MacOS.

The problem is: the semicolon is still in codes even I have switched it off in settings. Directly see gif below.

![semicolon](https://cloud.githubusercontent.com/assets/6456056/25526607/a71b2ccc-2c57-11e7-9e15-e28032a0b2b6.gif)

**Comment by robwise** [comment]
@ikzjfr0 Do you have eslint integration on? If so, what is your setting for semicolons?

**Comment by ikzjfr0** [comment]
my eslintrc.json configure includes 

```
"semi": [
	"error",
	"never"
]
```

**Comment by mohitgarg** [comment]
@ikzjfr0 Did you turn on ESLint integration in settings? I turned it off and it worked for me

**Comment by robwise** [comment]
If you have eslint integration on, and turning it off fixes it, then the rule must not have been configured correctly, or there is a bug in prettier-eslint.

**Comment by robwise** [comment]
Also, if you've got eslint integration on, you need to make sure your eslint config is a sibling or parent of the file in which you're working.

**Comment by robwise** [comment]
I've now implemented fallback options in case we cannot infer your settings from eslint, so try out 0.30.0 and I can reopen if you're still having trouble:

https://github.com/prettier/prettier-atom/pull/152
