### ISSUE TITLE
Space before function paranthesis

### ISSUE THREAD

**Issue by mohitgarg** [prettier/prettier-atom#150]
I am using standard as my linter and every time I save the file it deletes the space before the function paranthesis and then my linter starts yelling at well. How can I add a rule in config file to not do that?

**Comment by darahak** [comment]
Did you try using [Standard's ESLint config](https://github.com/feross/eslint-config-standard) + the ESLint integration option?

**Comment by mohitgarg** [comment]
@darahak I am talking about the atom packages here.  I am using this [standard](https://atom.io/packages/linter-js-standard) package for linting.

**Comment by robwise** [comment]
Did you turn the eslint integration for prettier-atom on? (The "enabled" option?) If you don't do this, prettier won't look at your eslint config.

**Comment by mohitgarg** [comment]
@robwise Yes, I turned it off because I am not using an eslint configuration file in the setup. The standard linter is linting the code on the fly with a config file. I just want to know how can I add an exception in the prettier configurations so that it will start adding a space before the function parenthesis

**Comment by robwise** [comment]
Prettier is not capable of doing that right now. They only want to allow a limited amount of configuration. Only eslint's autofix is capable of doing this automatically. You can make an issue at the [prettier repo](https://github.com/prettier/prettier) if you want to see this enabled. Otherwise, I'd recommend using ESlint and then turning the integration on. Please let me know if you've got any other questions.

**Comment by xgdgsc** [comment]
They are not doing anything on this issue. I' m wondering what does the option "Run Prettier Last" do. If the default behavior is to run eslint last, why would I get the error.

**Comment by robwise** [comment]
You shouldn't, you should be fine if you're using eslint to fix this. I would double check that your eslint setup is working correctly and that the rule is properly configured
