### ISSUE TITLE
trailingComma of type boolean

### ISSUE THREAD

**Issue by pruett** [prettier/prettier-atom#161]
I receive the following when running the formatter in Atom:

![screen shot 2017-05-08 at 3 22 55 pm](https://cloud.githubusercontent.com/assets/794809/25821361/cd3a3d00-3402-11e7-9bf4-1be5a6a6b288.png)

```
● Validation Error:
  Option "trailingComma" must be of type:
    boolean
  but instead received:
    string
  Example:
  {
    "trailingComma": false
  }
```

But it doesn't look the `Trailing Comma` option in the package settings allows for a `boolean`.

![screen shot 2017-05-08 at 3 24 06 pm](https://cloud.githubusercontent.com/assets/794809/25821364/d04eead6-3402-11e7-94c4-fc4c73d2dacc.png)

**Comment by darahak** [comment]
@pruett There is another thread for the same issue.
Can you check https://github.com/prettier/prettier-atom/issues/72? I'll close this one.

There might be a conflict in your Atom config with an older version of `prettier-atom`.
