### ISSUE TITLE
Options descriptions seem to contradict main project documentation

### ISSUE THREAD

**Issue by BHSPitMonkey** [prettier/prettier-atom#162]
The `prettier` README.md describes "Bracket Spacing" option as follows ([see here](https://github.com/prettier/prettier#options)):

| Option | Default | CLI override | API override |
| ------------- | ------------- | ------------- | ------------- |
| **Bracket Spacing** - Do not print spaces between brackets. <br /><br /> If true, puts the `>` of a multi-line jsx element at the end of the last line instead of being alone on the next line | `false` | `--jsx-bracket-same-line` | `jsxBracketSameLine: <bool>` |

However, the `prettier-atom` configuration page within Atom calls this option "**JSX Bracket Same Line**", and defines a *totally different* option also called "**Bracket Spacing**" that refers to spacing inside object literals. This led to a bit of confusion trying to get my tools working as expected until I figured out what was going on.

Is this a flaw in the `prettier-atom` configuration schema, or a bug in the main project's documentation? It makes sense to call the `jsxBracketSameLine` option "**JSX Bracket Same Line**" here in Atom because that maps directly to what the library and CLI options are named, but then what does "**Bracket Spacing**" actually refer to in `prettier`?

**Comment by BHSPitMonkey** [comment]
After getting deeper into the main `prettier` source, I'm leaning toward calling this a problem with the main project's documentation. It seems like they are calling the "JSX Bracket Same Line" option by the wrong name, and lacking documentation for the real "Bracket Spacing" option entirely. Does that sound about right?

**Comment by robwise** [comment]
@BHSPitMonkey Yes, it looks like their README is inaccurate, it's lumping two different options together, as you describe. You can see in the source code that they are two different options: https://github.com/prettier/prettier/blob/master/src/options.js#L12-L13 

Perhaps you could make a pull request over at that repo to correct it?

**Comment by BHSPitMonkey** [comment]
Done: https://github.com/prettier/prettier/pull/1564

Thanks for confirming; closing this issue.
