### ISSUE TITLE
Can not reformat/wrap slightly longer line

### ISSUE THREAD

**Issue by dacz** [prettier/prettier-atom#167]
Example: 

`const enhWithZip = withProps(props => ({ zip: path([ 'place', 'zip' ], props) }));`

Setting is 80char wide (this is 83). Cannot make it shorter. When I make it one character longer, it works:

```
const enhWithZip = withProps(props => ({
  zip: path([ 'place', 'zipa' ], props),
}));
```

My eslint is set to require spaces inside brackets `{ ... }` and `[ ... ]`. 

Note: I went to all-prettier and format on save. Prettier rocks! Thanks.

I'd paste the output of the `Prettier: Debug` command below, but Atom reports an error (#154), sorry.

**Comment by dacz** [comment]
Another case - deeply nested (complexity 29, booooo, shame on me but this component should be like this) snippet:

```
              <tr
                className={ place && place.streetAndSublocality ? '' : 'invalid' }
              >
```
length 83 (again).

I change this manually to:

```
              <tr
                className={
                  place && place.streetAndSublocality ? '' : 'invalid'
                }
              >
```
and similar modifications but save (reformat on save) will change it again to 83 long one line to disturb eslint. No problem with disable-line but... :)

... unfortunatelly problem with eslint...

I fixed my complexity ugliness with disable-line

`const Summary = ({ priceRange, place, order, user, intl }) => { //eslint-disable-line complexity`

but prettier reformats on save:

```
const Summary = ({ priceRange, place, order, user, intl }) => {
  //eslint-disable-line complexity
  const durationInHours = m...
```

that the `//eslint... ` part is on next line and therefore making eslint unhappy again.

**Comment by robwise** [comment]
@dacz this is just the atom plugin that uses prettier/prettier-eslint under the hood. Can you use prettier-eslint-cli on this code and see if it behaves the same way? If so, it's a prettier-eslint issue

**Comment by dacz** [comment]
@robwise Thanks. Output is the same, so I'll resort it to prettier-eslint. Thanks!
