### ISSUE TITLE
Flow Generics reported as error

### ISSUE THREAD

**Issue by shashanktomar** [prettier/prettier-atom#171]
Following is a valid flow syntax, but is reported as error by prettier plugin:
`
const funName = <T>(param: T): T => {
  // ...
}
`

**Comment by darahak** [comment]
@shashanktomar How is the error reported? What do you see?
Did you try switching the parser to Flow? It could be a bug in Babylon.

**Comment by robwise** [comment]
Also, please use the `prettier` or `prettier-eslint-cli` (if you have eslint integration enabled) packages and see if you get the error there. If yes, you need to report the issue at the respective repo, this repo is just the atom package that calls these under the hood.

**Comment by darahak** [comment]
@shashanktomar What's the exact line that throws the error?
The way you wrote your sample, it just fails because you started an inline comment before the closing brace.

Is it possible you are talking about https://github.com/prettier/prettier/issues/1632?

**Comment by shashanktomar** [comment]
@darahak Sorry for the late response. I have changed the parser to flow but can still see the error. Try pasting the code below in atom and saving it.
`const fun1 = <T>(param: T): T => param;`
`const fun2 = <T>(param: T): T => param;`

**Comment by darahak** [comment]
@shashanktomar This is what I get in Prettier's REPL: [link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20fun1%20%3D%20%3CT%3E(param%3A%20T)%3A%20T%20%3D%3E%20param%3B%5Cnconst%20fun2%20%3D%20%3CT%3E(param%3A%20T)%3A%20T%20%3D%3E%20param%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by shashanktomar** [comment]
@darahak Thanks for verifying. Submitted a bug [#1828](https://github.com/prettier/prettier/issues/1828)

**Comment by robwise** [comment]
closing since this is a prettier issue
