### ISSUE TITLE
setting tab width to a number results in error

### ISSUE THREAD

**Issue by faassen** [prettier/prettier-atom#175]
Due to #174 I set the tab width to 2 for prettier atom in the UI. But this results in a "tab width should be an integer, not a string" error from prettier-atom, which then didn't function.

**Comment by darahak** [comment]
There is a problem with how Atom handles changes on config schemas (= how we describe our settings).
Unfortunately, we cannot do anything about it.

See https://github.com/prettier/prettier-atom/issues/169 which is a duplicate of this issue.
A [troubleshoot section](https://github.com/prettier/prettier-atom#troubleshooting) has also been added to our `README` for this specific issue.
