### ISSUE TITLE
Key combination to turn on/off "Format Files on Save"

### ISSUE THREAD

**Issue by nikgraf** [prettier/prettier-atom#176]
I'm switching between multiple projects (open source and closed) during the day. Some of them have a prettier setup, some of them don't. Right now I always go into the Settings and turn this feature on and off. Would be nice to have a keyboard shortcut for turning it on/off. What do you think?

**Comment by nikgraf** [comment]
Just discovered "Show in Status Bar" … that solves my issue :)

**Comment by robwise** [comment]
You can also use the command menu: `prettier:toggle-format-on-save`
