### ISSUE TITLE
What does prettier-atom does under the hood with the eslint integration?

### ISSUE THREAD

**Issue by tleunen** [prettier/prettier-atom#177]
I was trying to run prettier on an entire code base, so I wanted to run `prettier-eslint` from the command line, with the `--write` option to overwrite the files.

But when I do that, I noticed the result is different from what `prettier-atom` is giving me with the eslint option.

It's slightly different, a few lines have the wrong indentation (2 spaces instead of 4 from my eslint config). But it's not every lines... So I wonder what magic prettier-atom does that `prettier-eslint` is not doing.

Maybe an option I'm missing?

**Comment by robwise** [comment]
@tleunen I'm not sure, but one possibility is that there are some prettier rules that cannot be inferred from your eslint config. In this case, prettier-eslint will fallback to the prettier default for that rule. However, in prettier-atom, we tell prettier-eslint to fallback to the settings you've got for the package. So, if you are missing an eslint rule, and your prettier-atom's prettier settings differ from the default prettier settings, you will get different results than running prettier-eslint directly.

**Comment by tleunen** [comment]
My tab width doesn't have any value in prettier-atom (set to "auto"), so it doesn't seem to be that.

What would be the best way to see what command prettier-atom is running? I can start atom in dev and see a log somewhere if I change the code? Any hint to where to put the log?

**Comment by robwise** [comment]
> My tab width doesn't have any value in prettier-atom (set to "auto"), so it doesn't seem to be that.

This is still a value, it's going to figure it out from atom's default tab width for the given scope. You can put a log right here to print out what the fallbacks are:
https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/executePrettierOnBufferRange.js#L15

**Comment by tleunen** [comment]
Ok, so everything is done by `prettier-eslint`...

If I debug these lines: https://github.com/prettier/prettier-eslint/blob/master/src/index.js#L60-L64

- In case of `prettier-atom`, the eslint config and the fallback prettier options are set, but not the prettier options.
- In case of `prettier-eslint-cli`, both the eslint config and prettier options are set. The options being the default prettier options.

That's why I get 2 different behaviors. Because one is using the default prettier options, and the other is not using it.

I'm not sure where the issue really is... Would it be an issue of `prettier-atom` to not provide any `prettierOptions` object to prettier-eslint? At the same time, it the plugin does that, it will force the users to change their settings to override the defaults...

@kentcdodds Any thoughts?
Without overriding anything from prettier-atom except the eslint setting, I'd expect both prettier-atom and prettier-eslint-cli to produce the same output.

**Comment by robwise** [comment]
> Would it be an issue of prettier-atom to not provide any prettierOptions object to prettier-eslint? At the same time, it the plugin does that, it will force the users to change their settings to override the defaults...

Doing this would remove prettier-eslint's ability to infer anything from your eslint settings, which would be extremely inconvenient. Prettier-eslint-cli should not be forcing you to override all settings, it should allow just inferring them from your eslint config.

**Comment by robwise** [comment]
I'm noticing issues with it prettier-eslint-cli pick up a different print width as well, but it definitely should not be doing that. I'm wondering if this is an issue with prettier-eslint-cli

**Comment by kentcdodds** [comment]
You might try reinstalling everything. I made a goof with `prettier-eslint-cli` releases. Make sure you have v4

**Comment by tleunen** [comment]
I'll wait for prettier-atom to be updated with the recent prettier version so I can compare the output again :)

**Comment by robwise** [comment]
Yep this was an issue in prettier-eslint-cli, resolved in 4.0.4, closing
