### ISSUE TITLE
Close the error dialog after prettier is re-run successfully

### ISSUE THREAD

**Issue by calesce** [prettier/prettier-atom#180]
It can be a bit annoying when I make a quick syntax error and then immediately fix it, and still have to click the close icon on the error dialog.

I can try my hand at implementing this if people think that it's a good idea. Thanks for the great package!

**Comment by robwise** [comment]
@calesce Yeah it can be very annoying, so the current plan is to show errors inline and get rid of the message popup thing altogether: https://github.com/prettier/prettier-atom/issues/146

I should have some time this weekend to try and get this implemented
