### ISSUE TITLE
Fails on save with EvalError with version 0.32.0

### ISSUE THREAD

**Issue by hollandThomas** [prettier/prettier-atom#182]
After upgrading to 0.32.0 there is the following error on file save:

`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`

<details>

```
Atom version: 1.17.2
prettier-atom version: 0.32.0
prettier version: 1.4.1
prettier-eslint version: 6.2.3
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": []
  },
  "prettierOptions": {
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon"
  },
  "useEslint": true,
  "silenceErrors": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

</details>

**Comment by darahak** [comment]
@hollandThomas Do you have `prettier` as a local dependency of your project?
It's possible that the `prettier` embedded in `prettier-atom` is not being used.

**Comment by nfcampos** [comment]
I do, and I'm seeing the same error.

**Comment by nfcampos** [comment]
And I was seeing this error before (and after) updating to 0.32.0, I believe I was using 0.31.1

**Comment by nfcampos** [comment]
But I only started to see this error after updating `prettier` itself in my project to 0.4.0

**Comment by nfcampos** [comment]
Seems to have been fixed for me after updating my project to `prettier` 0.4.2

**Comment by darahak** [comment]
@nfcampos As I suggested in my previous message, your local `prettier` may be used instead of the one bundled with `prettier-atom`.
If that's the case, you should update `prettier` in your project's dependencies.
See https://github.com/prettier/prettier-atom/pull/104

**Comment by nfcampos** [comment]
yes sorry about the flooding

**Comment by hollandThomas** [comment]
Upgrading to 1.4.2 indeed resolved the issue. Thank you!

**Comment by tleunen** [comment]
I have prettier-atom 0.32.0 and inside a project which has a dependency on prettier-eslint-cli 4.0.3, I'm seeing the exact same error message.

What should I do to force prettier-atom to use the one in the extension inside of the one in the project?

**Comment by robwise** [comment]
Try doing,

```
npm rm prettier-eslint-cli
npm i -D prettier
npm i -D prettier-eslint-cli
```

**Comment by tleunen** [comment]
Yes, adding prettier as a direct dev dependency works. Any reason why this is needed?

prettier-eslint-cli has a dependency on prettier-eslint which has a dependency on prettier already.

**Comment by robwise** [comment]
Doing this forces the prettier version to be the most up-to-date. For some reason, your prettier version was the older, buggy one, and prettier-atom was picking it up out of the node_modules folder.
