### ISSUE TITLE
Support typescript parser option

### ISSUE THREAD

**Issue by O4epegb** [prettier/prettier-atom#184]
Prettier [1.4.0](https://github.com/prettier/prettier/releases/tag/1.4.0) has Typescript support, so i guess we should add it here too?
I am pretty noob in atom extensions, but at first glance just adding it to config-schema.json options will do the thing? If so, i can make PR. Otherwise probably more experienced person should do this :)

**Comment by robwise** [comment]
I will try and take care of this, as I was going to hit the new CSS stuff as well
