### ISSUE TITLE
Using the version of prettier described in packages.json

### ISSUE THREAD

**Issue by ZeeCoder** [prettier/prettier-atom#192]
I see that the project has a dependency on prettier 1.4.4, so I assume it's using that.
However, with my current project, I'm using 1.3.1, while at work we use 1.4.2.

Is there a way the plugin could use the version installed for the current project, found in the dependencies?

**Comment by darahak** [comment]
It already does, if `prettier` is installed in your project's dependencies.
We need to update our documentation.

**Comment by zimme** [comment]
It doesn't seem like `prettier-eslint` is using a local version if it's available as seen in [executePrettierOnBufferRage](https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/executePrettierOnBufferRange.js).
getPrettierInstance is what gets the local instance of `prettier` if available but `prettier-eslint` doesn't have a counter-part.

**Comment by darahak** [comment]
In [buildPrettierEslintOptions](https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/buildPrettierEslintOptions.js), we provide the `filePath` option which should be enough according to the [docs](https://github.com/prettier/prettier-eslint#options).

For ESLint and Prettier paths, it says:

> By default, prettier-eslint will try to find the relevant eslint (and prettier) module based on the filePath. If it cannot find one, then it will use the version that prettier-eslint has installed locally. If you'd like to specify a path to the eslint module you would like to have prettier-eslint use, then you can provide the full path to it with the eslintPath option.

My understanding is that the default is to look in the project first.

**Comment by zimme** [comment]
Ooh, missed that. I guess I was too focused on this project to ecen consider looking at the dependencies docs :p

**Comment by robwise** [comment]
Closing this for now, please let me know if there's still something to be resolved and I will reopen

**Comment by ZeeCoder** [comment]
Thanks for the feedback guys, awesome work!
