### ISSUE TITLE
Use prettier_d

### ISSUE THREAD

**Issue by zimme** [prettier/prettier-atom#194]
I think [prettier_d](https://github.com/josephfrazier/prettier_d) would be a really good match for this project.

Any thoughts?

**Comment by darahak** [comment]
Not 100% sure, but aren't Atom packages (including dependencies) cached after activation?
The point of `prettier_d` is to mitigate startup time, which should already be low in Atom.

**Comment by zimme** [comment]
> // charypar: This is currently the best way to use local prettier instance.
   // Using the CLI introduces a noticeable delay and there is currently no
   // way to use prettier as a long-running process for formatting files as needed
   //
   // See https://github.com/prettier/prettier/issues/918

This comment from [here](https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/getPrettierInstance.js#L13) makes me think otherwise.

**Comment by zimme** [comment]
On another note, it doesn't seem like `prettier-eslint` is using a local version if it's available.

**Comment by josephfrazier** [comment]
`prettier_d` author here (by way of https://github.com/prettier/prettier/issues/918). I'd love to see `prettier-atom` use `prettier_d` to speed things up, if `prettier-atom` doesn't already cache loaded `prettier` instances. Let me know if you have any questions!

**Comment by robwise** [comment]
I'm going to go ahead and close this because we are already caching the lookup path using atom-linter tools' `findCached`
