### ISSUE TITLE
Support *.scss files

### ISSUE THREAD

**Issue by Tibfib** [prettier/prettier-atom#195]
`.css` files are now supported in the latest version but `.scss` isn't. It seems like it processes it as javascript:

![image](https://user-images.githubusercontent.com/290380/27155623-e189111a-5116-11e7-88d3-6e946a1c4eb8.png)

However, when I change the language in the bottom right of atom to `CSS` (instead of CSS) it will format it properly. Am I missing something or is this a bug?

**Comment by darahak** [comment]
Have you tried adding `source.scss` to the CSS scopes in the package settings?
I know it's in the "Format on Save" section, but I think it's also used for manual format.

**Comment by Tibfib** [comment]
Oh, cool, thanks for pointing that out! That works perfectly. I looked at the settings and didn't realize "scopes" was what I needed. I wonder if adding an explanation for what the scopes are (what files/languages should be formatted by what prettier parser) would be helpful? It would for me.

For anyone else looking later: add `source.css.scss` to your CSS scopes to get prettier to format .scss files.

Thanks for the awesome plugin!

**Comment by darahak** [comment]
> I wonder if adding an explanation for what the scopes are (what files/languages should be formatted by what prettier parser) would be helpful?

That's a great suggestion.
We'll think about a better description for these fields.

Or if you want to make a proposal, feel free to open a PR.
