### ISSUE TITLE
CSS/LESS indentation

### ISSUE THREAD

**Issue by chris-erickson** [prettier/prettier-atom#203]
How do I inform prettier to use the proper indentation for LESS files?  I use `.editorconfig` and `.eslintrc` and these files are ending up with the wrong indentation.

**Comment by robwise** [comment]
@chris-erickson That's probably something I would ask over at the [prettier repo](https://github.com/prettier/prettier)

**Comment by robwise** [comment]
Closing this for now, please let me know if there's still something to be resolved and I will reopen
