### ISSUE TITLE
isDisabledIfNotInPackageJson option title and description are contradictory

### ISSUE THREAD

**Issue by tsdorsey** [prettier/prettier-atom#209]
The following option is contradicting itself. The way I read them...
Title: "If you find prettier modules in my dependencies then format with prettier on save"
Description: "If you find prettier modules in dependencies then DO NOT format with prettier on save"
<img width="833" alt="screenshot 2017-06-28 23 06 38" src="https://user-images.githubusercontent.com/473477/27673874-eb76f7d6-5c57-11e7-95e1-4fca20088d02.png">

**Comment by robwise** [comment]
@tsdorsey The description text is wrong, it should be doing what the title says (if you have prettier in your deps, it formats, if you don't, it doesn't). This is the behavior you're getting, right?

**Comment by tsdorsey** [comment]
Nope.

Node project.
`"prettier": "^1.5.2"` in my devDependencies
If I check that box no formatting happens (even though the status bar indicator is showing that format on save is on).

I'm using yarn.
Have done various gyrations of `yarn remove prettier` and `yarn add prettier --dev` with no luck.

Do I need to reload the project when the package file changes? Restart Atom?

**Comment by tsdorsey** [comment]
Derp. My bad. 😞

I'm using [React Starter Kit](https://reactstarter.com/) and you can [see here](https://github.com/kriasoft/react-starter-kit/tree/master/src/components/Layout) that there are lots of package.json files in subfolders to reduce the number of index.js files in the project. The "is in deps" check is not recursive (which makes sense).

**Comment by tsdorsey** [comment]
If I add a devDependencies with prettier to the subfolder package.json file and have the option on it works as expected.

**Comment by robwise** [comment]
@tsdorsey I will fix the docs right now. J/C though, if we checked for the binary in `node_modules/.bin` instead of reading the package json, would that find it properly? There's a similar problem with CRA and #191

**Comment by tsdorsey** [comment]
Yeah, it's installed and in the bin folder. Just read #191 and looking in `node_modules/.bin` would be an excellent solution.

**Comment by duro** [comment]
@robwise I'm actually finding this not working as expected on my end. I have prettier in my devDependencies, and no further nested package.json's (just one at the root) and when I have this option turned on it does not auto-format on save. But when I have it turned off, it does auto-format.

**Comment by robwise** [comment]
@duro can you make an example repo from scratch that reproduces this? There might be some sort of edge case that I'm overlooking, as it stands right now I'm not able to reproduce.
