### ISSUE TITLE
Format undoes all editor folds

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-atom#215]
Here's a gif of the behavior. This happens whether I format manually or hit save to format.

![bad](https://user-images.githubusercontent.com/1500684/27712622-1c088b66-5ce5-11e7-9d51-0f143179b42d.gif)

Not 100% certain you can do anything about this, but maybe? Perhaps keep track of all the folded coded and refold it when you're done?

**Comment by robwise** [comment]
I'm not sure, I'd have to take a deeper look at how code folding is done. Unlike #105, this isn't just based on arbitrary line numbers (which can become inaccurate after formatting), so this one might be more within the realm of possibility.

**Comment by phil-andrews** [comment]
This might be a deal breaker for me unfortunately.

**Comment by kentcdodds** [comment]
Sorry to hear that @phil-andrews. This is an open source project, so if it matters that much to you I'm certain that @robwise would welcome [a pull request](http://makeapullrequest.com/) :smile:

**Comment by robwise** [comment]
I guess he'd rather delete his post instead 😕 

To anyone reading this, I definitely DO appreciate pull requests! If you're new to OSS, check out Kent's free course (see his link). Also, let me know what I can do to make it easier to contribute!

**Comment by phil-andrews** [comment]
The comment I left added nothing to the conversation and shouldn't have been left in the first place so I felt it was better to delete it. I do appreciate the direction towards contributing 👍

**Comment by kentcdodds** [comment]
I'm not sure it's possible to do this and it's not a huge deal to me anyway so I'm going to go ahead and close this :)
