### ISSUE TITLE
Different formatting results from prettier-eslint-cli

### ISSUE THREAD

**Issue by ryanhiebert** [prettier/prettier-atom#216]
### Summary

`prettier-atom` is formatting my project differently from `prettier-eslint-cli`. Specifically, it's not doing the spacing inside braces. I'm using Standard, and the eslint standard rules to configure eslint.

`prettier-eslint-cli` (via `yarn run format`) gives this diff:

```diff
diff --git a/index.js b/index.js
@@ -1 +1 @@
-let {a, b, c} = { a: 1, b: 2, c:3 }
+let { a, b, c } = { a: 1, b: 2, c: 3 }
```

`prettier-atom` gives this diff:

```diff
diff --git a/index.js b/index.js
@@ -1 +1 @@
-let {a, b, c} = { a: 1, b: 2, c:3 }
+let {a, b, c} = {a: 1, b: 2, c: 3}
```

### `package.json`

<details>

```json
{
  "name": "prettier-atom-repro",
  "version": "1.0.0",
  "private": true,
  "main": "index.js",
  "author": "Ryan Hiebert <ryan@ryanhiebert.com>",
  "license": "MIT",
  "scripts": {
    "format": "prettier-eslint --write index.js"
  },
  "eslintConfig": {
    "extends": [
      "standard",
      "standard-jsx"
    ]
  },
  "dependencies": {
    "eslint": "^4.1.1",
    "prettier-eslint-cli": "^4.1.1",
    "standard": "^10.0.2"
  }
}
```

</details>

### Prettier Debug

<details>

```
Atom version: 1.18.0
prettier-atom version: undefined
prettier version: undefined
prettier-eslint version: undefined
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "isDisabledIfNotInPackageJson": true,
    "showInStatusBar": true,
    "enabled": false,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": []
  },
  "prettierOptions": {
    "bracketSpacing": false,
    "semi": false,
    "singleQuote": true,
    "trailingComma": "es5",
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon"
  },
  "useEslint": true,
  "silenceErrors": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

</details>

### Additional version info

Since the versions seem to be missing in the debug output (not sure why) here's some versions gathered from the command line:

<details>

```
$ apm list | grep prettier
├── prettier-atom@0.35.0
$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.13.0
$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ yarn list prettier-eslint-cli
yarn list v0.24.6
└─ prettier-eslint-cli@4.1.1
Done in 0.34s.
$ yarn list standard
yarn list v0.24.6
└─ standard@10.0.2
Done in 0.33s.
$ 
```

</details>

**Comment by robwise** [comment]
@ryanhiebert You have `bracketSpacing: false` in your atom settings, so if this rule is missing from your eslint config, prettier-atom will fallback to your prettier-atom settings. Could you try setting this to `true` and see if it changes the behavior? Or set this to false, and set `"space-in-brackets": "always"` in your eslint config?

**Comment by ryanhiebert** [comment]
That did what I needed, thank you. I think that I misunderstood what was meant by what the help string for the prettier-eslint setting:

> Use [prettier-eslint](https://github.com/prettier/prettier-eslint) to infer your Prettier settings based on your ESLint config. If we cannot infer a Prettier setting from your ESLint config (or if there is none in the current project), we will fallback to using your settings in the *Prettier Options* section.

I took that to mean that it would end up with the same settings that `prettier-eslint` would, but upon re-reading I see that is incorrect. It seems that Standard doesn't much care about the bracket spacing as long as it's even, so both meet the eslint configuration, and I just had a different fallback because of how I had it configured.

**Comment by ryanhiebert** [comment]
Turns out that the `space-in-brackets` option has been replaced with `object-curly-spacing` and `array-bracket-spacing`. So for me, I needed to add this to my `package.json`'s `eslintConfig` section:

```json
"rules": {
  "object-curly-spacing": ["error", "always"]
}
```

**Comment by robwise** [comment]
> I think that I misunderstood

If you have alternative wording you think would improve understanding, don't hesitate to make a PR! The problem is, we had more basic functionality, and then people wanted more advanced functionality like falling back to their atom settings, but now people are getting confused by that because there's more complicated checks and fallbacks going on under-the-hood :/

> Turns out that the space-in-brackets option has been replaced

Oh oops, I'm glad you were still able to figure that out, I will try to remember that for the future!

**Comment by ryanhiebert** [comment]
>I'm hoping we can address this via something like #178

That sounds like it would be helpful. However, I think that what probably should happen is that the configured settings _not_ be used as the fallback configuration. I've been thinking about it a bit, and I'll open up a new issue to make my case. Then we'll see if you agree or not ;-)

Thanks for your help today!
