### ISSUE TITLE
Add local dependencies to prettier:debug output

### ISSUE THREAD

**Issue by darahak** [prettier/prettier-atom#222]
Idea from #217.

Would be nice to add:

- [ ] Detected local `prettier` version
- [ ] Detected local `prettier-eslint` version
- [ ] Detected `prettier-eslint-cli` version
- [ ] ESLint config if using `prettier-eslint` (see [getConfigForFile](http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile))

**Comment by peterp** [comment]
This would be helpful, right now my `Format Files on Save` isn't working when `only format if Prettier is found...` is checked, but I have:

```json
"prettier": "^1.5.2",
"prettier-eslint": "^6.4.2",
```

in my `devDependencies`
