### ISSUE TITLE
[0.36.0] No more error dialogs when formatting invalid code

### ISSUE THREAD

**Issue by ffxsam** [prettier/prettier-atom#228]
Prettier no longer pops up error dialogs if you try to run `Prettier: Format` on code with syntax error(s).

```
Atom version: 1.18.0
prettier-atom version: 0.36.0
prettier version: 1.5.2
prettier-eslint version: 6.4.2
prettier-atom configuration: {
  "prettierOptions": {
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon"
  },
  "useEslint": false,
  "useEditorConfig": true,
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment]
This is by design, we are now using the `linter` package to display errors inline. If you have linter already installed, you should see it right away, if not, you should have seen a message prompting you to install it?

**Comment by ffxsam** [comment]
Ah! I had `linter` disabled because it didn't play nice with Nuclide, but now that `linter` v2 is out, that seems to have been cleared up.
Thanks.

**Comment by ffxsam** [comment]
@robwise This issue is back for some reason. I have `linter` installed, and I have `eslint` in my `devDependencies` in my project (no `.eslintrc` though). And in the `prettier-atom` package settings, I have "ESLint Integration" checked.

**Comment by darahak** [comment]
Let's track this in #235.
Technically this is the original issue, but there is more information there.
It'll be easier to handle this way.
