### ISSUE TITLE
Destructuring without const/let breaks prettier

### ISSUE THREAD

**Issue by lifeiscontent** [prettier/prettier-atom#232]
Object Destructuring breaks prettier on save.

``` js
function test(object, property, value) {
  let red;
  let green;
  let blue;
  ({ red = 0, green = 0, blue = 0 } = { ...object, [property]: value });

  return [red, green, blue];
}
```

this javascript, when trying to save will blow up prettier-atom even though it is valid ES6.

**Comment by robwise** [comment]
@lifeiscontent this is just the atom integration, are you sure this isn't just a problem with prettier itself?

**Comment by lifeiscontent** [comment]
@robwise good question, as I haven't dug into the depths of prettier, I'm unsure, but I can repost it there if you like.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
