### ISSUE TITLE
format on save doesn't work

### ISSUE THREAD

**Issue by WangQianliang** [prettier/prettier-atom#233]
format on save doesn't work for me

```
Atom version: 1.18.0
prettier-atom version: 0.36.1
prettier version: 1.5.2
prettier-eslint version: 6.4.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": false,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "jsxBracketSameLine": true,
    "parser": "flow",
    "singleQuote": true,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none"
  },
  "useEditorConfig": false,
  "useEslint": false
}

**Comment by robwise** [comment]
Can you provide some more details?

**Comment by hattmarris** [comment]
Hi @robwise I've also observed this bug introduced in either `0.36.0` or `0.36.1` (I *think*).  Here are some screen caps of the behavior with 0.36.1 installed: 

Formatting manually (^⌥F) some test JSX (formats correctly) -
![](http://g.recordit.co/oTKPP9ZnWF.gif)

Saving and expecting format on save -
![](http://g.recordit.co/Zdl7GxZYGx.gif)

**Comment by WangQianliang** [comment]
after reinstall prettier-atom, disable linter-eslint's fix on save and enable linter-eslint's fix on save, now it works fine magically

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Comment by lednhatkhanh** [comment]
It doesn't work for me too, this should be reopen, I tried to reinstall prettier-atom, disable eslint auto save, re-enable the prettier format on save settings but still doesn't work...

**Comment by lednhatkhanh** [comment]
Update: After installing prettier-eslint as a devdependencies the `Format on save` settings start to work.

**Comment by robwise** [comment]
Do you need me to reopen? I need help finding where the bug is or how to reproduce as most people aren't running into this it seems.

**Comment by chibicode** [comment]
Same here - the problem for me was not adding `prettier-eslint` on `devDependencies` when having ESLint integration ON.

**Comment by Rambatino** [comment]
``` bash
yarn add prettier-eslint --dev
```

Is the fix! Thanks. ❤️
