### ISSUE TITLE
Getting closing and opening brace on the same line separated by comma

### ISSUE THREAD

**Issue by nadeemja** [prettier/prettier-atom#236]
Hi,

I'm using the latest Atom and prettier-atom. 

No matter what I do, I can't get prettier-atom to stop putting braces inside parentheses on new lines. I have tried brace-style: '1tsb'.

What I want:
```

Clients.update({
        ext_id: c.id,
      }, {
        $set: {
          ext_id: c.id,
          name: c.name,
          status: c.status,
        },
      }, {
        upsert: true,
      });

```

What I get instead:

      Clients.update(
        {
          ext_id: c.id,
        },
        {
          $set: {
            ext_id: c.id,
            name: c.name,
            status: c.status,
          },
        },
        {
          upsert: true,
        },
      );

This works very well VS Code

**Comment by robwise** [comment]
@nadeemja Is this a problem with how prettier-atom is passing the option to prettier, or is this a problem with prettier itself? This is just the atom integration that calls it under the hood.

**Comment by nadeemja** [comment]
@robwise 

Thanks chiming in :) 

When I run eslint --fix from the command line, it actually works the way I want.

In the devtools atom-prettier says, I think, something about config file not found for eslint,

However, from what I can tell from docs, I've configured correctly (VS Code finds the file).

Also, I've tried every conceivable combo of local vs global eslint@3 install. 

Please do let me know what diagnostics I can do to bring about information that might prove useful :)

**Comment by robwise** [comment]
Can you try running `prettier-eslint-cli` and if it creates the same result? If so, it's a problem with that library and not prettier-atom itslef

**Comment by darahak** [comment]
@nadeemja Have any news?

**Comment by darahak** [comment]
Closing this because it's not actionable for us.

Looks like the `brace-style` rule only applies to scopes and not object literals.
And I don't know about your VS Code setup, but I just tried and got the same result.
