### ISSUE TITLE
prettier-atom removes import statement from graphql

### ISSUE THREAD

**Issue by lucasfeliciano** [prettier/prettier-atom#249]
```graphql
#import 'fragments/eventCarousel.gql'
query SomeQuery($latitude: Float, $longitude: Float) {
    activeEvents {
        edges {
            node {
                ...eventCarousel
            }
        }
    }
}
```

prettier-atom removes the first statement: `#import 'fragments/eventCarousel.gql'`
Which is an valid statement if you have the webpack loader.

You can check here:

https://prettier.io/playground/#%7B%22content%22%3A%22%23%20import%20%5C%22%2FclaimsFragment.gql%5C%22%5Cn%5Cnquery%20claimsByBookingReferenceAndLastName(%24bookingReference%3A%20String!%2C%20%24lastName%3A%20String!)%20%7B%5Cn%20%20claimsByBookingReferenceAndLastName(bookingReference%3A%20%24bookingReference%2C%20lastName%3A%20%24lastName)%20%7B%5Cn%20%20%20%20...%20claim%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22graphql%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

What I think its happening is that prettier-atom doesn't use the graphql parser on `.graphql|.gql` files, instead it uses babylon parser, which throw an error.

**Comment by robwise** [comment]
@lucasfeliciano Can you use `Editor: Log Cursor Scope` to check what the scope is at these lines?

**Comment by lucasfeliciano** [comment]
Yeah, I was wrong:

![screen shot 2017-08-15 at 15 24 15](https://user-images.githubusercontent.com/968014/29317790-d87ab26c-81cd-11e7-81f5-930435f9cdbf.png)

**Comment by robwise** [comment]
@lucasfeliciano Does this happen with the normal prettier, or only prettier-atom?

**Comment by lucasfeliciano** [comment]
@robwise only prettier-atom :(

**Comment by robwise** [comment]
Man that's really strange, if it's using the right parser, it should be a straight pass-through. Can you use a dev version of prettier-atom and log if it's changing the parser it's using here?: https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/buildPrettierOptions.js#L46

**Comment by lucasfeliciano** [comment]
I'll take a look on that soon.

**Comment by darahak** [comment]
@lucasfeliciano Can you check if you have an outdated `prettier` install in your project's dependencies?
It's very likely that you encountered these issues: https://github.com/prettier/prettier/issues/2302 and https://github.com/prettier/prettier/issues/2299

In that case, you should update your dependency and try again.

**Comment by darahak** [comment]
I'll close this stale issue, since there is a really good chance it can be solved by just updating your `prettier` dependency.
Feel free to re-open if you still have the problem.
