### ISSUE TITLE
change of semicolon option has no effect

### ISSUE THREAD

**Issue by gmuc** [prettier/prettier-atom#251]
prettier-atom 0.37.0 atom 1.19.2 on Mac

change of semicolon option has no effect. Everytime my code on save is formated without semicolon.

After deinstall prettier-atom + restart atom + new install prettier-atom semicolon option work corret for all file allready opened on atom start. All after atom start opened files have the semicolon problem.

I think it's a caching bug!?

**Comment by robwise** [comment]
@gmuc I can't reproduce this. Perhaps you are using the eslint integration in some cases, and this is overriding your settings?

**Comment by gmuc** [comment]
I use linter-eslint 8.2.1. I found no semicolon option in linter-eslint.

**Comment by gmuc** [comment]
I now upgrade to 0.38.0 - same problem :-(

**Comment by robwise** [comment]
Are you still having this problem?

**Comment by gmuc** [comment]
yes. I upgraded to 0.40.0 - same problem. After delete and reinstall prettier-atom all open files, will nice format. New opened files - not working semicolon option!

My packages:
├── autocomplete-paths@2.11.0
├── busy-signal@1.4.3
├── emmet@2.4.3
├── goto-definition@1.3.4
├── intentions@1.1.5
├── js-refactor@0.7.5
├── language-babel@2.74.2
├── last-cursor-position@0.9.2
├── linter-eslint@8.3.2
├── markdown-preview-plus@2.4.10
├── markdown-writer@2.7.2
├── mocha@0.0.7
├── mocha-test-runner@1.0.0
├── node-debugger@1.10.1
├── nuclide@0.255.0
├── prettier-atom@0.40.0
├── refactor@0.11.5
├── standard-formatter@2.8.0
├── symbol-gen@1.3.1
├── vim-mode-plus@1.7.0
├── vim-mode-plus-ex-mode@0.9.1
└── vim-mode-plus-move-selected-text@0.10.0

**Comment by gmuc** [comment]
I have tried delete and reinstall complete atom - no solution :-(

**Comment by darahak** [comment]
- Are you using ESLint in your project? If yes, is the `semi` rule set to `"never"`?
- If format-on-save enabled in `linter-eslint`?
- Are you using `prettier-atom` with ESLint integration and the `semi` rule?

To be sure about the ESLint config, run:

```
npx eslint --print-config <path-to-your-file>
```

**Comment by robwise** [comment]
Also, we're not talking about unsaved files, right? prettier-atom needs the file to be saved in order to pick up local eslint config files, otherwise we can't know where to look and just fall back to your package settings.

**Comment by gmuc** [comment]
I tried deinstall linter-eslint 8.3.2. Now the semicolon of prettier-atom work. I install linter-eslint again and prettier-atom still works!?? There ara any cross dependencies?

**Comment by robwise** [comment]
@gmuc There are if you don't disable fix on save in linter-eslint, although we warn about that. Ok to close?

**Comment by gmuc** [comment]
you mean https://github.com/prettier/prettier-atom/issues/168

**Comment by gmuc** [comment]
If you want you can close. It's right to say prettier-atom and linter-eslint not good friends? Better to disable linter-eslint?

**Comment by robwise** [comment]
`linter-eslint` works great with prettier-atom, just don't enable its fix on save thing as you will get weird race conditions with prettier where they both are trying to replace the old code, and whoever's last wins.

**Comment by gmuc** [comment]
Great! Now you can close.
