### ISSUE TITLE
no-extra-parens: 'extra' parens removed when rule is off or absent from eslintrc.json

### ISSUE THREAD

**Issue by beagins** [prettier/prettier-atom#252]
I have `ESLint Integration` enabled and `Format Files on Save` enabled. 

My `eslintrc.json` file does not contain the setting `no-extra-parens` because I want code like the following to stay as-is: 
```
let myVar = (changes.a && changes.a.currentValue) ? changes.a.currentValue : this.a;
```

If I enable `no-extra-parens`, the parens in the statement above are considered unnecessary and removed: 
```
let myVar = 
  changes.a && changes.a.currentValue 
  ? changes.a.currentValue 
  : this.a;
```

Although this is syntactically correct, this goes against my team's style guide.

I want to use `prettier-atom`, however, even though `no-extra-parens` is not set in my `eslintrc.json`, it seems to remove extra parens by default.

I tried to add the following rule to my `eslintrc.json` file, but `prettier-atom` still removes the 'extra' parens: 
```
"rules": {
    "no-extra-parens": "off", ...
```

**Comment by darahak** [comment]
The Atom package is not really concerned by this issue so it would have been more appropriate on https://github.com/prettier/prettier.

This is one of those things that Prettier can't really change and you will probably have to drop this from your style guide if you want to adopt it.

When the code is parsed and we get an AST, there is no info about the parens (see [this gist](https://astexplorer.net/#/gist/1aac99e75bf202488dd7dfb57205785f/1d693a659ce3b723ce830e6b4bdbebf59dbf45d5)), so Prettier has to make a choice (oversimplified here): only print parens when necessary or always print them.
It's just impossible to please everyone here.

Maybe make a custom ESLint rule to put them back if you really want them?
