### ISSUE TITLE
Prettier not working after changing EditorConfig settings & checking and unchecking (testing out) different prettier-atom settings.

### ISSUE THREAD

**Issue by jcalderaio** [prettier/prettier-atom#253]
Before I ask my question, I want to thank the creators/contributors for all of your work on this potentially awesome project. I use the word potentially because I've heard non-stop from my peers how awesome it is, but it doesn't work for me. I'm working on a React Native project with many files and folders and an ESLint file. In the prettier settings, I checked the boxes next to ESLint Integration and EditorConfig Integration. I also checked next to format upon save.

I exited, tried it on a few files and it worked flawlessly. Then I started messing around with my EditorConfiguration settings by making it 3 spaces as a tab, and the length of a line to 100 chars. I exited and it still worked. I went back to the prettier settings and mucked around in there, checking and unchecking the 2 Integration boxes from before. I exited, tried it out on a file, and it didn't work. It's now not working. I don't know what the hell I did, but I got a taste of it and I NEED it back :) 

Please, if anyone has any ideas let me know.

**Comment by robwise** [comment]
@jcalderaio Are you still having this problem?

**Comment by jcalderaio** [comment]
Yes I am

**Comment by robwise** [comment]
So if I understand correctly, you set prettier-atom to use eslint and editor config, then it worked correctly, then you checked and unchecked the two boxes again, and now it doesn't work?

Can you provide more detail on what you mean by "it doesn't work?"

**Comment by jcalderaio** [comment]
By "it doesn't work", I mean that upon saving a file, nothing is formatted. I even see the green "Prettier ✓" notification at the bottom of Atom (signaling that I have the "Format Files on Save" option checked in the Prettier settings). I do notice in different files (on the bottom right-hand side of Atom) that some have different spacing options than others (some say "Tabs (2 wide)", others say "2 spaces" and even others say "3 spaces". I had played around with different spacing options, but why is each file taking on different ones instead of the entire project being uniform? This may have something to do with why Prettier is not formatting my files. But, I'm no expert on Prettier.

**Comment by robwise** [comment]
@jcalderaio The spaces/tabs thing is determined by Atom. If you have your prettier-atom setting for tabs/spaces set to "auto," it just infers from the file.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
