### ISSUE TITLE
Support prettier v1.6 config files

### ISSUE THREAD

**Issue by codeheroics** [prettier/prettier-atom#257]
Hi, thanks for the great work!

Prettier 1.6 just landed [support for .prettierrc config files](https://github.com/prettier/prettier/pull/2434).

Will they be supported soon on prettier-atom?

**Comment by darahak** [comment]
Thanks for bringing this to our attention, we'll take care of it as soon as possible.
In the meantime, I'm closing it because #256 was opened just before.
