### ISSUE TITLE
Detect obsolete or incompatible versions of Prettier

### ISSUE THREAD

**Issue by darahak** [prettier/prettier-atom#258]
We had our share of issues where users reported problems, only to discover later that it was caused by an old installation of Prettier.

For example, if we support TypeScript scopes and we detect a pre-`1.4.0` Pretter install, we should notify the user that they should update their deps.
If we support config files, we should avoid using pre-`1.6.0`.

We could probably put this info in our `package.json`.

**Comment by robwise** [comment]
Seems like a good idea, but what do you mean by putting the info in our package.json?

**Comment by darahak** [comment]
I was thinking about using the [peerDependencies](https://yarnpkg.com/lang/en/docs/dependency-types/#toc-peerdependencies) property.
It could be read on package activation for a quick version check.

**Comment by darahak** [comment]
Better yet, we should fall back on our own embedded Prettier if it doesn't meet requirements from `peerDependencies`. I don't know why I didn't think of that.

**Comment by robwise** [comment]
While the prettier config release obviously had a major backward-compatibility issue, in this case it was actually resulting from an external dependency that already was the embedded dependency, and we can't (I think) install two different versions. Depending on what it is, I think we'll want to just use a conditional to work around the issue, and then as a "plan b" just display an incompatibility error or do what you just suggested. But again, I think "plan a" should be to somehow work around the given issue with a conditional or something:

https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/buildPrettierOptions.js#L30

**Comment by darahak** [comment]
I'm not sure why we are talking about installing two versions.

I'll try to clarify my reasoning below.
Most of the problems were caused by new embedded Prettier vs old Prettier in project dependencies.

What I'm proposing is only indicating compatible versions of `prettier` and `prettier-eslint` in our `package.json`. Then we can show clear errors telling users to upgrade instead of them creating issues about undefined properties.

Conditionals are fine for one or two features, but can become a real PITA for maintenance if we add more.
And it's easy to forget: e.g. some people have older versions of Prettier and don't have `resolveConfig`. We only check for `resolveConfig.sync` so we're just moving the problem.

And if people can't update their dependencies (rare but can happen), let them downgrade `prettier-atom` instead.

**Comment by robwise** [comment]
> And it's easy to forget: e.g. some people have older versions of Prettier and don't have resolveConfig. We only check for resolveConfig.sync so we're just moving the problem.

Yeah we should fix this actually lol

> I'm not sure why we are talking about installing two versions.

Oh, because in the case of `prettier-eslint` we *always* use the bundled version, we never pick up the local version. I guess we could change that though.

**Comment by darahak** [comment]
> Oh, because in the case of prettier-eslint we always use the bundled version, we never pick up the local version. I guess we could change that though.

I didn't know that, thanks for clarifying!

**Comment by robwise** [comment]
Yeah, for reference, here was the discussion about it way back when it was implemented: https://github.com/prettier/prettier-atom/issues/59#issuecomment-288158656

**Comment by robwise** [comment]
Resolved in #404
