### ISSUE TITLE
Notify user in a failed formatting attempt

### ISSUE THREAD

**Issue by michaellee8** [prettier/prettier-atom#259]
Feature request:
Notify user with the cli error message in a failed format attempt

<detail>
Currently, the formatter will not show any feedback regardless fail or success format attempt when being used in atom, and this may possibly cause frustration. Sometimes, when eslint is not used for some reason, it is very hard to identity a very minor syntax error that is critical to the formatter. I mostly have to use cli version of prettier to show the source of error, and this is not convenient.
</detail>

**Comment by robwise** [comment]
@michaellee8 This is already the intended current behavior, do you have a reproducible example where this doesn't happen?

**Comment by michaellee8** [comment]
![screenshot from 2017-09-01 04-01-32](https://user-images.githubusercontent.com/16556558/29943230-55001b9c-8ecb-11e7-9473-df80377fd8af.png)
atom-prettier debug
```
Atom version: 1.19.3
prettier-atom version: 0.37.0
prettier version: 1.5.3
prettier-eslint version: 6.4.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "useEslint": false,
  "useEditorConfig": true,
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  },
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```
@robwise  I have never saw your described behavior, do I need to turn on anything for it?

**Comment by robwise** [comment]
@michaellee8 do you have the `linter` package installed and enabled?

**Comment by michaellee8** [comment]
Ah I have disabled `linter` package as suggest by `nuclide-diganostics`. Does it matters? Can Nucide Dignanostics do the trick?

**Comment by robwise** [comment]
@michaellee8 can you enable `linter` and see if the errors show up?

**Comment by michaellee8** [comment]
After looking deeper, I found that the error is shown in the Dignaostics page, hence i must admit I am pretty blind XD. However, I would like to say it could be more conveient and obvious if we can get an active pop-up or notification instead of a pasive single line warning.

**Comment by robwise** [comment]
I'm not sure how diagnostics works as I don't use that, in linter it pops up from the bottom as well as highlighting the code inline. I had it as a popup but people complained it was too intrusive so I switched it to the linter way, which is pretty much the standard for this type of thing AFAIK.

**Comment by michaellee8** [comment]
Maybe that is a nuclide problem, I will check it out later
