### ISSUE TITLE
Do not fallback to defaults if ESLint configuration is bad

### ISSUE THREAD

**Issue by AlicanC** [prettier/prettier-atom#262]
If prettier-eslint or prettier-eslint-cli is installed and there is something wrong with them, prettier-atom shouldn't fallback to defaults and provide a useful error instead.

Steps to reproduce:
- Clone this repo
- Make a mess in ".eslintrc.yml"
- Format a file

**Comment by robwise** [comment]
@AlicanC I'm a bit confused by this one. We provide fallbacks _before_ running prettier-eslint (there are no current fallbacks for prettier). If there is an error thrown by prettier-eslint, we throw that error. If prettier-eslint does not throw an error, prettier-atom can't know there was an error. Maybe this is something we should put on the prettier-eslint repo instead?

**Comment by AlicanC** [comment]
When making my own ESLint config, I've had a case where prettier-eslint-cli formatted correctly (`yarn prettier-eslint -- "src/**/*.js" --write`) but atom-prettier's "Format on Save" acted like I don't have PEC at all.

Since it worked with PEC and not AP (which uses PEC) I thought there was something wrong about how AP called PE/PEC.

This commit (which uncomplicated my config) fixed the issue and made it work with both PEC and AP:
https://github.com/svtek/javascript/commit/44501cce6282ce0d4de5e5b175392300560041c3

If AP doesn't have an algorithm like "if PEC fails, use defaults" then this must be a problem with PEC, but as I said, running PEC worked perfectly where AP's "Format on Save" didn't.

**Comment by darahak** [comment]
We do not pass the ESLint config to `prettier-eslint` as it's inferred from the file path.
Since you had different results with the CLI, can you check if you were using the same version in both cases?

**Comment by robwise** [comment]
I'm not sure what actionable things we can really do for this issue. We don't do any looking up of the eslintrc with this package, it's all done under the hood by prettier-eslint. If prettier-eslint throws any errors, we rethrow them. I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
