### ISSUE TITLE
Not picking up eslintrc file

### ISSUE THREAD

**Issue by andy9775** [prettier/prettier-atom#263]
I have an .eslintrc file in the root of my project directory and I have `ESLint integration` checked in the plugin and yet it is not picking up my eslint file.  Running prettier-eslint from the command line outputs the correctly formatted file so it doesn't seem to be an issue with my configuration files.

**Comment by darahak** [comment]
Do you have `prettier-eslint` in your project? If yes, is it up to date?
Did you check the DevTools console for errors?

**Comment by andy9775** [comment]
Yes, `"prettier-eslint": "^8.0.0",` installed and no error's being reported. 

For my JSX settings, for example, my eslint config specifies that props should be on their own separate line and after running prettier it places them on one line.

Debug outputs `"useEslint": true` and `"useEditorConfig": true`

**Comment by robwise** [comment]
You didn't enable `run prettier last` by chance did you?

**Comment by andy9775** [comment]
No. I did re-install everything (including atom) and it's picking up the file however it's not formatting correctly. For example I have `"react/jsx-max-props-per-line": [2, {"maximum": 1, "when": "always" }]` set and after running prettier some, not all, JSX props are placed on the same line. For example:

```
  <Card className={cardClass} key={announcement.id}>
```

instead of
```
  <Card className={cardClass}
            key={announcement.id}>
```

I get an eslint error on the key but yet prettier doesn't format it correctly.

**Comment by darahak** [comment]
What's the ESLint error?

**Comment by andy9775** [comment]
It fails the rule (linting)
`react/jsx-max-props-per-line: Prop 'key' must be placed on a new line`

**Comment by darahak** [comment]
I made a minimal sample with your code and it works fine.

Again, did you check DevTools if there are errors?
There could be a parsing error somewhere.

Also update `prettier-eslint` to 8.1.0 to avoid API incompatibilities.

**Comment by andy9775** [comment]
I'll put together a sample project and invite you

**Comment by darahak** [comment]
I'm closing this stale issue, since we could not reproduce the bug and had no news for a while.
Feel free to re-open it if you still have the problem.
