### ISSUE TITLE
prettier-atom failed: Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by sonukj** [prettier/prettier-atom#268]

**Comment by chesleybrown** [comment]
Just updated to the latest version. Consistently get this error every time I save a JS file now. I've tried restarting atom to no benefit.

Running `0.39.0`.

**Comment by kwhitaker** [comment]
I'm also seeing this issue this morning (worked fine yesterday).  It happens when I save a file.

**Comment by M-ZubairAhmed** [comment]
@sonukj have you looked at this issue [267](https://github.com/prettier/prettier-atom/issues/267). 
In your dev dependencies update prettier to 1.7.0

**Comment by JamieDixon** [comment]
We're also seeing the same problem after upgrading to 0.39.0.

**Comment by chesleybrown** [comment]
Can confirm as suggested in #267, updating to prettier 1.7.0 in my `package.json`, doing a fresh `npm install` and restarting atom resolved the problem for me.

**Comment by sonukj** [comment]
@chesleybrown upgrading to 1.7.0 didnt solve my issue..still getting the error

**Comment by souporserious** [comment]
@sonukj did you clear out `node_modules` and reinstall? It worked for me after following @chesleybrown's steps.

**Comment by erickeno** [comment]
@sonukj after upgrading try restarting you atom editor.

**Comment by robwise** [comment]
Let's track this in #267

**Comment by sonukj** [comment]
@chesleybrown  now the issue solved thanku all
