### ISSUE TITLE
How to define your own settings and what settings are there. Jshint: Misleading line break before '?'

### ISSUE THREAD

**Issue by mvaneijgen** [prettier/prettier-atom#273]
I work with a Wordpress theme that uses jshint to compile all the JS and with love to use Prettier with it  but for jshint doesn't like it when every thing is put on a new line in my JS and I have know Idea what  the setting is called or what to Google for. 

I write this line of code

```js
target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
```

And it will expand to 

```js
    target = target.length
          ? target
          : $('[name=' + this.hash.slice(1) + ']');
```

And then my jshint will state `Misleading line break before '?'; readers may interpret this as an expression boundary.` can some one point me to a settings overview that I could try to disable this way of expanding and where to put these settings inside Atom

**Comment by darahak** [comment]
There is no setting in Prettier to change that.

You can either use [prettier-ignore comments](https://github.com/prettier/prettier#excluding-code-from-formatting) or disable the [laxbreak](http://jshint.com/docs/options/#laxbreak) rule in your file.
