### ISSUE TITLE
Not working "trailingComma"

### ISSUE THREAD

**Issue by tell-y** [prettier/prettier-atom#281]
My setting is below:
```
{
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "es5"
}
```

Then, when I formatted code which is used a function, last argument of the function is added comma.
(I tried to format on VSCode, It was success)

My expected is below:
```
sampleFunction(
  arg01,
  arg02 // But formatted result is 'arg02,'
);
```

thanks.

<details>

```json
Atom version: 1.19.5
prettier-atom version: 0.40.0
prettier version: 1.7.0
prettier-eslint version: 8.1.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "parser": "flow",
    "printWidth": 100,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "tabWidth": "auto"
  },
  "useEditorConfig": false,
  "useEslint": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```
</details>

**Comment by robwise** [comment]
Do you have `ESLint Integration` enabled? Are those settings the prettier config file settings or the prettier-atom package's settings?

**Comment by tell-y** [comment]
Thank you for your response.
Yes, I checked on `ESLint Integration` at atom setting page.

**Comment by robwise** [comment]
Please show your eslint config file, prettier config file, and atom prettier settings

**Comment by tell-y** [comment]
My package.json setting is below(no eslint config file and prettier config file):
```
{
  ~~~
  "prettier": {
    "printWidth": 100,
    "singleQuote": true,
    "trailingComma": "es5"
  },
  "eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "experimentalObjectRestSpread": true
      }
    },
    "extends": [
      "airbnb",
      "prettier",
      "prettier/react"
    ],
    "plugins": [
      "prettier"
    ],
    "rules": {
      "prettier/prettier": [
        "error",
        {
          "printWidth": 100,
          "singleQuote": true,
          "trailingComma": "es5"
        }
      ],
      "global-require": "off",
      "no-param-reassign": [
        "error",
        {
          "props": true,
          "ignorePropertyModificationsFor": [
            "req"
          ]
        }
      ],
      "no-restricted-properties": "warn",
      "react/forbid-prop-types": "warn"
    }
  },
  ~~
}
```

atom prettier settings are below (only checked and selected, others no set):
- ESLint Integration
- Ignore Files in '.eslintignore'
- Single Quotes
- Bracket Spacing
- Semicolons
- Print Width -> 100
- Trailing Comma -> es5
- Javascript Parser -> flow

**Comment by darahak** [comment]
`eslint-config-airbnb-base` defines `comma-dangle` as:

```js
  'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'always-multiline',
    }],
```

But you also extend `eslint-config-prettier` which should disable that rule, so it's weird...
Can you try to see what are the exact rules being applied to your file?

Run:
```
eslint --print-config <path-to-your-file.js>
```

**Comment by tell-y** [comment]
Running result is here: [https://gist.github.com/tell-y/029ecbeab7ba37a98d5359a6ec9ee595](https://gist.github.com/tell-y/029ecbeab7ba37a98d5359a6ec9ee595)

**Comment by darahak** [comment]
You have `comma-dangle` as `off`, but then you also have `no-comma-dangle` as `off`.
Maybe it's re-enabling dangling commas. Can you try to remove it?

**Comment by tell-y** [comment]
I don't set those setting...

anyway, I tried to change `"ecmaVersion": 6,` to `"ecmaVersion": 2017,` of eslintConfig/parserOptions, then it could work correctly!

**Comment by darahak** [comment]
That's because dangling commas in function parameter lists are part of ES2017.
See [here](https://github.com/tc39/proposals/blob/master/finished-proposals.md).

I guess it's not a problem as long as it stays compatible with the platforms you're targeting (via transpiling).

**Comment by tell-y** [comment]
I see.
Thank you for your supporting. @darahak @robwise 

I think it should work with `"ecmaVersion": 6`(`"ecmaVersion": 2015`), however maybe I have a chance to write code as ES2017 soon this project soon, so this solution is enough for me 👍

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
