### ISSUE TITLE
Not working anymore with local network address

### ISSUE THREAD

**Issue by GuillemotF** [prettier/prettier-atom#283]
After upgrading to 0.40.0 prettier can't run on files accessed by a local network address like \\192.168.x.x\project\app\index.js
It throws `prettier-atom failed: UNKNOWN: unknown error, open '\192.168.x.x\package.json\'`
It was working before upgrading but i don't know if this bug was introduced in 0.39 or 0.40.

Windows 10 64 Pro
Atom 1.20.1

Prettier debug : 
<details>
 Atom version: 1.20.1
prettier-atom version: 0.40.0
prettier version: 1.7.0
prettier-eslint version: 8.1.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "useEslint": true,
  "useEditorConfig": true,
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  }
}
</details>

**Workaround** : Prettier-atom works when mounting a network drive (giving atom a new address to the files like Z:\project\app\index.js)

**Comment by darahak** [comment]
I reproduced it, but I don't know why it only appeared recently.
It happens when the package looks for config files or ignore lists.

If you set breakpoints on exceptions in DevTools, there are a lot of them (for `.eslintignore`, `.prettierrc`, etc.) and it only shows the last (not sure why either).

**Comment by robwise** [comment]
Well, we're using a different library for the two of them. The prettier config is found using a method from prettier itself, and it seems they throw or don't handle this scenario properly? I think this one probably needs to be fixed on prettier's repo?

**Comment by GuillemotF** [comment]
You're right, this is a prettier bug, i tried to run this scenario from prettier cli command, it throws `no matching files` even with --no-config option.
This is not working since 1.6.0 release.

**Comment by robwise** [comment]
@GuillemotF Can you do me a favor and make an issue for this on the prettier repo, and I will close here?
