### ISSUE TITLE
prettier-atom failed: Cannot find module 'estraverse'

### ISSUE THREAD

**Issue by robertdmunn** [prettier/prettier-atom#284]
Using prettier-atom with eslint on macOS High Sierra. Saving a JavaScript file results in the error message:

prettier-atom failed: Cannot find module 'estraverse'

The editor does not automatically format the code on save as it is configured to do.

Note that I am editing files residing on a local Windows Server 2008 virtual machine, which I access from macOS using an SMB share.

Here is the output of Prettier: Debug

<details>

```json
prettier-atom: details on current install

Atom version: 1.20.1
prettier-atom version: 0.40.0
prettier version: 1.7.0
prettier-eslint version: 8.1.1

prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": true
  },
  "useEslint": true,
  "useEditorConfig": true,
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  }
}
```
</details>

I am using an eslintrc.js file, but this error occurs without the presence of eslintrc.js as well. Here is my .eslintrc.js config file:

<details>

```js
module.exports =
 {
  "rules": {
        "indent": [
            2,
            "tab"
        ],
        "quotes": [
            2,
            "double"
        ],
        "linebreak-style": [
            0,
            "windows"
        ],
        "semi": [
            2,
            "always"
        ],
        "no-tabs":[
          0,
          "allow"
        ],
        "no-var":[
          0,
          "allow"
        ],
        "object-curly-spacing":[
          0
        ],
        "max-len":[
          0
        ],
        "quotes":[
          0
        ],
        "spaced-comment":[
          0
        ],
       "comma-dangle": [2,
         "never"],
        "keyword-spacing":[
          2,
        { "before" : false,
         "after" : false }
       ],
       "space-before-blocks":[
         2,
         "never"
       ]
    },
    "extends": "google"
};
```
</details>

**Comment by darahak** [comment]
I don't know where this comes from. It's not from our direct dependencies.
There could be a conflict or outdated package in your project?

**Comment by robertdmunn** [comment]
I have more information for you. The plugin works when I am editing JavaScript files on my local Mac drive instead of over the SMB share. Just verified that functionality.

All of my packages say they are updated. I have 90 installed packages, would not be shocked for there to be a conflict somewhere. Still, it looks like the problem may be specific to SMB shares. I know there is an existing bug where editing files over SMB can cause file locks on the system where the files live. For instance, I generally have to close Atom before I do a Git pull or checkout.

**Comment by robwise** [comment]
I'm not really knowledgeable about SMB shares or what is conflicting with that. It may be one of our dependencies, probably `prettier` itself? I'm not sure how to go forward with this, so I'm going to close for now. Please let me know if there is something that can be done to fix this.
