### ISSUE TITLE
Show in status bar not always working

### ISSUE THREAD

**Issue by josh-stevens** [prettier/prettier-atom#285]
Sometimes while "Show in status bar" is enabled, the Prettier toggle in the status bar will disappear. It will reappear when I go into the preferences and check and uncheck it, but disappear again in certain files. I'm not entirely sure what conditions cause it to disappear (usually when there is a lot of stuff going on in the status bar I think).

This is a pretty big one for me, since sometimes I'm working with other people's repositories and they aren't using Prettier formatting (or adhering to their own lint rules) and I don't want my small changes to format their whole files, so it's nice to be able to toggle Prettier on the fly.

**Comment by robwise** [comment]
Yes, this way you don't have prettier stuff in your status bar when you're working on unrelated files

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
