### ISSUE TITLE
Support for `prettier.config.js`

### ISSUE THREAD

**Issue by wldcordeiro** [prettier/prettier-atom#286]
I've been noticing that the plugin doesn't look at my prettier config and modifies code it shouldn't it'd be nice to get detection of the config for prettier.

**Comment by darahak** [comment]
It should already be supported.
Unless it's picking up an old version from your project's dependencies.

**Comment by wldcordeiro** [comment]
I have a config but its body is and I don't think that gets resolved. 🙁 

```js
module.exports = require('@my-namespace/prettier-config')
```

**Comment by darahak** [comment]
Is it working with the CLI?

Cosmiconfig uses [require-from-string](https://github.com/floatdrop/require-from-string/) to parse JS configs. It supports relative requires, but from dependencies? I don't know.

**Comment by darahak** [comment]
I'm closing this issue, since it doesn't seem to be actionable for us.
As I said before, it looks like only relative modules are supported.

If you still need this feature, you should raise the issue with the concerned projects.
