### ISSUE TITLE
Warn user when project local prettier is outdated

### ISSUE THREAD

**Issue by t9md** [prettier/prettier-atom#290]
When people see error because of "project local `prettier` was old".
Removing or updating project-local prettier solves problem, but this is not obvious from error message.
So I want atom-prettier warn user to update prettier.

See tweet like this
https://twitter.com/ryanflorence/status/918344031133769730

Related: https://github.com/prettier/prettier-atom/issues/267

**Comment by t9md** [comment]
But why atom-prettier force use to use specific version of prettier?
Ideally maintain multiple prettier executer to support older version of prettier so that updating prettier do not force also update project local prettier.

**Comment by robwise** [comment]
Prettier does support using an older version, as Kent replied, it was a mistake in prettier-eslint-cli

**Comment by robwise** [comment]
dupe of https://github.com/prettier/prettier-atom/issues/258

**Comment by t9md** [comment]
Are you saying, we'd never see this error?
I'm not sure I understand background correctly, but I myself face this issue and spending some time before noticing uninstall local outdate prettier and use latest globally installed prettier is one of solution.

If this my resolution is effective for other users, I thought adding kind warning is helpful.

Anyway, it's just suggestion, I'm not strong opinion for that.

Thanks for maintaining great atom-prettier pkg, I like this a lot!!

**Comment by darahak** [comment]
No, if we go back on old versions of Prettier, at some point it will break at a different location.
You are right: the error messages that are displayed because of these incompatibilities are not helpful.

That's what I wanted to address by opening #258.

**Comment by t9md** [comment]
Thanks for clarification, understood.
