### ISSUE TITLE
Prettier auto formats JSON removing parens

### ISSUE THREAD

**Issue by wuno** [prettier/prettier-atom#292]
When turning prettier on save. It formats my json by removing the parens. 

For example if I have this, 

```
const apples = {
    'red': 'with seeds'
}

// It changes it to this,

const apples = {
    red: 'with seeds'
}
```

I am using eslint and have a pretty extensive eslintrc file but when I delete the file I still have the same problem. So I think this is for sure a setting within prettier. But I cannot figure out which one. 

Does anyone know how to change the behavior for formatting objects? I want to be able to write json without it being formatting when I save the file to turn it into a JS Object.

**Comment by robwise** [comment]
@wuno Are you sure that Atom recognizes that you are in a JSON scope and not a JS scope?

**Comment by wuno** [comment]
I was wondering about that and looking around to see how I could determine that. 
I am using eslint as well but when I remove all my rules it does the same thing. When I open the app in webstorm the problem does not persist. So it is for sure a prettier thing. 

I am sure it is just a setting I just cannot figure out which one it is.

**Comment by darahak** [comment]
Prettier will always remove quotes when possible, e.g. it will preserve them if you use property names with dashes or whitespace.
If you want it to stay consistent, you can use the [quote-props](https://eslint.org/docs/rules/quote-props) ESLint rule and enable autofix.

Side note: The sample you showed us is JavaScript, and it removed quotes (the title was a bit misleading).

**Comment by wuno** [comment]
This is my current rule in .eslintrc

```
"quote-props": [1, "as-needed"],
```

You are saying I can change this and it will work closer to what i am expecting? Also I shall change the name, sorry about that.

**Comment by darahak** [comment]
If you want to always use quotes for object properties, use `"always"`.
All the options are described [here](https://eslint.org/docs/rules/quote-props#options).

**Comment by olivgilberto** [comment]
when using a .prettierrc config file, set/include property `quoteProps` and set it to `preserve`: `"quoteProps": "preserve"`

**Comment by safinghoghabori** [comment]
> On VSCode, when using a .prettierrc config file, set/include property `quoteProps` and set it to `preserve`: `"quoteProps": "preserve"`

It will always add quotes to the property or only when it needs?

**Comment by stefantrinh1** [comment]
To DO Via UI and globally

Code/File > Preferences > Settings > Search "quote props" > Prettier: Quote Props > preserve

**Comment by musasahinkundakci** [comment]
> To DO Via UI and globally
> 
> Code/File > Preferences > Settings > Search "quote props" > Prettier: Quote Props > preserve

It doesnt work jesus ıt is killing me

**Comment by musasahinkundakci** [comment]
> > To DO Via UI and globally
> > Code/File > Preferences > Settings > Search "quote props" > Prettier: Quote Props > preserve
> 
> It doesnt work jesus ıt is killing me

Btw ı did what you said it didnt work because of Use Editor Config.when ı clicked Use Editor Config to unclicked ,it s worked :D

**Comment by atlasdevorient** [comment]
> 
> 
> @wuno Are you sure that Atom recognizes that you are in a JSON scope and not a JS scope?

happens in VSCode too.

**Comment by RevanYana** [comment]
> To DO Via UI and globally
> 
> Code/File > Preferences > Settings > Search "quote props" > Prettier: Quote Props > preserve

thanks its work for me

**Comment by Cayllen** [comment]
Not sure why this is not default, just confusing - or does it also work without the props?
In my example it removed the "" from tz and it wrote tz: tz which I assume is wrong
<img width="281" alt="image" src="https://user-images.githubusercontent.com/27898791/217229884-0f9b2cc6-521e-47c0-8fae-75ea13074c11.png">
