### ISSUE TITLE
Not openning remote file

### ISSUE THREAD

**Issue by titanve** [prettier/prettier-atom#294]
Hello all!
I'm openning a folder (project) from a server on my network and every time I hit `Save` it shows this error
![image](https://user-images.githubusercontent.com/4803351/31958231-b26fb21e-b8b6-11e7-9da9-1355486da490.png)
What can I do? The remote path for the project folder is: `./C:/192.168.1.42/Anonymous/intralab` (taken from copy relative path) and from windows explorer `\\192.168.1.42\Anonymous\intralab\application\single_pages\pedido`
Thanks for your help

**Comment by robwise** [comment]
@titanve I assume this has something to do with the fact that it's remote, I'm not sure if we support that, or if Atom does as far as its resolveConfig function?

**Comment by titanve** [comment]
Hey @robwise what do you suggest?
Thanks

**Comment by robwise** [comment]
Hey sorry for not getting back to you, this slipped through the cracks. I'm not really sure what to do about this as I'm not sure where the code is erroring. Can you open your Atom dev tools and see if there is a stack trace where this is happening?
