### ISSUE TITLE
Prettier not fixing too long line

### ISSUE THREAD

**Issue by whitelizard** [prettier/prettier-atom#296]
Have been using prettier for a great while and are very happy with it. Today however I got this problem with a line that was too long, that prettier just would not format correctly.

Here is the line, with a minimal environment for a happy eslint.
```js
export default class Test {
  test = async ({ records, properties, mode }, path) => {
    const res = await Promise.all(records.map(r => super.update({ rid: r.rid, properties, mode }, path)));
    return res;
  };
}
```
What I get in Developer Tools console:
![image](https://user-images.githubusercontent.com/8565497/31994004-63e2b5d2-b97f-11e7-9c7e-37eaa95e0c2b.png)

Atom version: **1.17.2** (Ubuntu)
Prettier-atom version: **0.40.0**

.eslint:
```json
{
  "parser": "babel-eslint",
  "extends": "airbnb-base",

  "rules": {
    "no-restricted-syntax": [0],
    "no-mixed-operators": [0],
    "no-underscore-dangle": [0],
    "arrow-parens": [2, "as-needed"],
    "class-methods-use-this": [0]
  },

  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
}
```

Prettier settings:
![image](https://user-images.githubusercontent.com/8565497/31994427-e64bfffa-b980-11e7-92a3-2f42ce844625.png)

![image](https://user-images.githubusercontent.com/8565497/31994450-00bdc68e-b981-11e7-87d7-7bb083d1e7e8.png)

If I enable "Run Prettier Last" it will break the line, but will generate even more eslint errors.

**Comment by whitelizard** [comment]
Another example:

`const replies = await Promise.all(rule.apiData.map(entry => this.c.rpc.p.make(entry[1], entry[2])));`

**Comment by robwise** [comment]
@whitelizard Are you still having this issue?

**Comment by darahak** [comment]
If there is an issue, it's probably for `prettier-eslint`; the CLI gives the same result.
There is a set of rules from the `airbnb-base` config that is messing with the format.

The easy solution is to also use `eslint-config-prettier` to disable style rules that could interfere with Prettier.
