### ISSUE TITLE
prettier-atom failed: Couldn't resolve parser "scss"

### ISSUE THREAD

**Issue by gaohailang** [prettier/prettier-atom#297]
I encounter this error when I save my unformatted scss file.

<details>
Atom version: 1.19.2
prettier-atom version: 0.40.0
prettier version: 1.7.4
prettier-eslint version: 8.2.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "index.scss"
    ],
    "enabled": true,
    "isDisabledIfNotInPackageJson": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "semi": false,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon"
  },
  "useEslint": true,
  "useEditorConfig": true
}
</details>

**Comment by robwise** [comment]
@gaohailang Do you have a prettier config?

**Comment by panuhorsmalahti** [comment]
I had this error (and I didn't have a prettier config). I fixed it by updating prettier from 1.7.0 to 1.8.2 and restarting Atom.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
