### ISSUE TITLE
CSS Grid Template Areas

### ISSUE THREAD

**Issue by amirmishani** [prettier/prettier-atom#300]
The proper way to show CSS Grid template areas should be:

```
grid-template-areas:
      'header header header' 
      'main main sidebar'
      'main main sidebar'
      'footer footer footer';
```
However the code gets all put in one line with text wrapping based on your personal prefs.

**Comment by robwise** [comment]
@amirmishani Please make an issue on the prettier repo, this is just the atom integration

**Comment by amirmishani** [comment]
Will do. Thanks.
