### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-atom#304]
We could provide more helpful, repo-specific information about code style, paradigms in use, etc.

https://github.com/prettier/prettier-atom/issues/303#issuecomment-343319708

**Comment by olsonpm** [comment]
I just started messing with postcss the last couple days - [their code docs](https://github.com/postcss/postcss/tree/master/docs) are great and can serve as reference.

I'm trying to get some other stuff done so I won't be working on this item.

**Comment by robwise** [comment]
Closing for now, I think people don't really read contributing even as-is anyway.
