### ISSUE TITLE
Allow to format on save for markdown files

### ISSUE THREAD

**Issue by pvdlg** [prettier/prettier-atom#309]
When the focus is on a markdown file the `Prettier` menu is the status bar is not visible even if the option `Show in status bar` is enabled.

When saving, the js code within fences is not formatted.

When running the command `Prettier:Format` the code is formatted as expected.

**Comment by robwise** [comment]
I can't reproduce this, it seems to be working fine for me (both the checkmark in the status bar showing up on markdown files properly as well as the formatting of JS fenced code blocks using format on save). Are you sure that your markdown scopes are correct?

**Comment by pvdlg** [comment]
Are you sure that your markdown scopes are correct?

It's not set so I assume it uses the default. If I set it to `source.md, source.gfm` the problem persist.

According to [menus/prettier-js.json#L3](https://github.com/prettier/prettier-atom/blob/ca06e71d6c74610d06ac7c7d4b8037ebbc97075b/menus/prettier-js.json#L3) the `Prettier` menu is supposed to appear only for `js` or `js jsx` source type.

So I imagine there must be something in your atom config (or missing in mine) that makes `prettier-atom` to consider the js in fences as `source js`.

In my markdown the js fences look like ```js

**Comment by robwise** [comment]
> It's not set so I assume it uses the default. If I set it to source.md, source.gfm the problem persist.

Yes this is true

> According to menus/prettier-js.json#L3 the Prettier menu is supposed to appear only for js or js jsx source type.

That looks like a bug but that's actually for a different thing (the command palette). The code for the tile is here: 

https://github.com/prettier/prettier-atom/blob/master/src/statusTile/updateStatusTileScope.js

Basically, if the current scope matches any scope in all of your settings, it should come up.

> So I imagine there must be something in your atom config (or missing in mine) that makes prettier-atom to consider the js in fences as source js. In my markdown the js fences look like ```js

I can't think of what it would be, and that is how my JS fences look too

**Comment by pvdlg** [comment]
I'm use [language-markdown](https://atom.io/packages/language-markdown). I don't know if it's related.

In `prettier-atom` plugin configuration, if I add `text.md` to the scope it works as expected.
I don't know why the markdown file doesn't match the default value of `source.gfm, source.md`.

Maybe it would be a good idea to add `text.md` to the default value ?

**Comment by robwise** [comment]
@pvdlg if you do `Editor: Log Cursor Scope` what do you get? I didn't realize there was a `text.md`, but yeah that sounds like it should be something that we should add to the defaults?

**Comment by pvdlg** [comment]
If my cursor is outside fences:
- text.md

If my cursor is in js fences:
- text.md
- fenced.code.md
- source.embedded.js

**Comment by robwise** [comment]
Oh interesting, mine is coming as `source.gfm`. That must be the problem, it must depend on which package you use (I use markdown-writer). Yeah, I think we should add `text.md` to the default scopes. Would you mind making a quick PR?

We'd just need to change this line here: https://github.com/prettier/prettier-atom/blob/master/src/config-schema.json#L119

If so, please check out the conventional changelog commit message format so it shows up in the changelog automatically

**Comment by pvdlg** [comment]
> Would you mind making a quick PR?

#312

> If so, please check out the conventional changelog commit message format so it shows up in the changelog automatically

👍 I maintain https://github.com/semantic-release/semantic-release :)

**Comment by robwise** [comment]
hahahaha my bad! Preaching to the choir!
