### ISSUE TITLE
0.43.0: Error when saving if "useTabs" is enabled

### ISSUE THREAD

**Issue by poacher2k** [prettier/prettier-atom#316]
Heyo!

After upgrading to the latest version, I'm getting this when saving. I added a `console.log('options', options);` in the place where it failed. see console output:

![image](https://user-images.githubusercontent.com/2255960/33602802-bfd197a4-d9b0-11e7-864a-8be1d6670d61.png)

If I disable "use tabs" in the prettier-atom options, everything works fine without any errors.

**Comment by darahak** [comment]
Related to https://github.com/prettier/prettier/issues/3399.
Solved by https://github.com/prettier/prettier/pull/3401.

Will probably be included in the next release.
