### ISSUE TITLE
value.indexOf is not a function

### ISSUE THREAD

**Issue by derwaldgeist** [prettier/prettier-atom#317]
Since the latest updated to prettier-atom, I am constantly getting this error when trying to save a file:

```
prettier-atom failed: value.indexOf is not a function
```

Content of the file doesn't matter, nor does file type (JavaScript, SCSS, ...).

**Comment by mwamodojnr** [comment]
I have the same issue. I have just removed the latest upgrade and reinstalled the a previous version 0.41.0

**Comment by derwaldgeist** [comment]
@mwamodojnr Did this downgrade help? For me, it didn't work.

**Comment by derwaldgeist** [comment]
It's weird. I got it working by deactivating about half of my add-on packages and reactivating them afterwards. I have no clue why this helped.

**Comment by zimme** [comment]
This was a problem in `prettier-eslint`. Which is fixed now.

**Comment by derwaldgeist** [comment]
Thanks!
