### ISSUE TITLE
"Error: prettier-atom attempted to set messages with linter package, but was unable." after reopening a file

### ISSUE THREAD

**Issue by MaxJohnsen** [prettier/prettier-atom#318]
Anyone else having issues with Linter errors not showing up after reopening a file within Atom?

The console logs the following error-message:

`/Users/max/.atom/packages/prettier-atom/dist/linterInterface/index.js:25 prettier-atom attempted to set messages with linter package, but was unable. Messages: [{"location":{"file":"/Users/max/Desktop/test.js","position":{"start":{"row":0,"column":11},"end":{"row":0,"column":11}}},"excerpt":"Unexpected token","severity":"error"}]`

Steps to reproduce:
- Open Atom
- Create a new JavaScript file
- Add a line of valid code, e.g. `const num = 5;`
- Introduce an error to the code, e.g `const num =, 5;` - A Linter error from prettier shows up as expected after saving
- Remove the error from code - Linter error disappears as expected after saving
- Close the file and reopen it using the sidebar
- Introduce a new error to the code - Linter error-message does **not** show up after saving

OSX 10.13.1 (17B1003)

<details>

```
Atom version: 1.22.1
prettier-atom version: 0.43.0
prettier version: 1.9.0
prettier-eslint version: 8.2.4
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon"
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true
}
```

</details>

**Comment by darahak** [comment]
Thanks for reporting.

Is the context similar to https://github.com/prettier/prettier-atom/issues/298?
If yes, let's track the problem there and close this one.
