### ISSUE TITLE
Nuclide remote: prettier-atom attempted to set messages with linter package, but was unable. Messages: []

### ISSUE THREAD

**Issue by burdakovd** [prettier/prettier-atom#322]
I'm seeing this error when editing remote file with Nuclide (every time on save I get this error, and can't achieve format-on-save functionality).

```
~/.atom/packages/prettier-atom/dist/linterInterface/index.js:25 prettier-atom attempted to set messages with linter package, but was unable. Messages: []
```

I've applied https://github.com/prettier/prettier-atom/pull/321 locally, and the error still persists.

After adding some more logs around the line where the error is being logged, I see that it was caused by file path being undefined rather than by Linter being null.

The error is logged here: https://github.com/prettier/prettier-atom/blob/e8e8e3fc4da30082a8d70f341b729c46a7771823/src/linterInterface/index.js#L19

In my scenario messages appear to be `[]`, filePath is `undefined`, and delegate is an instance of `IndieLinterDelegate`.

Further, editor from which undefined file path is extracted is a TextEditor that contains remote file in there. Is remote editing something that is supported at all for Prettier?
![image](https://user-images.githubusercontent.com/5193161/33798643-4fd0b96e-dd14-11e7-832e-baccd2cf5a7a.png)

As a workaround I ended up removing `prettier-atom`, integrated `prettier` into `eslint` on the server, and ran `esw --watch --fix` on the server side. Then whenever I'm saving a file from Nuclide, server-side linter attempts to fix it (including formatting according to Prettier), then Nuclide detects that file has  changed remotely and reloads it.

**Comment by SavePointSam** [comment]
I'm located the bug and am working on the fix now.

**Comment by robwise** [comment]
prettier-atom 0.48.1 is released with this fix so I am closing. Please let me know if there continue to be issues, and thanks to @SavePointSam for the fix!
