### ISSUE TITLE
[Feature Request] Insert Pragma

### ISSUE THREAD

**Issue by ZakTax** [prettier/prettier-atom#324]
If [requirePragma](https://prettier.io/docs/en/options.html#require-pragma) is enabled, prettier-atom respects that and doesn't alter formatting.

Would it be possible for prettier-atom to detect this and display a notification asking if user wants to insert the pragma at top of file? Clicking yes would insert and re-format the file.

**Comment by robwise** [comment]
I think this may now be fixed in 0.55.0 as we defer pretty much everything to Prettier.
