### ISSUE TITLE
can not format vue style block

### ISSUE THREAD

**Issue by magicdawn** [prettier/prettier-atom#327]
a Vue file looks like this
```vue
// app.vue

<template>
  <html-code></html-code>
</template>

<script>
// js code
</script>

<style lang='less'>
// less code
</style>
```

And the less code's scope is `source.css.less.embedded.html`, so I add this scope to `cssScope` setting. But it does not work for style block, and the script block works.

Since this is scope related, I believe this is atom and prettier-atom related.

<details>
Atom version: 1.23.1
prettier-atom version: 0.43.1
prettier version: 1.9.2
prettier-eslint version: 8.3.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.css.less.embedded",
      "source.css.less.embedded.html",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "isDisabledIfNoConfigFile": true,
    "showInStatusBar": true,
    "enabled": false,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "prettierEslintOptions": {
    "prettierLast": true
  },
  "prettierOptions": {
    "semi": false,
    "singleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon"
  },
  "useFlowParser": false,
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true
}
</details>

**Comment by magicdawn** [comment]
more info: prettier can format a `.less` file, but not a less block

**Comment by darahak** [comment]
Vue is not really supported by Prettier.
There is a hack in `prettier-atom` that lets you format the `script` part, but that's it.

If you want to follow the issue, go to https://github.com/prettier/prettier/issues/2097

**Comment by darahak** [comment]
Support will come with Prettier 1.10.
See this PR: https://github.com/prettier/prettier/pull/3563

We will close this issue when it's released and we update our dependency.

**Comment by magicdawn** [comment]
Sorry to say that another question appears:

> prettier-atom failed: Couldn't resolve parser "vue"

**Comment by magicdawn** [comment]
![image](https://user-images.githubusercontent.com/4067115/35031789-69ee61f8-fb9f-11e7-9605-57049f47a110.png)

**Comment by magicdawn** [comment]
And I tried latest prettier cli with this `.vue` file, there is no error~

**Comment by robwise** [comment]
@magicdawn can you uninstall and reinstall atom, you might not have the latest bundled version of prettier or something somehow
