### ISSUE TITLE
Duplicate last lines

### ISSUE THREAD

**Issue by pedrouid** [prettier/prettier-atom#328]
I've been getting an issue for about a week now, not sure when was the last update but this seems to be directly from `prettier-atom` rather `prettier`. 
Currently running on `prettier-atom@0.43.1` and installed globally is `prettier@1.8.2`.
Everytime I save a file (formatting on save is enabled) I get duplicate last lines, sometimes two or three lines but it seems to correlate with the second last semicolon on the file
(see screenshot for example)
<img width="297" alt="screenshot 2017-12-19 14 17 26" src="https://user-images.githubusercontent.com/10136079/34161250-f7e0e146-e4c7-11e7-9e21-93b1ce790b4c.png">

**Comment by leehankyeol** [comment]
This also occurs with no-semicolon setting. To me, it happens when `prettier-atom` automatically creates line breaks for formatting.

**Comment by stclairdaniel** [comment]
This is happening to me as well, happy to provide any information that could be helpful.

**Comment by robwise** [comment]
> @robwise This could have something to do with updating the text buffer via diff?

Yes, I was thinking the same exact thing. I think personally I've noticed that with brand new files, it adds an extra blank line at the end.

**Comment by c10b10** [comment]
I'm having this issue too. Cursor also sometimes moves at reformat.

**Comment by lestato9** [comment]
I have this issue too. Any help is appreciated

**Comment by robwise** [comment]
I've been able to reproduce this as far as inserting an extra newline at the end of the file if I delete all lines following the last line of text. However, I can't get it to do what happened in the OP's screenshot. I'm worried that what I'm having happen is due to a different problem than what you guys are seeing. Is this happening with every single file?

**Comment by robwise** [comment]
I released 0.44.0 that should fix the extra newline problem (#333), can you check whether you are still having the issue?

**Comment by leehankyeol** [comment]
@robwise The issue seems to be gone in my case.

**Comment by stclairdaniel** [comment]
@robwise It appears to be gone for me as well. Thanks for the quick fix!

**Comment by robwise** [comment]
Awesome!

**Comment by heisian** [comment]
~~moral of the story: always keep your plugins up-to-date, unless of course, the update is going to regress a bug.~~

moral of the story: always google first
