### ISSUE TITLE
about eslint arrow-parens requireForBlockBody

### ISSUE THREAD

**Issue by enjoyZhou** [prettier/prettier-atom#329]
Do not support this requireForBlockBody?

[https://eslint.org/docs/rules/arrow-parens.html#requireforblockbody](https://eslint.org/docs/rules/arrow-parens.html#requireforblockbody)

**Comment by robwise** [comment]
@enjoyZhou this sounds like a prettier-eslint issue, can you check over there?

**Comment by enjoyZhou** [comment]
I mean like this example...

Before format：
`Api.update(params).then((res) => {});`
After format：
`Api.update(params).then(res => {});`

The parentheses are missing！I need to keep the **‘(res) ’** parentheses

**Comment by robwise** [comment]
@enjoyZhou I understand, but this type of thing is done by the prettier-eslint package, not the prettier-atom package?

**Comment by enjoyZhou** [comment]
Sorry, So I need to install the prettier-eslint  plug-in for Atom?

**Comment by robwise** [comment]
If you don't have prettier-eslint in your local repo, then we fall back to a bundled version of prettier-eslint. You have enabled the eslint integration in your prettier-atom settings, right?

**Comment by enjoyZhou** [comment]
ATOM v1.23.1 x64
prettier-atom v0.45.0

`  "prettier-atom":`
   ` formatOnSaveOptions: {}`
    `prettierEslintOptions: {}`
   ` prettierOptions:`
      `jsxBracketSameLine: true`
      `printWidth: 100`
      `singleQuote: true`
     ` tabWidth: 2`
     `trailingComma: "es5"`

**Comment by robwise** [comment]
Looks like no? You have to check the prettier-eslint integration checkboxx in order to use prettier-lint.

Also, this could be related to this: https://github.com/prettier/prettier-atom/issues/340
