### ISSUE TITLE
not work integgrate eslint

### ISSUE THREAD

**Issue by webfrontzhifei** [prettier/prettier-atom#339]

**Comment by tquetano-r7** [comment]
So this is not stated very eloquently, but let me try to explain as I'm encountering the same issue.

After doing the most recent update of atom (`1.23.1`) and prettier-atom (`0.45.0`), no longer is my `.eslintrc` file respected ... everything just uses the default prettier formatting. There are no errors or anything that signifies what could be the culprit.

**Comment by agustinf88** [comment]
Same for me. Please help on this!

**Comment by SanderNouwynck** [comment]
The same issue occurs for me, with my eslint config in my package.json file

**Comment by kirkstrobeck** [comment]
+1 for Atom 1.24.0-beta1

**Comment by robwise** [comment]
@kirkstrobeck So the breaking change was something in the Atom 1.24.0-beta1 you think? I will check the release notes and try to figure out if there's something we can fix on our end.

**Comment by robwise** [comment]
Does anyone know if this is related? https://github.com/prettier/prettier-atom/issues/334#issuecomment-354725603

**Comment by mariuslundgard** [comment]
@robwise I’m also experiencing this issue in Atom@1.23.1 (prettier-atom@0.45.0).

**Comment by mrandalldh** [comment]
I just downgraded `prettier-eslint` in `prettier-atom` to version `8.6.2` and worked! All of my `.eslintrc.js` rules are now being respected. It most definitely has to do with issue #334 @robwise

**Comment by Rulsky** [comment]
@mrandalldh thank you for pointing me toward a workaround. With this workaround works in atom@1.23.2

**Comment by p-j** [comment]
Have had the same issue for 2 days now after updating a couple of packages (can't remember which though).
I'm running Atom 1.22.1 with prettier-atom 0.45.0.
I also can confirm that what happens in #334 is what I have too:
cli tools works
prettier-atom alone works
eslint fix file in atom works
prettier-atom + eslint does not work

**Comment by robwise** [comment]
@p-j can you try the fix in @mrandalldh's [post](https://github.com/prettier/prettier-atom/issues/339#issuecomment-354886726)?:

> I just downgraded prettier-eslint in prettier-atom to version 8.6.2 and worked! All of my .eslintrc.js rules are now being respected. It most definitely has to do with issue #334 @robwise

**Comment by mattcolman** [comment]
downgrading prettier-atom to 0.38.0 worked for me. `apm install prettier-atom@0.38.0`

**Comment by p-j** [comment]
@robwise unfortunately no. I've updated the package.json to set fix the version to 8.6.2 and ran yarn again but it didn't help. I'm still losing my parents on my arrow functions and the max-length is not fixed automatically anymore either.

**Comment by darol100** [comment]
@p-j Did you restart your atom? 

 https://github.com/prettier/prettier-atom/issues/339#issuecomment-355872876 : Works perfect for me.

**Comment by darahak** [comment]
Could you continue on #334?
I'd like to avoid scattering information over multiple threads.

Thank you 🙏

**Comment by unordered** [comment]
on my ubuntu 18.04, if project path like ".foo" (system hidden file/folder), eslint interceptor is not working, because the path ignored by eslint!
