### ISSUE TITLE
"Ignore Files in `.eslintignore`" does not work

### ISSUE THREAD

**Issue by scottybrown** [prettier/prettier-atom#347]
By default this is enabled.
I added "test" in .eslintignore, so that linting ignores test files. Seems to work. Also disabled prettier formatting for my test files.
I disabled this feature in the prettier-atom config so I can prettify the test files.
I found that it did no prettifying on any of my test files on save.
I restarted atom and found the same.
Lastly, I removed "test" from .eslintignore and, on save of my test file, the prettifying started working again. So it definitely seems like this feature is having no effect.

I've done some research - I'm certain this is a feature specific to prettier-atom, not something in prettier or eslint themselves.

I'm afraid I can't figure out how to run Prettier: Debug (sorry!). But I can tell you I'm on 0.46.0 of the plugin.

**Comment by darahak** [comment]
Did you enable ESLint integration?

I'm not sure, but it's possible these two options cannot work at the same time.
I'll have to take a look.

**Comment by scottybrown** [comment]
Yes, ESLint Integration is enabled.

You mean that, if ESLint Integration is enabled, it automatically uses the eslintignore file regardless of the this setting? That would be in opposition to the note underneath the setting "Ignore Files in `.eslintignore`" which reads:
"Works regardless of whether ESLint Integration is enabled or not"

**Comment by Maushundb** [comment]
I'm getting the same issue:

eslintignore
```
**/__tests__/*
```

`utils/__tests__/myFile.test.js` is not getting formatted

**Comment by olsonpm** [comment]
Ugh - I misread OP as I thought he was saying the files were not getting ignored.  PR coming shortly

**Comment by robwise** [comment]
> Ugh - I misread OP as I thought he was saying the files were not getting ignored. PR coming shortly

Oh no wonder, so did I lol
