### ISSUE TITLE
eslint --fix not being executed at all

### ISSUE THREAD

**Issue by James2516** [prettier/prettier-atom#350]
**Versions**:

- `prettier-eslint` version: 8.3.1
- `prettier-atom` version: 0.47.0

```
{
  "root": true,
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "env": {
      "es6": true
  },
  "parser": "babel-eslint",
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "react/prop-types": 0,
    "no-console": 0,
    "arrow-parens": ["error", "always"],
    "prefer-template": "error"
  }
}
```

.prettierrc:
```
{
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "true"
}
```

**What I did:**

![](https://i.imgur.com/fgcqM31.png)

I have eslint integration enabled on `prettier-atom`, but it doesn't seem to be running `eslint --fix` at all.

If I enable `linter-eslint`'s Fix errors on save, it'd automatically insert a line after the `import` statement to fix that warning.

However I'm not supposed to do that as it gives a warning:
> prettier-atom: linter-eslint's Fix on Save feature is currently enabled. We recommend disabling this feature when using the ESlint integration from prettier-atom

**Comment by darahak** [comment]
Sorry, we are aware of the issue.
This is being discussed in https://github.com/prettier/prettier-atom/issues/334.

**Comment by knoopx** [comment]
That same happens to me when using the `import/order` rule with `"newlines-between": "always"`. prettier strips lines between imports but `eslint --fix` isn't fixing them after (prettier/eslint --fix cli works fine, prettier-eslint cli doesn't neither). Other rules seem to be applied?
