### ISSUE TITLE
Multiple Pragma entries on save - Markdown files

### ISSUE THREAD

**Issue by schalkneethling** [prettier/prettier-atom#351]
I have a `.prettierrc` file in the root of my project with the following content:

```
{
    "insertPragma": true,
    "singleQuote": true
}
```

Upgraded to prettier-atom today, so I am on version `0.47.0` on Atom `1.23.3`. Created a new Markdown file and after saving the first time, the following was added to the document:

```
/\*_ @format _/
```
This then is the `Pragma` yay! But then, each time I press save, another of these is added, oh no :(

At the top of my JS file the following has been added:

```
/** @format */
```

Again the Pragma for JS files. And here I do not see the same behaviour as described for Markdown files[JSON also seems fine]. While I am at it, I noticed that no Pragma is added to `.css` files, is that expected?

**Comment by darahak** [comment]
Related to this? https://github.com/prettier/prettier/issues/3557

**Comment by schalkneethling** [comment]
> Related to this? prettier/prettier#3557

Ah indeed looks to be, my bad. I just realised that it is "breaking" JSON docs by adding the comment :-/ Thx @darahak  - Marking as duplicate of https://github.com/prettier/prettier/issues/3557
