### ISSUE TITLE
Pick up `~/.prettierrc.json` for non-project files?

### ISSUE THREAD

**Issue by ryanpcmcquen** [prettier/prettier-atom#352]
I couldn't seem to find the answer to this in the other issues or docs, so forgive me if I missed it. One of the things I liked about `atom-beautify`, is that it would pick up the `.jsbeautifyrc` in my home folder (`~/`) for any files I tried to beautify, and read that over the Atom configuration. Does `prettier-atom` have an option like that or do I have to configure it through Atom for non-project files?

**Comment by robwise** [comment]
@ryanpcmcquen Yep, check out https://prettier.io/docs/en/configuration.html

**Comment by ryanpcmcquen** [comment]
Thanks, it seems to be ignoring my `~/.prettierrc.json` ...

**Comment by robwise** [comment]
Try restarting atom, we have to fix the caching in #270
