### ISSUE TITLE
prettier-atom failed: Couldn't resolve parser "vue"

### ISSUE THREAD

**Issue by sidjainn** [prettier/prettier-atom#357]

**Comment by darahak** [comment]
Check your project dependencies if you have at least Prettier 1.10.0.
Older versions are not compatible.

**Comment by mod3x** [comment]
+1
again downgraded to 0.38.0 and works fine

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
