### ISSUE TITLE
ver 0.49.1 is not working on Atom ver. 1.23.3 on Win Server 2016 Standard

### ISSUE THREAD

**Issue by titanve** [prettier/prettier-atom#367]
Hello everyone,

Prettier was working nice and after the update to ver. 0.49.1 it stopped working, I have the atom-ide-ui ver. 0.8.0 installed as well.

What can I do in order to fix this problem? 

Thanks! 😄

**Comment by titanve** [comment]
I've got this message, I guess prettier won't work if I disable linter pkg
![image](https://user-images.githubusercontent.com/4803351/35761770-6e6efedc-085a-11e8-9841-85d532c0b35d.png)

**Comment by robwise** [comment]
Prettier will work with `atom-ide-diagnostics` just fine (I do this myself). Just turn off `linter` because you don't need it if you're using `atom-ide-diagnostics`.
