### ISSUE TITLE
Editor not responding

### ISSUE THREAD

**Issue by steida** [prettier/prettier-atom#373]
I don't know why, I tried clean Atom install, still, an attempt to format on save ends with 
![screen shot 2018-02-06 at 22 49 04](https://user-images.githubusercontent.com/66249/35885996-f1bcf860-0b8f-11e8-942e-3fbd311f8627.png)

**Comment by magicdawn** [comment]
Hi @steida How did you fix this?
I have met this too many times 😠

**Comment by magicdawn** [comment]
I don't have nuclide installed, don't know which package have collision with prettier-atom
my packages: https://gist.github.com/magicdawn/c4d99c4d707e75590232#file-packages-json

**Comment by steida** [comment]
I switched to VSCode, Atom is dead.

**Comment by magicdawn** [comment]
Sad Story 💔

**Comment by robwise** [comment]
lol

**Comment by magicdawn** [comment]
Hi @robwise 
prettier-atom is not responding when `format on save` is on and save a file with 600 lines
pretty sure it's prettier-atom causing this because when I turn off `format on save`, the file saves successfully.

How can I do?

**Comment by robwise** [comment]
@magicdawn This is probably a different issue than the OP so I would make your own issue where I can help troubleshoot. I would start by disabling other packages in an effort to try and narrow down if there is some sort of conflict where something is not playing nice with prettier-atom.
