### ISSUE TITLE
feat: option to auto-disable format on save for `package.json`

### ISSUE THREAD

**Issue by SavePointSam** [prettier/prettier-atom#382]
I find myself very regularly having to toggle 'format on save' when modifying my `package.json`. Would be nice to have a new option to disable 'format on save' for `package.json` automatically.

I know it is a bit of an edge case, and there is the option to toggle format on save from the command palette, or from the status bar. However, having to never think about it would be killer.

**Comment by SavePointSam** [comment]
@olsonpm, seems like a pretty quick thing you might be able to pull off for me since you've been crushing things lately. :D

**Comment by robwise** [comment]
@SavePointSam I think for this we can just use the existing exclude globs feature?

**Comment by robwise** [comment]
Now that we are on 0.55.0, this can be done with the `.prettierignore` file
