### ISSUE TITLE
prettier-atom failed: unknown type: "TSJSDocAllType"

### ISSUE THREAD

**Issue by saadq** [prettier/prettier-atom#383]
## The problem

The package seems to complain with an error that says: 

```
prettier-atom failed: unknown type: "TSJSDocAllType"
``` 

This happens when you try to run `Prettier: Format` on a file that uses [the flow existential type `*`](https://flow.org/en/docs/types/utilities/#toc-existential-type) with generics. The code works fine in [Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAQDMAbCAdx31RxwEsBbABwgCcZcAlOAQzBgAaXMFwBhCC2gJOAX1zE2k3AHI2fASrpQwpXgGd9uABJxS5XHAAe8KABMjEqVBkAedAD4R1XOvtw2AAoASm88XAj1GABXNjxAnwiI1zt6ADcPU3MIV1RUjMTcYJ9ZHFKoHGtWDlw7OGJeaNJOLPIcEEEQCGYYemh9ZFBeNiUKAAVhhAGUXjSIejsOkAMYZAbSfThOgCM2fgBrOBgAZWZ+eigAc2QYNmitkDsIMDXeDYeLzY4xvcvGXle706ACt9FYAEJ7MCHE68RhwAAyFzggM2nQg0RgzExACZUQ8zmwvsgQNteNsAJ7kKBLZhsC4wADqCxgAAtkAAOAAMnTpEE2jL2zBJdLgXzSKM66gAjtF6Oofrw-gCkOs0SBNox6Dc7g99BdLqQ4ABFaIQeD4zowcnMuxs5A4q17eikA1Of4kqDSJbRTYAFXJ0zVcFksiAA).

## Steps to reproduce

1. Create a file called `Hello.js`
2. Put the following code inside the file:

```js
/**
 * @flow
 */

import React, { Component } from 'react'

class Hello extends Component<*> {
  render() {
    return (
      <div>Hello</div>
    )
  }
}

export default Hello
```

3. Run `Prettier: Format` This will throw the error.

![](https://i.imgur.com/zarmZnF.png)

## Prettier Debug
[GitHub Gist](https://gist.github.com/anonymous/758f6b74d58d8a8d5efe8a0b053e6a1b)

<details>
Atom version: 1.24.0
prettier-atom version: 0.51.0
prettier version: 1.10.2
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "prettierOptions": {
    "bracketSpacing": false,
    "parser": "flow",
    "semi": false,
    "singleQuote": false,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "arrowParens": "avoid"
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vueScopes": [
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

## Thanks!

You all have done an awesome job with this package, thanks so much!

**Comment by robwise** [comment]
@saadq I'm able to format this with prettier-atom just fine and I use flow (and existential types) a lot.
![](https://cl.ly/3R1N330V3B3q/Screen%20Recording%202018-02-19%20at%2008.27%20PM.gif)

Do you think this might be repo-specific somehow? What version of prettier do you have installed locally? Or are you using the version that comes bundled with prettier-atom?

**Comment by saadq** [comment]
Oh, weird. I have version `^1.10.2` listed in my dev dependencies. I'm going to see if I can create a minimal repo which reproduces the problem.

**Comment by saadq** [comment]
Ahh, so sorry guys. I had `"parser": "typescript"` in my `.prettierrc` since I was trying it out for a bit, and forgot to switch it back to Flow. Everything is working as it should, my apologies! Thanks for the quick reply :)
