### ISSUE TITLE
Prettier causes Atom to freeze/hang

### ISSUE THREAD

**Issue by denchen** [prettier/prettier-atom#385]
Within the past week, Prettier has caused Atom to hang while saving some of my Javascript (React) files AND while using the shortcut (`CTRL-ALT-F`). I'll eventually get a dialog box with an option to keep waiting or force-close. I've verified that if I disabled Prettier, I have no such freezes. Also, this does not happen with all my files, just a handful. I'm not sure what's different in those JS files that would cause the hang.

Software:
* macOS High Sierra 10.13.3
* `atom@1.24.0`
* `prettier-atom@0.51.0`

Debug output:
```
Atom version: 1.24.0
prettier-atom version: 0.51.0
prettier version: 1.10.2
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vueScopes": [
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by olsonpm** [comment]
is it consistent for those files?  i.e. can you reproduce and maybe share a problematic file?

**Comment by denchen** [comment]
It is consistent for one of my files. Let me try to pare the file down while still being able to make Atom freeze and then post it here.

**Comment by olsonpm** [comment]
congrats on getting it working :+1: 

I'm willing to dig deeper if you want to push both the problematic and working files to a sample repo - but I'm also just as happy leaving things as-is in a working state ha.  Not all problems are worth looking into as I'm sure you've been around computers enough to understand.

**Comment by denchen** [comment]
I'm gonna hold off on a repo for now, unless it becomes problematic / happens multiple times. Right now it seems to have been isolated to that one file (though I'm not 100% sure). Thanks for being willing to dig deeper though!

**Comment by olsonpm** [comment]
no worries.  Thanks for the prompt feedback.  It's nice getting things over with sooner than later :)

**Comment by SavePointSam** [comment]
@denchen it may be worthwhile to look into verifying your line-endings. they tend to be tricky and secretly cause problems.
