### ISSUE TITLE
prettier-atom failed: Couldn't resolve parser "postcss"

### ISSUE THREAD

**Issue by chrishutchinson** [prettier/prettier-atom#386]
Hey, while attempting to format (on save or manually) `.scss` and `.css` files I'm getting the error:
>`prettier-atom failed: Couldn't resolve parser "postcss"`

Debug output below:

```
Atom version: 1.24.0
prettier-atom version: 0.51.0
prettier version: 1.10.2
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": false,
    "showInStatusBar": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vueScopes": [
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by olsonpm** [comment]
this is an [issue in prettier](https://github.com/prettier/prettier/issues/4071) caused by a recent update to theirlibrary.

workaround: `npm install prettier@1.10`

**Comment by olsonpm** [comment]
[they moved quick and fixed it already in 1.11.1](https://github.com/prettier/prettier/issues/4071#issuecomment-369411373).

**Comment by chrishutchinson** [comment]
Nice one, thanks!

**Comment by cawel** [comment]
I am using Atom v1.25 with `prettier-atom` v0.52.0 ( [which uses `prettier` v1.11.1](https://github.com/prettier/prettier-atom/blob/v0.52.0/package.json) ) and I am still having the issue :(

**Comment by olsonpm** [comment]
do you have a prettier inside your node_modules, and if so what version is it?

**Comment by cawel** [comment]
I don't. To make sure, I deleted my `node_modules/` dir, then ran `npm install`, and thus I can confirm I have no `prettier` in there:
```bash
$ ls node_modules/ | grep prett
pretty-bytes
pretty-error
pretty-format
```

**Comment by olsonpm** [comment]
interesting.  If you create a sample github issue that reproduces the error I'll definitely have a look.

Sorry you ran into this problem

**Comment by olsonpm** [comment]
aye, I forgot to mention I need you to paste the output of the 'prettier: debug' command in the problematic file.  That will have your prettier plugin settings which I need in case the repo doesn't come with a local prettier config.

**Comment by iamkeir** [comment]
I am experiencing this issue too. I have `prettier-atom` version `0.60.1` installed in Atom. It also prompted me to install `linter`, which is at version `2.3.1`.

We also have `prettier` in our `package.json`:
```
"prettier": "2.0.5",
"prettier-package-json": "2.1.3",
"prettier-stylelint": "0.4.2",
"eslint-config-prettier": "6.11.0",
"eslint-plugin-prettier": "3.1.4",
```
I am a bit out of my depth here so I am not sure how to resolve - any guidance greatly appreciated.
