### ISSUE TITLE
prettier-atom failed: Couldn't resolve parser "vue"

### ISSUE THREAD

**Issue by chenmei1** [prettier/prettier-atom#387]
prettier-atom failed: Couldn't resolve parser "vue"

**Comment by olsonpm** [comment]
Mind giving some more details?  Ideally you'd provide enough for me to reproduce your issue.  I've been very recently working with vue and haven't run into any issues so it will take some digging to figure out what's going on.

- To start, please provide the output of the `Prettier: Debug` command
- Post the contents of your local `package.json` if any
- If you could, creating a sample github repo that produces the problem for you would be awesome

Thanks

**Comment by chenmei1** [comment]
while attempting to format .vue  files I'm getting the error:
> prettier-atom failed: Couldn't resolve parser "vue"

**Comment by olsonpm** [comment]
I understand that, but on my machine it's been formatting `.vue` files just fine - thus I need more information to debug your problem.

**Comment by chenmei1** [comment]
I re-install,It run normally,thanks

**Comment by olsonpm** [comment]
Glad you got it working!
