### ISSUE TITLE
Prettier-atom failed: Couldn't resolve parser 'postcss'

### ISSUE THREAD

**Issue by abhinav-m** [prettier/prettier-atom#388]
Whenever i save a `.scss` or a `.css` file, i get the error mentioned in the title, and below.
`Prettier-atom failed: Couldn't resolve parser 'postcss'`

Posting prettier:debug output here:

```
Atom version: 1.24.0
prettier-atom version: 0.51.0
prettier version: 1.10.2
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vueScopes": [
      "text.html.vue"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "useEditorConfig": false,
  "useEslint": false,
  "useStylelint": false,
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by olsonpm** [comment]
Mind checking if you have the same problem [resolved here](https://github.com/prettier/prettier-atom/issues/386)?

**Comment by abhinav-m** [comment]
@olsonpm Im using atom's package for prettier. I have not installed it locally on my project, Any ideas how i can address this?

**Comment by olsonpm** [comment]
Odd.  If you create a sample repo which produces your issue then I'll definitely take a look.  Otherwise it will take me some time and I'd have to wait til after the weekend.

**Comment by abhinav-m** [comment]
https://github.com/abhinav-m/react-starter-boilerplate @olsonpm this is a sample repo i encounter the issue on.

**Comment by olsonpm** [comment]
Wow awesome - thanks much.  I'll let you know If I need anything else but this is usually sufficient

**Comment by olsonpm** [comment]
Hey - I think you found a bug in `prettier-atom` as it's finding the prettier inside node_modules which has a version of `1.11.0`.  It's also listed in package-lock.json.

I assume this doesn't come up often because usually packages declare `prettier` as a devDependency.  In your repo however `webpack-cli` declares prettier as a regular dependency.
<br>

@robwise @SavePointSam - can you confirm the following
- `prettier-atom` should only be grabbing prettier found in node_modules if it's declared as a dev/dependency in package.json.

**Comment by robwise** [comment]
@olsonpm No, I think it uses the local prettier if it's found at all in node_modules, the thing where it has to be declared in the package.json is for the disable/enable formatOnSave thing.

Relevant code is all of this file: https://github.com/prettier/prettier-atom/blob/master/src/helpers/getPrettierInstance.js

**Comment by olsonpm** [comment]
mind explaining why that would be the case though?

**Comment by robwise** [comment]
Why we'd use your local prettier versus an arbitrary one that comes bundled with prettier-atom? Because it will cause massive diff noise and inconsistencies to be using different versions between different editors and between any script that runs prettier directly via the CLI.

**Comment by robwise** [comment]
We could consider adding an option of whether you want to use the bundled version always or prefer using the local version if we find one, but using the local version is pretty par for the course for things like linter-eslint and others. My team's projects check that all files pass prettier's `list-different` check. If some devs were using different versions of prettier than what we had locally (which is used in CI for that list-different check), we'd be in a world of hurt.

**Comment by olsonpm** [comment]
> If some devs were using different versions of prettier than what we had locally

in any situation where a team depended on a local version of prettier, why would you be relying on a version depended on by another package?  Why would you not have prettier both installed and configured explicitly?

Or in this case, what if webpack-cli decides to use beautifyjs at some point? resulting in prettier being removed.

Regardless, i'll let it be as-is and just remember this is how it works for next time.

**Comment by robwise** [comment]
> why would you be relying on a version depended on by another package? Why would you not have prettier both installed and configured explicitly?

I do (personally). Maybe you could explain what you're proposing we change? Adding a check to make sure that prettier is defined in the package.json before using the local version? That might be something we want to do.

**Comment by olsonpm** [comment]
i propose that just as a local configuration should only be used when explicitly defined, a local prettier version should only be used when explicitly defined.

**Comment by robwise** [comment]
@olsonpm let's continue this in #389

**Comment by olsonpm** [comment]
@abhinav-m to be clear, for now you'll need to either install prettier as a devDependency  (recommended) or create a pull request to webpack-cli updating their version of prettier.
