### ISSUE TITLE
Only use local prettier version if prettier is in package.json

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-atom#389]
Currently, [if we find prettier in node_modules, we use it instead of the version we bundle with prettier-atom](https://github.com/prettier/prettier-atom/blob/master/src/helpers/getPrettierInstance.js). However, it may be the case that this was only present because it is a dependency of something else and not because the developer is using it to format their project.

Therefore, we may want to consider only using the local version if prettier is actually defined in the package.json explicitly. Otherwise, we fall back to using the version that came bundled with prettier-atom.

*Note:* Don't confuse this with the option we already have which disables format-on-save unless prettier is found in the package json. The scenario we're talking about here is where the person is okay with formatting, but would prefer using the bundled version of prettier that comes with prettier-atom instead of some random version of a dependency.

**Comment by chrisdrackett** [comment]
we currently have prettier in a shared repo. With this setup prettier isn't directly in any our our project's `package.json` files but we still want to use the version in  `node_modules`. I totally get the logic behind this idea, I just think it would break a current potential use case.

**Comment by robwise** [comment]
Yes, that is a good point, this might be hurting more than helping.
