### ISSUE TITLE
prettier debug not outputting values set in prettierrc file

### ISSUE THREAD

**Issue by lifeiscontent** [prettier/prettier-atom#390]
hello,

I'm having issues with prettier-atom, I've setup my config like so:

``` js
module.exports = {
  semi: false,
};
```

but for some reason when I look at the debug output of pretter-atom I don't see any of these values reflected.

**Comment by SavePointSam** [comment]
The prettier-atom debug output is designed to provide internal insight to debugging specific issues with the package, not prettier or it's configuration.

Also, please note that when creating a prettier configuration that uses module exports, you need to use the filename `prettier.config.js`. You can review the prettier configuration documentation [here](https://prettier.io/docs/en/configuration.html)
