### ISSUE TITLE
Editor crashing on save

### ISSUE THREAD

**Issue by majdi** [prettier/prettier-atom#392]
Hi, 
I love this package but I have an annoying issue with "big files", ie more than 200 lines
Everytime I update something and I save the file --> atom is crashing.

Sometimes it's only freezing but I need to wait more than 30seconds [ too much ].
Most of the time Atom is when I'm commented something.

Thanks,

**Comment by SavePointSam** [comment]
Hi there!

Could you provide an example of a file that causes Atom to crash as well as your current package list?

```
$ apm list --installed --bare
```

**Comment by majdi** [comment]
Sure,

This is my package list:

**atom-alignment@0.13.0
atom-beautify@0.32.2
busy-signal@1.4.3
emmet@2.4.3
file-icons@2.1.17
fonts@3.0.3
git-plus@7.10.0
intentions@1.1.5
language-babel@2.84.0
language-cmake@1.1.0
language-cpp14@0.6.2
language-docker@1.1.8
language-graphql@0.9.0
language-javascript-jsx@0.3.7
language-lisp@0.2.0
language-styled-jsx@1.0.4
language-swift@0.5.0
linter@2.2.0
linter-ui-default@1.7.1
monokai@0.24.0
monokai-seti@0.9.0
pigments@0.40.2
platformio-ide-terminal@2.8.0
prettier-atom@0.51.0
react@0.18.0
react-es6-snippets@0.3.0
svg-preview@0.12.1
toggle-quotes@1.1.0**

I can't provide a full example of my code but you can see the structure [here](https://gist.github.com/majdi/8bec9e32fe105c2533f92b3feba8c7c5)

**Comment by olsonpm** [comment]
are you able to reproduce with "a big file" and post the contents of that?  We're mainly looking for ways to reproduce and understand your issue.  I've used the prettier plugin on many files larger than 200 lines, and I doubt it's a hardware issue as 200 is just not that much.

**Comment by majdi** [comment]
Hi @olsonpm,
I reproduce the issue, it's not about the size of the file, I think it's something else;
You can find [here](https://gist.github.com/majdi/9ee2f74ac31161d605efac236b6a7a63) another gist with less than 120 lines.

The crash happen when I comment any **import** line on the top of the file and I save the file.

**Comment by olsonpm** [comment]
haha what a weird bug.  I'm able to reproduce.  I'll let you know what I find and thanks for taking the time to get reproduceable steps!

**Comment by majdi** [comment]
You're welcome :-D
I'll try to find how to fix-it too.

**Comment by olsonpm** [comment]
wow this was frustrating.  I don't know what's going on but updating the prettier version fixes it.

@robwise @SavePointSam, unless either of you want to take a deeper look, does it sound okay to you guys to update the bundled prettier version and advise users to update their prettier version locally if they come across this bug?
<br>

Some debugging notes for reference:

- if I run the text through prettier cli @ 1.10.2 (version bundled with plugin) the delay doesn't appear.  I didn't try other editors
- the delay seems to correlate with the complexity of the jsx.  Removing chunks of the jsx reduces the time down to a reasonable amount.  Modifying any code at the top level i.e. not code within the class declaration produces the delay
- the delay happens [here in prettier](https://github.com/prettier/prettier/blob/1.10.2/src/main/ast-to-doc.js#L51)
- that file was only slightly modified between `1.10.2` -> `1.11.1`.  I didn't dig into the changes to understand it further.

```diff
// src/main/ast-to-doc.js

 const comments = require("./comments");
 const FastPath = require("../common/fast-path");
 const multiparser = require("./multiparser");
-const util = require("../common/util");
 
 const doc = require("../doc");
 const docBuilders = doc.builders;
@@ -75,7 +74,10 @@ function genericPrint(path, options, printPath, args) {
 
   // Escape hatch
   if (printer.hasPrettierIgnore && printer.hasPrettierIgnore(path)) {
-    return options.originalText.slice(util.locStart(node), util.locEnd(node));
+    return options.originalText.slice(
+      options.locStart(node),
+      options.locEnd(node)
+    );
   }
 
   if (node) {
```

- the [release notes](https://prettier.io/blog/2018/02/26/1.11.0.html) also didn't give any clues

**Comment by olsonpm** [comment]
@majdi - a workaround for now would be to install the latest prettier local to your project.  Then the plugin will take that version instead of:

1. one found in your node_modules if prettier was installed as a direct or indirect dependency
2. the one bundled in this plugin (1.10.2)

**Comment by SavePointSam** [comment]
Have you tried passing in a different AST parser when calling the CLI from our end? We may be providing an incorrect parser for the file type. Can you look into that as a potential solution, @olsonpm?

I personally don't mind updating our bundled Prettier, but we should probably explore other potential solutions to figure out if we really are the problem first, even more so because there is no mention in the release notes about this problem. Did you look in the Prettier issues for something related?

**Comment by olsonpm** [comment]
i just pasted his code into a brand new js file so unless i've always been passing an incorrect parser i doubt that's the issue.  I also didn't check this on a clean install, so it's possible package conflicts are at play.  However given the delay happens at that one recursive call and prettier fails to throw an error, I think there's something else at play.

Honestly I've sunk as much time into this issue as I care to as well.  This was making my atom crash at times and so the debugging experience wasn't great. I'm not going to debug further.

**Comment by robwise** [comment]
I'll bump now and we can see if it solves the issue, it never hurts to bump it anyway.

**Comment by olsonpm** [comment]
it solved the issue for me locally inside atom --dev with prettier atom dev linked.  You're right OP should verify the fix though :)

thanks robwise

**Comment by majdi** [comment]
I just install locally prettier@^1.11.1 and it works well. Thanks @olsonpm! 
Hope you'll find the origin of this weird bug 🤓

**Comment by robwise** [comment]
Okay bumped to prettier 1.11.1 in prettier-atom 0.52.0

**Comment by olsonpm** [comment]
I've given up actually haha.  I've got some problems that are more interesting atm and bumping a version is a good'nuff stopping point for me.

@majdi If you have a moment please try the new version of prettier-atom to make sure it solves your problem.  If it does then go ahead and close the issue.

**Comment by majdi** [comment]
Perfect @olsonpm it works in both cases. Thanks guy 👍

**Comment by joarwilk** [comment]
Thanks for fixing this so fast guys, was seeing the same issue.

**Comment by joarwilk** [comment]
Hey, this still happens for me on the latest version of the plugin

**Comment by majdi** [comment]
Did you have the same issue than me? I didn't have any problem still the update.

**Comment by olsonpm** [comment]
@joarwilk, see what version of prettier is installed in your node_modules.  Even if you don't install prettier as a dependency, if one is installed indirectly (via another dependency) then the plugin picks that one up.

**Comment by joarwilk** [comment]
Went away after a fresh computer restart. Probably some spooky cache still giving me the previous version after updating. Works just fine now!

**Comment by rx2347** [comment]
FYI: Still crashes on large Copy&Paste and save.

Atom: 1.44.0 x64 (OSX)
Prettier-Atom: 0.58.2
