### ISSUE TITLE
Format on save broken

### ISSUE THREAD

**Issue by mdotasia** [prettier/prettier-atom#396]
It looks like format on save is broken for js and jsx files. I have it enabled together with display in status bar. When I am in editor tab with JSON file I see a green Prettier with a checkmark in the status bar. Format on save works for JSON.

When I open js or jsx the green Prettier checkmark disappears from the status bar and format on save does not work. Toggling it on via Ctrl Shift P has no effect. Manual format works. 

```
Atom version: 1.25.0
prettier-atom version: 0.52.0
prettier version: 1.11.1
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "useEditorConfig": false,
  "useEslint": false,
  "useStylelint": false,
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "scopes": {
    "javascript": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescript": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "css": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "json": [
      "source.json"
    ],
    "graphQl": [
      "source.graphql"
    ],
    "markdown": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vue": [
      "text.html.vue"
    ]
  }
}
```

**Comment by olsonpm** [comment]
please post a github repo with a file that reproduces your issue.  The only thing i can see from the output is the possibility that eslintignore is causing the file to not be formatted, though if i can reproduce your issue locally then figuring out exactly why will be very easy.

Sorry you ran into this problem!

**Comment by mdotasia** [comment]
The error occurred on my Macbook. On a Linux machine same project with same plugins did not break format on save in prettier-atom. Therefore, I reinstalled Atom and all plugins from scratch on my Macbook and everything seems fine now. No idea what was wrong.

**Comment by ionush** [comment]
The same solution worked for me
