### ISSUE TITLE
Support proseWrap option

### ISSUE THREAD

**Issue by billyjanitsch** [prettier/prettier-atom#401]
Currently, there is no way to configure the [Prose Wrap option](https://prettier.io/docs/en/options.html#prose-wrap) alongside all of the other Prettier options in prettier-atom's config.

Is this an intentional omission?

**Comment by olsonpm** [comment]
My assumption is that it's a newer configuration that just never got ported into prettier-atom.  A lot of the code in this repo I'm learning is fairly old.

We've discussed moving away from all the hard-coded options in the plugin itself and moving toward a "global prettier config" of sorts but I can't promise this would land any time soon.  If you would really prefer this option in the prettier-atom configurations itself as opposed to having a prettier configuration local to whatever files you're formatting, then I'm sure a PR would be welcome.

**Comment by billyjanitsch** [comment]
Thanks for looking into it! I use prettier-atom to format Markdown notes outside of project/package contexts (think personal todo lists), for which it's nice to tweak package-level settings. A global config (e.g. user dotfile) would also work.

I'll try a PR when I have time. Thanks!

**Comment by robwise** [comment]
> A lot of the code in this repo I'm learning is fairly old

?

**Comment by olsonpm** [comment]
the filepath option has been available since last june

**Comment by robwise** [comment]
And as I already explained, we _chose_ not to implement it back then, it's not because the repo is outdated.

**Comment by olsonpm** [comment]
whatever mang

**Comment by olsonpm** [comment]
i can't find how to remove myself from the list of collaborators.  please remove me.
