### ISSUE TITLE
Javascript Template Literals

### ISSUE THREAD

**Issue by mario-iliev** [prettier/prettier-atom#403]
Project: React + Styled Components
When I use expressions in template literals for styled components, prettier-atom takes the line after ${} expression and place it on the same as the expression:
```
const ItemWrap = styled.div`
  display: block;

  ${optimizations.enableHardwareAcceleration} &.active {
    display: table;
  }
  &.transition {
    position: absolute;
  }
```

Where it should be:
```
const ItemWrap = styled.div`
  display: block;

  ${optimizations.enableHardwareAcceleration}
  
  &.active {
    display: table;
  }
  &.transition {
    position: absolute;
  }
```

I've tried to solve it with various configurations but no luck.

**Comment by robwise** [comment]
@mario-iliev This sounds like a prettier problem and not a prettier-atom problem. Can you verify whether or not this problem occurs when using Prettier directly?

**Comment by SavePointSam** [comment]
Hey there! I have the same oddity occurring. I believe this is on the prettier side as we don't do anything fancy other than facilitate the connection to prettier for you. What you can do is add a `;` at the end of your comment to prevent that wrapping.

```diff
const ItemWrap = styled.div`
  display: block;

- ${optimizations.enableHardwareAcceleration}
+ ${optimizations.enableHardwareAcceleration};

  &.active {
    display: table;
  }
  &.transition {
    position: absolute;
  }
`;
```

**Comment by mario-iliev** [comment]
@robwise I don't understand the context of Prettier against prettier-atom. I have only "prettier-atom" package and when I disable it, the problem is not occurring.

@SavePointSam I saw that the problem could be solved by adding the semicolon but I think that prettier-atom should either automatically add the semicolon or not merging the two lines (prefer first option:)).

**Comment by SavePointSam** [comment]
@mario-iliev prettier-atom is just an extension for Atom that will manage the connection to the prettier system. It doesn't actually do any formatting, prettier does all the work. prettier-atom simply listens to events in the Atom environment and forwards requests to and from the prettier API.

As such, any formatting issues you are seeing are directly related to prettier and reports should be posted on [the main repository](https://github.com/prettier/prettier).

You can think of prettier-atom like a power outlet adapter. We don't do anything to the power, just allow easier access to it.

**Comment by SavePointSam** [comment]
It also appears that there is an open issue for this functionality over at prettier already.

https://github.com/prettier/prettier/issues/2291

You're welcome to look over there for more information. Closing this issue as it is not a prettier-atom specific problem. Thanks for the report!
