### ISSUE TITLE
"Cannot read property 'sync' of undefined" on projects without Prettier config

### ISSUE THREAD

**Issue by cbovis** [prettier/prettier-atom#406]
I'm receiving the following error every time I save a file in projects which **don't** have a Prettier config file. I have to disable "Format On Save" to avoid error notifications popping up every time I save a file.

![error](https://user-images.githubusercontent.com/34132/38478959-8cfb7aaa-3bff-11e8-9a66-2c7fd457f17c.png)

I don't have this issue when editing files in projects which contain a Prettier config file.

**Comment by robwise** [comment]
@cbovis it could be that your version of prettier-atom is so old that the bundled version doesn't have `resolveConfig.sync` defined yet. 

Can you try updating prettier-atom, then restarting Atom, and see if that fixes it?

**Comment by callmeaponte** [comment]
I'm getting the exact same issue - the error keeps popping up for me on projects that don't have a Prettier config file. In my case I opted to just disable prettier-atom altogether to make the message go away.

I'm running the latest version of Prettier (0.53.0). Let me know if there's anything I can do to help you troubleshoot this.

**Comment by robwise** [comment]
@callmeaponte Are you sure it's that exact same error?

**Comment by callmeaponte** [comment]
I'm pretty sure. I'll re-enable the package now and take a screenshot the next time it pops up.

**Comment by robwise** [comment]
@callmeaponte This is a very common error for people who are using an old version of prettier. Can you verify what version of Prettier is in your `node_modules` folder in the project where this is occurring by checking the package.json inside of `node_modules/prettier`?

**Comment by callmeaponte** [comment]
Prettier doesn't exist in the `node_modules` folder (it's not a dependency), nor is it installed globally.

In case you want to try and reproduce it - this is occurring on a brand new [Angular](https://angular.io/guide/quickstart) app spun up using the `ng new` CLI command. I'm using prettier-atom version 0.54.0.

**Comment by Blink18260000** [comment]
For what it's worth, opening the console, clicking the line indicator at the top of the error, and making the following code change got things working for me.

```
const getPrettierConfigOptions = _.cond([[_.flow(getCurrentFilePath, isDefined), editor => {
  // $FlowFixMe
  const hasResolveConfigSync = isDefined(getPrettierInstance(editor).resolveConfig.sync);
  if (!hasResolveConfigSync) return null;
```

became 

```
const getPrettierConfigOptions = _.cond([[_.flow(getCurrentFilePath, isDefined), editor => {
  // $FlowFixMe
  const hasResolveConfigSync = isDefined(getPrettierInstance(editor).resolveConfig && getPrettierInstance(editor).resolveConfig.sync);
  if (!hasResolveConfigSync) return null;
```

I'm not sure why that variable wouldn't exist (I didn't really dig into the code), but I'm on 0.54.0. Additionally, adding a prettier config and restarting atom didn't seem to get it working. Hopefully this is a functional workaround for other people until the root cause is found.

**Comment by callmeaponte** [comment]
Would it be okay to open up a pull request with the change suggested by @Blink18260000 as a temporary workaround for now?

**Comment by robwise** [comment]
@callmeaponte I'm about to release #404 which changes a lot of this code I think. I will make sure this change is picked up there as well.

**Comment by callmeaponte** [comment]
Awesome. Thank you!
