### ISSUE TITLE
Creating random {" "} whenever spaces are seen

### ISSUE THREAD

**Issue by gazcn007** [prettier/prettier-atom#407]
Great work on prettifying JSX code  👍 , just having this issue:

For example if my code is uglified like the following 
![image](https://user-images.githubusercontent.com/12766318/38595464-f3617036-3d19-11e8-9c24-04a40194b5ac.png)

Whenever I do pretty with prettier-atom, it creates {" "}:
![image](https://user-images.githubusercontent.com/12766318/38595485-157f3ae0-3d1a-11e8-88bf-e3b8b583ad17.png)

This works fine with normal JSX components, but it has '_idCounter' of undefined errors (`Uncaught TypeError: Cannot read property '_idCounter' of undefined`) when using libraries such as [react-konva](https://github.com/lavrton/react-konva).

**Comment by robwise** [comment]
Hey there, what you're describing sounds like it is actually an issue with [prettier](https://github.com/prettier/prettier) itself, as opposed to this repo (prettier-atom) which is just the Atom plugin that calls prettier under-the-hood. Can you make an issue for this over on that repo?

I will close this for now, but please feel free to reopen if this is actually a prettier-atom problem.

**Comment by gazcn007** [comment]
Cool, Thanks Rob
