### ISSUE TITLE
Glob pattern matching not working properly

### ISSUE THREAD

**Issue by CorwinCZ** [prettier/prettier-atom#408]
I'm using `prettier` on my project for months, works perfetly. Recently I have added `prettier-atom` to my editor, but I was strugling with settings. More specifically with `Include (list of globs)` part.

Here is my CLI `prettier` command (taken from `package.json`):
`"prettier": "prettier --single-quote --trailing-comma all --write '{pages,components,libs}/**/*.js'",`

This command sucessfuly formats all .js files inside `pages`, `components` and `libs` as expected. When I copy-pasted the glob into `prettier-atom` settings, only files in `components` folder were formated on file-save. I could format the rest manualy wia command, but that is not ideal.

After testing and searching about globs, i ended up with this settings in `Include` section:
`{dummy,pages,components,libs,dummy}/**/*.js`
This works as expected.

This really confuses me - from what was able to read about globs, the `{pages,components,libs}/**/*.js` should be expanded to `pages/**/*.js`, `components/**/*.js`, `libs/**/*.js` - which is happening if I use this glob in CLI. But when I check the settings file, it seems that `prettier-atom` glob is first expanded by commas and the `{}` are ignored.

Am I missing something about globs, or are the `prettier-atom` glob's used diferently then `prettier` globs?

## Addition informations

Other settings of `prettier-atom`:

    "prettier-atom":
      formatOnSaveOptions:
      enabled: true
      isDisabledIfNotInPackageJson: true
      showInStatusBar: true
      whitelistedGlobs: [
        "{dummy"
        "pages"
        "components"
        "libs"
        "dummy}/**/*.js"
      ]
    prettierOptions:
      singleQuote: true
      trailingComma: "all"
    useEditorConfig: false

Atom version: 1.24.1
Prettier-atom version: 0.53.0
Prettier version: 1.9.2
OS: Ubuntu 16.04

Thanks for your time and great plugin!

**Comment by robwise** [comment]
@CorwinCZ Sorry for the delayed response, somehow this slipped past my notifications. 

I think what's going on here is that there are two established ways that glob syntax is implemented (minimatch and .gitignore style). 

We are using [this package](https://www.npmjs.com/package/ignore) for our current implementation (this is the gitignore style). I don't think the syntax you ave there is valid for the gitignore style.

We used to do it the other way (minimatch), but we got complaints about that implementation and decided to do it this way.

**Comment by CorwinCZ** [comment]
Thanks @robwise for response! It helped to solve my issue. In the end I have decided to go with simple match for few file types, without considering folders - `*.js, *.css, *.scss`.

Can you please consider adding this information to README file and settings tooltips? I didn't know there are more then one implementation of glob pattern search, having link to either package or [.gitignore documentation](https://git-scm.com/docs/gitignore) would really help :)

**Comment by robwise** [comment]
Yes, good idea, sorry again for the confusion and delayed response.
