### ISSUE TITLE
Consider setting --config-precedence=file-override

### ISSUE THREAD

**Issue by anhuong** [prettier/prettier-atom#410]
By default, `--config-precedence` is set to `cli-override` which means the Atom settings are overriding the `.prettierrc`. The user would expect the `.prettierrc` to take precedence. 

If we set it to `file-override`, then the `.prettierrc` is honored and would behave as the user expects.

**Comment by robwise** [comment]
This should be resolved in https://github.com/prettier/prettier-atom/pull/404
