### ISSUE TITLE
when prettier-atom is enabled I cannot save any file

### ISSUE THREAD

**Issue by llimllib** [prettier/prettier-atom#417]
Steps to reproduce:

1. Enable prettier
2. Try to save a file (file type does not matter)
3. Note that file does not save. `Uncaught (in promise) log.setLevel() called with invalid level: FATAL` appears in the dev console
4. Disable `prettier-atom`
5. Note that the problem has resolved

Screencast: https://youtu.be/QZ74ZHU38gg

What I expect to happen: the file saves

Prettier:debug output:
```
Atom version: 1.26.1
prettier-atom version: 0.53.0
prettier: bundled
prettier version: 1.11.1
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "scopes": {
    "javascript": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescript": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "css": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "json": [
      "source.json"
    ],
    "graphQl": [
      "source.graphql"
    ],
    "markdown": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vue": [
      "text.html.vue"
    ]
  }
}
```

**Comment by SavePointSam** [comment]
Hi! Thanks for bringing this to our attention. I know this may sound silly, but we occasionally experience strange installation issues. Have you tried completely removing the plugin and re-installing?

If you’ve tried that and are still experiencing this issue, could you open the stack trace to the error you posted? It would help quite a lot to see that.

**Comment by llimllib** [comment]
Sorry, I should have mentioned that there is no traceback, I would have tried to look into it if there were:

<img width="556" alt="monosnap 2018-05-09 20-53-16" src="https://user-images.githubusercontent.com/7150/39846682-0da33e94-53cb-11e8-96c3-ae66b699cb53.png">

**Comment by llimllib** [comment]
Uninstalling and reinstalling does not have any effect

**Comment by llimllib** [comment]
I'm happy to help debug in any way possible, I don't know atom, was just testing out a switch from vim.

I would pair with somebody if they wanted to look into it, or run atom in dev mode, or whatever you think might be useful

**Comment by robwise** [comment]
Hmm, this is very strange, and unfortunately, I can't reproduce it locally. We don't really call `log.setLevel` anywhere in this codebase, so I'm having trouble figuring out what might be the cause. 

It's also a bit strange that you receive the dependencies installed message twice, it should only be showing up once AFAIK.

You have `atom-linter` installed, right?

**Comment by llimllib** [comment]
Yup, I have `linter` installed

**Comment by robwise** [comment]
Can you try with the latest release (0.55.0)? We've changed a lot of things under the hood.

**Comment by llimllib** [comment]
Upgraded, and cannot reproduce so closing
