### ISSUE TITLE
Cursor jumps about 100 lines up after compiling SASS

### ISSUE THREAD

**Issue by monolux** [prettier/prettier-atom#419]
If I do not have my main.sass file in .prettierignore or .eslintignore after each save and compiling SASS the cursor will jump up about 100 or more lines.

As soon as I have the .sass file in the list of files to ignore in  .prettierignore or .eslintignore the cursor stays at the same position after each compile.

**Comment by robwise** [comment]
Could you give some example code that I can use to try and reproduce?

**Comment by monolux** [comment]
I will try and make a animated gif of the error and also try to shoot you some example code.
Do you also need a list of other packages installed?
Perhaps this could also be a reason for the jumping behaviour?
Happy to provide enough stuff so you can look into it.
Issue persists, as soon as I remove the main.scss file from .prettierignore the jumps keep coming back.
This happens regardless of it I have other packages activated or not.

**Comment by SavePointSam** [comment]
> Perhaps this could also be a reason for the jumping behaviour?

Prettier has a flawed implementation of detecting cursor position. I was working on a patch awhile ago, but got busy with personal events. It could very well be on the plugin.

Though it doesn't hurt to have the plugin list for diagnosis. You can get a nicely formatted list from running the following on a command line:

```
$ apm list
```

Having a minimal reproducible code sample is the best way to help us. Can be in the form of a GitHub repo or a CodeSandbox, whichever is easier for you.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
