### ISSUE TITLE
prettier-atom failed: No parser and no file path given, couldn't infer a parser.

### ISSUE THREAD

**Issue by hundsim** [prettier/prettier-atom#420]
**Versions:**
prettier-atom: 0.53.0
prettier: 1.13
atom: 1.27.1

I upgraded prettier from 1.12 to 1.13 and now when I try to save a file I'm getting the following error:

![screenshot 2018-05-28 19 00 47](https://user-images.githubusercontent.com/1907343/40623943-fb91dd26-62a9-11e8-9b43-21321473376b.png)

Everything worked fine and as expected up until the upgrade of the prettier package.

**Comment by dnalborczyk** [comment]
@hundsim  https://github.com/prettier/prettier/issues/4567

as an interim you can (or might have to) specify the `parser` in your prettier config

e.g. `parser: babylon`

**Comment by hundsim** [comment]
Thanks, that made it!

**Comment by robwise** [comment]
I'm going to reopen as this does need to be addressed.

**Comment by robwise** [comment]
Oops actually you were right, this was a Prettier bug, I didn't read the link lol
