### ISSUE TITLE
Prettier 1.13

### ISSUE THREAD

**Issue by swrobel** [prettier/prettier-atom#422]
Prettier 1.13 has a pretty major change in handling of parens: https://prettier.io/blog/2018/05/27/1.13.0.html#insert-more-parentheses-in-math-expressions-4413-and-4407-by-duailibe

**Comment by SavePointSam** [comment]
Hey! It's unclear what you're asking of us. Can you clarify an actionable item on our part? Thanks!

**Comment by swrobel** [comment]
Bump the included version of prettier
