### ISSUE TITLE
Per document scope for format on save toggle

### ISSUE THREAD

**Issue by jmatsushita** [prettier/prettier-atom#424]
Hi there,

This is a feature request for this great module. It would be great if the Format on Save option worked on a per document basis. The UX could be that if you Cmd-Click on the Prettier status bar, it would deactivate (or activate) only for the opened document. It could display a little document icon next to the Prettier status bar item, to inform the user about the current state and scope.

Hope you like the idea!

Jun

**Comment by robwise** [comment]
@jmatsushita In the interest of keeping the plugin simpler, I would recommend using the blacklist or whitelist globs features of prettier-atom, or alternatively, once #404 is merged, just using a `.prettierignore` file.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
