### ISSUE TITLE
Error: 'prettier-atom failed: No parser could be inferred for file: ...example.html'

### ISSUE THREAD

**Issue by BenKai3** [prettier/prettier-atom#426]
Whenever writing JavaScript in a script tag, in an html file, the error goes off upon saving.

"prettier-atom failed: No parser could be inferred for file: ...index.html"

**Comment by zeusdeux** [comment]
Getting the same error when I save a script (so no extension and a shebang up top) in my editor (emacs).

**Comment by yijiaow** [comment]
Getting the same error in Atom editor when I'm trying to save .htmlhintrc file. I already ran `apm install linter-htmlhint`

**Comment by yohanisgobai** [comment]
Getting the same error, But it can be solve JUST if you place ALL including the script tag on 1 Line. @BenKai3

**Comment by Reaver86** [comment]
Same error in IntelliJ, when a codecoverage report (index.html) is generated.

**Comment by hiyangguo** [comment]
🙋‍♂️

**Comment by jqn** [comment]
Any fixes? this is a real bummer

**Comment by robwise** [comment]
This should get fixed in #404 which I'm planning to release very soon

**Comment by saikumar-mobinius** [comment]
I am also getting same error for PHP files

**Comment by drewbaker** [comment]
Got this same error with PHP today.

**Comment by mikeallbutt** [comment]
> Got this same error with PHP today.

I get this error with PHP files. Prettier is working for .js files though.
