### ISSUE TITLE
Autocompleting values sometimes does not work

### ISSUE THREAD

**Issue by MiLeung** [prettier/prettier-atom#428]
![](https://media.giphy.com/media/BWihV4MLAnxVp4RiTU/giphy.gif)

The behavior is unpredictable. For example, sometimes autocompleting (pressing enter) for the "center" in alignItems: 'center' will work, sometimes not. I do not have prettier installed.

**Comment by robwise** [comment]
Are you sure this is prettier-atom's doing? We only install a hook that runs on save, nothing should be affecting autocomplete AFAIK.

**Comment by MiLeung** [comment]
Yeah scratch that, not prettier-atom's fault!
