### ISSUE TITLE
Format on save doesn't work on JSX files

### ISSUE THREAD

**Issue by danielmcoelho** [prettier/prettier-atom#429]
Prettier is working fine for me on JS files. I can format on save or use the key shortcut. But on JSX files, it only works when manually using the key shortcut to format. No errors on the console. Any ideas?

Prettier debug:
```
Atom version: 1.27.2
prettier-atom version: 0.54.0
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "useEslint": true,
  "useStylelint": true,
  "useEditorConfig": true,
  "scopes": {
    "javascript": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescript": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "css": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "json": [
      "source.json"
    ],
    "graphQl": [
      "source.graphql"
    ],
    "markdown": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vue": [
      "text.html.vue"
    ]
  }
}
```

**Comment by robwise** [comment]
It looks as though your javascript scopes are the default list and therefore are set to run on JSX as expected.

There could be several things affecting it such as an eslintignore or prettierignore file. Is it possible that you've ignored JSX files with either of these types of files?

**Comment by danielmcoelho** [comment]
@robwise That's the problem, I don't have any `eslintignore` or `prettierignore`. No errors on `Prettier->Debug`. What else can I look for to debug this?

**Comment by robwise** [comment]
@danielmcoelho Sorry for the late reply. You can do `apm develop prettier-atom` which will initialize a local repo of prettier-atom for you. Then you can do `atom --dev` to use that version (make sure to `yarn install` the dependencies first).

Then you can insert console statements to debug. You will need to do `yarn start build` to rebuild and restart atom to pick up the changes and then open Atom's console to see your console statements. The key is checking whether prettier-atom is returning `false` to `shouldFormatOnSave`, or if it is actually trying to format but failing for some reason.

**Comment by danielmcoelho** [comment]
@robwise I'm having a hard time debugging this because I never used Typescript before. On which file should I console log `shouldFormatOnSave`?

**Comment by m4l3k** [comment]
@robwise @danielmcoelho 
getCurrentScope(editor) returns "javascript" for .jsx files

getAllScopes() => `["source.js", "source.jsx", "source.js.jsx", "source.babel", "source.js-semantic", "text.html.basic", "text.html.vue", "source.ts", "source.tsx", "source.ts.tsx", "source.css", "source.less", "source.css.less", "source.scss", "source.css.scss", "source.css.postcss", "source.json", "source.graphql", "source.md", "source.gfm", "text.md", "text.html.vue"]0: "source.js"1: "source.jsx"2: "source.js.jsx"3: "source.babel"4: "source.js-semantic"5: "text.html.basic"6: "text.html.vue"7: "source.ts"8: "source.tsx"9: "source.ts.tsx"10: "source.css"11: "source.less"12: "source.css.less"13: "source.scss"14: "source.css.scss"15: "source.css.postcss"16: "source.json"17: "source.graphql"18: "source.md"19: "source.gfm"20: "text.md"21: "text.html.vue"]`

getCurrentScope(editor)  => `"javascript"`

**Comment by m4l3k** [comment]
@robwise @danielmcoelho 
Installing `language-babel` package solved the issue and format on save works on .jsx files 🎉 
https://atom.io/packages/language-babel

**Comment by ionush** [comment]
@m4l3k I have the same issue but unable to resolve by installing language-babel. Any other ideas?

**Comment by danielmcoelho** [comment]
BTW, I didn't solve my issue either 😞

**Comment by ionush** [comment]
I sorted it with a clean install of atom on my mac. Refer to #396

**Comment by robwise** [comment]
Can you try with the latest release (0.55.0)? We've changed a lot of things under the hood.

**Comment by danielmcoelho** [comment]
@robwise Is looks like it's working 🎉 Amazing!
