### ISSUE TITLE
Only format on save if prettier is in the dependencies

### ISSUE THREAD

**Issue by mxstbr** [prettier/prettier-atom#43]
I have projects that use `prettier` and adhere to the style standard, but I also have projects that neither use `prettier` nor adhere to the style. (they enforce some other styleguide with `eslint`)

It'd be great if the "Format on save" option only took effect in projects that have `prettier` in their `package.json` or something like that!

**Comment by robwise** [comment]
I was thinking in https://github.com/jlongster/prettier-atom/issues/41 that it might be good to do a blacklist glob, that might be better because that would cover cases where people still want to use prettier for their files even though the project might not have it listed in the dependencies.

**Comment by mxstbr** [comment]
> it might be good to do a blacklist glob

That seems very manual. I create new projects almost everyday, and updating a custom glob every time based on "do I want to use prettier or not" seems pretty tedious. I'm not sure I'd even enable that option just based on the fact that I'll probably forget about it.

**Comment by darahak** [comment]
Why not both?
I think this could be fixed by a `Use global installation` setting, like in the `linter-eslint` package.
And the blacklist could solve [prettier#787](https://github.com/prettier/prettier/issues/787) for example

**Comment by blainekasten** [comment]
I'm with @mxstbr here. I came here to raise this issue. Glad to see I'm not the only one facing this. I personally do not create a new repo every day, but I'm even just thinking organizationally as I try to introduce prettier to my company, asking every person in the company to set up their blacklist creates friction points to adoption.

**Comment by robwise** [comment]
Sorry if I've been unclear on this, we are definitely going to get this addressed. Right now the plan is we are going to look for prettier/prettier-eslint (depending on your eslint integration setting), and if we don't find it, we will have an option in the settings where you can specify if you want us to fall back to the included packaged version or just not do anything. https://github.com/jlongster/prettier-atom/issues/59#issuecomment-287848381
