### ISSUE TITLE
json-stringify scope not supported

### ISSUE THREAD

**Issue by pbarbiero** [prettier/prettier-atom#430]
Prettier 1.13 added a new scope, json-stringify -- specifically for package.json (or similar) files to stop it fighting with package managers for example. See https://github.com/prettier/prettier/pull/4450

It appears that prettier-atom is overriding that and treating package.json as the json parser again, and I cant see how to fix that with the current provided options.

**Comment by robwise** [comment]
This will probably be resolved with #404, but I'm going to leave it open until then.
