### ISSUE TITLE
TypeScript Not Formatted on Save

### ISSUE THREAD

**Issue by shellscape** [prettier/prettier-atom#433]
I'm not quite sure where to begin on providing triage up front for this one. I have a mixed project, where both ESLint (latest) and TSLint (latest) exist. Prettier is installed (latest) and works great with on the JavaScript files in the project, formats as expected on save. However, Prettier seemingly does nothing on the TypeScript files in the project. No errors, no warnings, no formatting on save.

I searched the issues here and couldn't find anything related. I did find one that had to do with out of date dependencies, but I'm up to date. I'm a bit baffled.

`Prettier:Debug` Output:
```
Atom version: 1.28.2
prettier-atom version: 0.54.0
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.1
prettier-atom configuration: {
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon",
    "arrowParens": "avoid"
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "scopes": {
    "javascript": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescript": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "css": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "json": [
      "source.json"
    ],
    "graphQl": [
      "source.graphql"
    ],
    "markdown": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "vue": [
      "text.html.vue"
    ]
  }
}
```

**Comment by robwise** [comment]
@chrisdrackett Maybe make a separate issue for that? It would depend on whether this is happening with prettier or just prettier-atom (the former being something you should bring up over at the Prettier repo).

@shellscape Does prettier run properly when run from the command-line (as opposed to the atom package)? This would help narrow things down a bit.

**Comment by shellscape** [comment]
@robwise it appears to yes

**Comment by robwise** [comment]
@shellscape Does anything happen when invoking format manually?

You might try running a dev version.

To run a dev version:

- `atom develop prettier-atom`
- `cd ~/.atom/dev/packages/prettier-atom`
- `yarn install`
- `yarn build`
- `atom -dev .` 

Make sure to rebuild the project if you make a change and then tell Atom to `reload window` (or restart Atom) in order to pick up the changes.

Then you can insert some debug statements to figure out what's going wrong. 

Note to self: we really should make a debug mode so this no longer is necessary in the future.

**Comment by luastoned** [comment]
Maybe you have the experimental Tree-Sitter parsing enabled? See #398

**Comment by erezny** [comment]
@luastoned identified the issue in my environment. 

The workaround is to open Settings, Core tab, and disable "Use Tree Sitter Parsers"

![image](https://user-images.githubusercontent.com/1763111/43733269-ee126742-9968-11e8-9569-8c11fd9b44cc.png)
