### ISSUE TITLE
Look for prettier in parent projects

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier-atom#434]
when using prettier in a mono-repo I get the impression that in child projects without prettier in their deps that the build in copy of prettier is being used. Ideally this package could look into parent directories to try and find a version of prettier in a package.json

**Comment by robwise** [comment]
I think it's already working like this isn't it (using [read-pkg-up](https://www.npmjs.com/package/read-pkg-up))?

**Comment by chrisdrackett** [comment]
hm, I'll do more investigating. I'm running into issues where my files are formatted on save and then formatted again on commit (using lint-staged) this lead me to believe that a different version is being used for both.

**Comment by MadLittleMods** [comment]
As a note around nested projects (multiple `package.json`), initially I couldn't figure out why format on save wasn't working.

I had to turn off ` Only format if prettier is found in your project's dependencies` as I only had `prettier` in the root `package.json` but not any of the sub-modules. Some more details here, https://gitlab.com/gitlab-org/gitter/webapp/merge_requests/1292

**Comment by j-f1** [comment]
@MadLittleMods (off-topic: feel free to add GitLab to the [users list](https://prettier.io/en/users/) if you end up adopting Prettier)

**Comment by MadLittleMods** [comment]
@j-f1 GitLab is already using Prettier, but I am looking to use it in Gitter (owned by GitLab) as well

 - https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/17695 
 - https://docs.gitlab.com/ee/development/new_fe_guide/style/prettier.html
 - https://gitlab.com/gitlab-org/gitlab-eslint-config/
 - https://gitlab.com/gitlab-org/gitlab-ce/blob/daca42ac648166ea90ad6eb87e912c0b8c852933/.prettierrc
