### ISSUE TITLE
ignores settings in package.json

### ISSUE THREAD

**Issue by despairblue** [prettier/prettier-atom#444]
Since #404 landed options in the package.json are ignored. I mentioned that [here](https://github.com/prettier/prettier-atom/pull/404#issuecomment-409617296) already. I know prettier-atom does not read any options anymore, but it must has something to do with how prettier-atom is invoking prettier, because if I run the local prettier from the terminal it works correctly.

Specifically it ignores this part in my package.json:

```
  "prettier": {
    "trailingComma": "es5"
  },
```

<details>
<summary>Prettier: Debug</summary>
Atom version: 1.29.0
prettier-atom version: 0.55.1
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "excludedGlobs": [
      "package.json"
    ],
    "showInStatusBar": true,
    "respectEslintignore": true,
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "parser": "flow"
  },
  "silenceErrors": true,
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

**Comment by despairblue** [comment]
Just tested copy'n pasting the config into a `.prettierrc` file. Than the prettier instance started by prettier-atom picks it up.

**Comment by despairblue** [comment]
I think I found the problem. It seems the cwd is not set correctly for the process.

The way it happened is: 

I have a global prettier installation and a local one. The local one was removed because I did a `yarn --production` to build a docker image. It than picked up the global prettier which did not find the configuration in the package.json local to the file that was formatted.

**Comment by robwise** [comment]
@despairblue Why does the global one not pick it up? Is it just an old version that you had installed (they didn't always support package.json options IIRC)?

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
