### ISSUE TITLE
config.cson options are ignored

### ISSUE THREAD

**Issue by nikis05** [prettier/prettier-atom#445]
**Issue description:**
Looks like my prettier-atom ignores config options provided in `config.cson`. After I installed a package update the `singleQuote` option is ignored. I tried to run formatting on my code manually with the Prettier CLI with the corresponding option, works fine. In my `config.cson` I have this option set to true. Tried adding some other options to the `config.cson`, they are ignored as well. I have no `.prettierrc` file in my project, am not using tslint.

**Prettier: Debug output:**

<details>
Atom version: 1.29.0
prettier-atom version: 0.55.1
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": true
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

**Comment by robwise** [comment]
@nikis05 As of #404 (which we just finally released), we are no longer relying on Atom settings for defining Prettier options. Unfortunately, Atom has for a long time had a bug where package options from previous versions don't get properly removed, making it look like those options are still relevant to the current options you have installed.

The way to do what you want to do, that is, defining your Prettier options without having to make a `.prettierrc` for every project is to create a global `.prettierrc` in your root `User` folder. Prettier will look up the file tree and find your settings there.

**Comment by nikis05** [comment]
@robwise Thanks a lot! Didn't think of this solution. I think the "Prettier Options" section should probably be removed from the package settings to avoid possible confusion.
