### ISSUE TITLE
Configuration broken with no clear migration path?

### ISSUE THREAD

**Issue by jarecsni** [prettier/prettier-atom#453]
I noticed that Format on save stopped working in Atom with latest prettier-atom.

The plugin's page helpfully mentions that configuration now sourced from a config file rather than the atom plugin's preference page. 

Have a few issues with this:

1) Why do we still have the config preference sheet in atom preferences if those settings take no effect?
2) Not clear how those individual settings map to prettierrc preferences?

Effectively the plugin got broken and I can find no documentation, migration help on your site anywhere. Can you please help?

**Comment by jarecsni** [comment]
Just to add to this, formatting with Ctrl-Alt-F isn't working either (it's not formatting according to eslint rules as it used to).

**Comment by jarecsni** [comment]
Sorry for jumping the guns - typical early morning oversight... there was a missing curly brace in my code :D which essentially caused prettier to skip formatting, the comment in the release notes about moving to prettierrc reassured me that there was something wrong with prettier-atom :) Closing issue now.

**Comment by robwise** [comment]
@jarecsni No worries. Was the curly brace in the config file or your normal JS code you were trying to format? If the latter, the plugin should have at least given you a syntax error displayed by linter (or nuclide).

**Comment by jarecsni** [comment]
@robwise It was my code not the config. I think I probably did not notice it :) Thanks!
