### ISSUE TITLE
Enable/disable package duplicates status button

### ISSUE THREAD

**Issue by tcrowe** [prettier/prettier-atom#456]
```
Atom version: 1.31.2
prettier-atom version: 0.55.2
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
```

Hey doods :wave:

If I enable/disable this it wont remove it's status element.

<img width="168" alt="screen shot 2018-10-08 at 8 39 54 am" src="https://user-images.githubusercontent.com/1634015/46701222-3bb8a380-cbdc-11e8-8fce-4b4816fb01ff.png">

<img width="449" alt="screen shot 2018-10-08 at 8 39 50 am" src="https://user-images.githubusercontent.com/1634015/46701223-3c513a00-cbdc-11e8-9330-1d2a1cce5fe5.png">

Repro steps:
+ Enable prettier-atom
+ Disable prettier-atom
+ Enable prettier-atom
+ Disable prettier-atom
+ Enable prettier-atom
+ Disable prettier-atom

Really mash it for the full effect! 💪🏼

**Comment by robwise** [comment]
Hey there, that's strange. I'm not getting it locally on my version. Is anyone else getting this also? Could it be some sort of dis-synergy between prettier-atom and the theme you're using?

**Comment by robwise** [comment]
Hmm, probably not the theme then. Yeah that setting needs to be enabled for the thing to show up, but clicking it doesn't cause clones like that for me. I'm not sure why this would be happening.

**Comment by tcrowe** [comment]
Thanks for taking a look, @robwise. If we can't reproduce it perhaps it is just an odd combination of plugins.

I'll close it out and if anyone searching finds it in the future we can see. 👍
