### ISSUE TITLE
preferred way to run eslint with prettier

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier-atom#459]
I know the README mentions ways to do it, but I'm wondering what is best.

Regarding option 2, I have eslintrc configured to ignore prettier rules (`eslint-config-prettier`). In this case, can I tell the `linter-eslint` plugin to fix on save, as well as tell `prettier-atom` to format on save? 

Will that cause issues (f.e. a race condition?). So far from limited testing, it seems to work, but I am wondering if I am only lucky because prettier finishes before eslint?

If I want to fix both eslint and prettier issues on save, should I prefer using `prettier-eslint` or will the other one work fine?

**Comment by trusktr** [comment]
> ESLint is just going to overwrite any changes that prettier-atom made since it has no idea that prettier-atom changed anything (a last wins race condition).

Interesting. I thought this is what the `eslint-config-prettier` was for, so that (hopefully) ESLint would not format anything related to what Prettier formats.

So far after testing, it seems to work (ESLint running after Prettier), but I have only tested for a day, on a handful of files.

> I think probably you're highlighting that there is an issue here with the documentation

👍 

> Option 2 makes it sound like you can have both linter-eslint fix-on-save and prettier-atom format-on-save enabled, which is not true.

I was hoping they'd be mutually exclusive (at least 99.999% of the time) so that it wouldn't matter (does the `eslint-config-prettier` otherwise serve any purpose?). I.e. I would think that ESLint will never complain about format issues that Prettier fixes, or that Prettier formats to, and I assume that ESLint will only fix things I've specified that are not related to Prettier formatting.

---

In any case, I have a commit hook in my project that run ESLint first, _then_ Prettier, so even if some formatting were to get funky from the race condition in Atom, the commit hook will always straighten things up.

---

Also please let me know this is true: Prettier eslint config ignores all formatting that Prettier handles? And it also ignores properly formatted Prettier code?

If this is true, and if eslintrc does not touch any Prettier pre/post format code, then in theory it shouldn't matter which one runs first right?

**Comment by robwise** [comment]
> In any case, I have a commit hook in my project that run ESLint first, then Prettier, so even if some formatting were to get funky from the race condition in Atom, the commit hook will always straighten things up.

As long as you've got `eslint-config-prettier` it shouldn't matter which order you do it in, just that you don't run both scripts at the same time in two different CLI tabs.

> Also please let me know this is true: Prettier eslint config ignores all formatting that Prettier handles? And it also ignores properly formatted Prettier code? If this is true, and if eslintrc does not touch any Prettier pre-/post- auto-format code, then in theory it shouldn't matter which one of the two tools runs first right?

The race condition doesn't come from the two trying to fix the same type of formatting error, but rather that the two are each replacing the text in the Atom buffer with their result, and if they happen concurrently instead of synchronously, then the last one is going to overwrite the previous one's result.

If this is the original code, and prettier capitalizes just `bar` and eslint capitalizes just `foo`, they still have a race condition if you run them at the same time:

```
foo
bar
```

prettier returns:

```
foo
BAR
```

and eslint returns

```
FOO
bar
```

Whoever finishes last wins, even though they aren't touching the same part of the code, because ALL of the code is overwritten.

**Comment by francoism90** [comment]
@robwise So basically if you combine option 1 + 3, you will end up with something like this:
```
// .eslintrc.js
module.exports = {
  root: true,
  env: {
    es6: true,
    browser: true,
    node: true
  },
  parserOptions: {
    parser: "babel-eslint",
    ecmaVersion: 2017,
    sourceType: "module"
  },
  extends: [
    /**
     * https://prettier.io/docs/en/eslint.html#use-both
     * https://github.com/prettier/prettier-atom (3. Use prettier-eslint)
     */
    "plugin:prettier/recommended",
    "plugin:vue/recommended"
  ],
  plugins: ["import", "promise"],
  rules: {}
};
```

**Comment by trusktr** [comment]
That makes sense. However, I haven't experienced this problem yet when running both independently, and it seems like both tools are making their modifications successfully.

I have began to use the eslint-integration from the prettier package, so it shouldn't be a problem.

Thanks for the input!
