### ISSUE TITLE
prettier 1.15 javascript breaking changes

### ISSUE THREAD

**Issue by gex** [prettier/prettier-atom#461]
prettier 1.15 came out on [nov 7](https://prettier.io/blog/2018/11/07/1.15.0.html) and it introduced a [new formatting for nested ternary operators](https://prettier.io/blog/2018/11/07/1.15.0.html#flatten-else-branch-for-nested-ternaries-5039-by-suchipi-5272-by-duailibe-5333-by-ikatyang). since this package hasn't been updated since august (and prettier 1.13) my editor and my ci environment are testing my files differently and the auto-formatted files don't pass the tests. is it possible to upgrade prettier to the latest version somehow?

**Comment by robwise** [comment]
Yep I'll bump now
