### ISSUE TITLE
How to tell prettier to format on save for HTML files?

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier-atom#467]
I've opened an HTML file, and the latest `prettier` supports format for `.html` files.

Running `prettier some-file.html` at the command line works great, but format on save isn't working while in an `.html` file.

Does this repo need a code update for that?

**Comment by pmrotule** [comment]
I have the same issue with the html of my Vue single file components. Prettier cli would break attributes into multiple lines if the line exceeds 80 characters but nothing is happening with this package. It only formats my `<script>` and `<style>` tags on save.

**Comment by MiLeung** [comment]
I have the Prettier shown in my status bar, but when I open a .html file, the Prettier button goes away and the file doesn't format on save. Help?

**Comment by robwise** [comment]
@MiLeung Can you make sure your local Prettier version (assuming your project has one) is up to date? HTML parsing wasn't added until 1.15 IIRC.

**Comment by MiLeung** [comment]
https://github.com/prettier/prettier-atom/issues/491
