### ISSUE TITLE
After Uninstalling prettier-atom ,I tried to reinstall it I am getting following error

### ISSUE THREAD

**Issue by ash123mani** [prettier/prettier-atom#469]
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ashutosh/.atom/.apm/.apmrc" "--userconfig" "/home/ashutosh/.atom/.apmrc" "install" "/tmp/d-1181029-4554-1l0n5qn.6muoc4n29/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file /home/ashutosh/.atom/.apm/vfile-location/2.0.4/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/ashutosh/.atom/.apm/vfile-location/2.0.4/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1181029-4554-14tnl37.bqapa7zaor/npm-debug.log

Please help me out !!

**Comment by robwise** [comment]
Are you still having this issue?

**Comment by ash123mani** [comment]
I started using vs code , I will check .

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Comment by ash123mani** [comment]
Sure, @robwise thanks
