### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by masquevil** [prettier/prettier-atom#475]
Installing “prettier-atom@0.56.2” failed.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp http GET https://atom.io/download/electron/v2.0.9/iojs-v2.0.9.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at _errnoException (util.js:1024:11)
gyp ERR! stack     at TLSWrap.onread (net.js:615:25)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/xr/.atom
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by robwise** [comment]
Anyone else having this issue?

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
