### ISSUE TITLE
Plugin cannot find global prettier

### ISSUE THREAD

**Issue by deathgaze** [prettier/prettier-atom#476]
I'm getting the following error: `Your Prettier version is not compatible with prettier-atom. Prettier must be >= 1.13.4`. After getting this, I installed `prettier` as a global package with `yarn install -g prettier`. After shutting down and restarting Atom, I'm still getting this issue.

Not quite sure where to go from here as I don't know what mechanism the plugin is using to detect my prettier version. I do know for sure that the project I'm attempting to run this in doesn't have prettier installed. When I do install prettier into the project, it appears to work, but I don't want to add prettier to this project's dependencies.

```
[ksefchik@Kirks-MacBook-Pro ~/dev/<snip>/csw-ui]
(master) $ prettier -v
1.15.3
[ksefchik@Kirks-MacBook-Pro ~/dev/<snip>/csw-ui]
(master) $ which prettier
/usr/local/bin/prettier
```

<details>
  Atom version: 1.33.0
prettier-atom version: 0.55.2
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "trailingComma": "all"
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

**Comment by robwise** [comment]
It sounds like we were somehow detecting a local version of prettier inside of your package.json.

It goes package.json -> global -> bundled-with-plugin in that order of resolution. 

However, we do cache certain lookups for performance so this may also be contributing to confusion so make sure to restart Atom if you change your global just to make super sure that it isn't a caching issue.

Also, can you bump to the latest version of prettier-atom to ensure you've got the latest bundled version of prettier?

**Comment by kikoseijo** [comment]
I had this message until I disabled this option:

![screen shot 2019-01-29 at 13 53 48](https://user-images.githubusercontent.com/1528668/51909639-68800900-23cd-11e9-99b1-cfcc023710df.png)

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
