### ISSUE TITLE
Prettierignored files being formatted.

### ISSUE THREAD

**Issue by conartist6** [prettier/prettier-atom#477]
Format-on-saves files which are .prettierignored. No combination of settings will get it to stop.

prettier-atom 0.55.2

prettier@1.14.3 installed as a dev dependency.

**Comment by robwise** [comment]
@conartist6 I'm not able to reproduce locally. If you call prettier directly from the command line, does this still happen?

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
