### ISSUE TITLE
Prettier missing Options section on Atom UI

### ISSUE THREAD

**Issue by djbinary** [prettier/prettier-atom#479]
Windows 10 (Latest Version)
Atom editor. (Latest Version 1.33.1 x64)
I installed the latest Prettier module, via Atom installer (Also tried CMD, with same problems)
I installed ALL dependencies too.

When I format .js files via prettier, it removes all semicolomns, and replaces single quotes to double quotes.
On all tutorials I have seen on the internet for the Atom editor, there is a section on setting, where you can enable / disable single quote, semicoloms, (There is a simple checkbox UI)
However, I do NOT have these checkboxes available. Basically the "Prettier Options" section is missing.
I tried adding `.prettierrc` file to the ROOT of my project (Same directory of index.js file)
With parameters 
```
{
  "trailingComma": "es5",
  "tabWidth": 4,
  "semi": true,
  "singleQuote": true
}
```
But doesn't change anything. 

Have the settings changed? Do we now need to change this file to reflect settings? Where can I find parameters to add to this file? I searched everythwhere on the internet, but I cannot understand what I need to do. 
Can someone please tell me what parametes I need, saved in which file type, and what location on the project file? I am new to this world. Any help is appreciated.

Thank you!
![02](https://user-images.githubusercontent.com/6247309/50741876-76da6b00-11fb-11e9-993b-f00255fd3f43.PNG)
![03](https://user-images.githubusercontent.com/6247309/50741877-76da6b00-11fb-11e9-9970-e3fccbab0c69.PNG)

**Comment by j-f1** [comment]
I’ve moved this issue to the repo for the Atom package.

**Comment by robwise** [comment]
@djbinary We have removed the in-editor settings from prettier-atom since prettier now supports a `.prettierrc` config file. You will need to place this file inside of your project. Please ensure you have restarted Atom after placing this file.

**Comment by jdarling** [comment]
Just ran into this and think it's pretty janky that you went from a global set of settings that didn't require changes in every project to a settings file per project without a way to setup global settings.  Is there a global prettierrc or a section in the atom configuration files that we can set things, or are we expected to add yet another configuration file to every project we work on?

**Comment by robwise** [comment]
Just put a `.prettierrc` in your home directory; this is how every other formatting tool/linter works. 

There was extensive discussion about why we had to do this, but to recap, here are a couple of issues off the top of my head:

- Every time a new feature was being added to Prettier we'd have to update the plugin to accommodate it which was a lot of manual work.
- If the plugin was updated to include said feature but the local version of Prettier in the project repo was older and didn't have the feature it was confusing what would happen.
- The "plugins" functionality for Prettier which greatly extends Prettier's usefulness by adding support for other languages was logically impossible to combine with a global Atom config.

**Comment by djbinary** [comment]
> Just put a `.prettierrc` in your home directory;
What do I write in that file?
How can I tell the file to:
Turn every double quote to single on save
What would be the code in this case?

I have read the documentation. However, I could not understand what to do. It's not well documented for some newbie like me.

Thanks

**Comment by robwise** [comment]
If you want to have non-default settings for Prettier that are always used without having a project-specific .prettierrc, you can just place a `.prettierrc` file in your home directory. This isn't something to do with prettier-atom directly, really, it's just the normal prettier behavior documented here: https://prettier.io/docs/en/configuration.html

**Comment by teamworktec** [comment]
> @djbinary We have removed the in-editor settings from prettier-atom since prettier now supports a `.prettierrc` config file. You will need to place this file inside of your project. Please ensure you have restarted Atom after placing this file.

It worked, after restart atom editor 💯
