### ISSUE TITLE
Fix on save causing atom to crash randomly

### ISSUE THREAD

**Issue by rohan-deshpande** [prettier/prettier-atom#481]
This isn't happening on all files, funnily enough it seems to be happening for any file that imports [`three`](https://github.com/mrdoob/three.js/). Example code 

```javascript
import { Scene } from 'three';
```
 
With format on save enabled, the editor hangs indefinitely and prompts me to close it. When turned off, all works as expected. I recently updated the prettier atom version, was not having this issue in the previous release. I doubt this has anything to do with `three` but just listing it as it may provide some clues.

```json
Atom version: 1.34.0
prettier-atom version: 0.56.2
prettier: bundled
prettier version: 1.15.2
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment]
Hmm, that's extremely weird. Neither prettier nor prettier-atom attempts to actually resolve your code's dependencies, so it shouldn't matter what library is being imported. Are you sure something else isn't the common link between the files that cause this?

**Comment by rohan-deshpande** [comment]
Yeah I did think it was odd, but turning off format on save fixed the issue. I'll try once again after a full reboot and see if the issue persists.

**Comment by rohan-deshpande** [comment]
Full reboot didn't help, this is still happening, anything I can do to help you find what the issue might be?

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.
