### ISSUE TITLE
Handle graphqls extension

### ISSUE THREAD

**Issue by slisaasquatch** [prettier/prettier-atom#482]
Prettier can format both GraphQL queries (*.graphql files) and GraphQL schemas (*.graphqls files) correctly, but prettier-atom doesn't seem to handle *.graphqls files.

I've tried renaming a schema to have the graphql extension, and prettier-atom is able to format it correctly.

<details>
Atom version: 1.34.0
prettier-atom version: 0.56.2
prettier: bundled
prettier version: 1.15.2
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "useEslint": false,
  "useStylelint": false,
  "formatOnSaveOptions": {
    "enabled": false,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

**Comment by robwise** [comment]
That's strange, prettier-atom is just piping through to prettier (both when determining whether or not in can format a file and actually doing the formatting). I will look into it. Can you post a sample snippet of some very simple code to format so I can test it?

**Comment by slisaasquatch** [comment]
Sure. Try this:
```graphql
type Query {
  field1(
    arg1: Int
    arg2: Boolean
    arg3: String
    arg4: Int = 1
    arg5: Float! = 0.6
  ): String
}

schema {
  query: Query
}
```

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.
