### ISSUE TITLE
Installing “prettier-atom@0.56.2” failed

### ISSUE THREAD

**Issue by yuvraj2112** [prettier/prettier-atom#483]
npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\I328437\AppData\Local\Temp\apm-install-dir-119029-14664-1o68puz.vpda\package.json'
npm WARN apm-install-dir-119029-14664-1o68puz.vpda No description
npm WARN apm-install-dir-119029-14664-1o68puz.vpda No repository field.
npm WARN apm-install-dir-119029-14664-1o68puz.vpda No README data
npm WARN apm-install-dir-119029-14664-1o68puz.vpda No license field.

npm ERR! path C:\Users\I328437\AppData\Local\Temp\apm-install-dir-119029-14664-1o68puz.vpda\node_modules\prettier-atom\node_modules\prettier-stylelint\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\I328437\AppData\Local\Temp\apm-install-dir-119029-14664-1o68puz.vpda\node_modules\prettier-atom\node_modules\prettier-stylelint\cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I328437\.atom\.apm\_logs\2019-01-29T07_15_50_147Z-debug.log

**Comment by robwise** [comment]
Closing as others aren't having this issue.

**Comment by Drapegnik** [comment]
@robwise I have the same, and https://github.com/AtomLinter/linter-eslint/issues/1275 too, any ideas wthat's wrong?

**Comment by robwise** [comment]
@Drapegnik Are you sure it's 100% the same error with the same underlying library? I would try uninstalling and re-installing your prettier-atom package to make sure you have the latest associated packages.
