### ISSUE TITLE
.eslintrc not being respected

### ISSUE THREAD

**Issue by vincerubinetti** [prettier/prettier-atom#488]
I have the following `test.js` file:

``` javascript
function test() {
    let longVarName = element.longConditionalPartA || element.longConditionalPartB;

    if (test) return true;
    else return false;
}

test();
```

The second line is > 80 char wide and should be wrapped automatically by prettier. Also, the single-line conditional statements should be put on their own separate lines per the `.eslintrc` file in my project directory:

```
{
    "extends": ["google"],
    "parserOptions": { "ecmaVersion": 6 },
    "env": { "es6": true, "browser": true },
    "plugins": ["html"],
    "rules": {
        "curly": ["error", "multi-or-nest"],
        "eqeqeq": ["error", "always"],
        "comma-dangle": ["error", "never"],
        "indent": ["error", 4],
        "keyword-spacing": ["error"],
        "one-var": ["off"],
        "space-in-parens": ["error"],
        "space-infix-ops": ["error"],
        "no-var": ["off"],
        "require-jsdoc": ["off"],
        "nonblock-statement-body-position": ["error", "below"]
    }
}
```

When pressing `ctrl+alt+f`, my output changes to this, which is basically just default `prettier` styling:

```
function test() {
  let longVarName =
    element.longConditionalPartA || element.longConditionalPartB;

  if (test) return true;
  else return false;
}

test();
```

Running `prettier-eslint` from the command line (installing `eslint`, `prettier`, `prettier-eslint`, and `prettier-eslint-cli` globally and running `prettier-eslint test.js --write`, gives the expected output, with the long statement wrapped by `prettier`, and the inline conditionals put on their own line by `eslint`:

```
function test() {
    const longVarName =
        element.longConditionalPartA || element.longConditionalPartB;

    if (test)
        return true;
    else
        return false;
}

test();
```

I saw other issues of the `.eslintrc` file not being respected, but the resolution to those issues involved a bugfix to `prettier-eslint` itself, which seems to already have been implemented. Further, it seems in my case, using `prettier-eslint` directly is working just fine.

My debug:

```
Atom version: 1.34.0
prettier-atom version: 0.56.4
prettier: bundled
prettier version: 1.15.2
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "isDisabledIfNoConfigFile": true,
    "respectEslintignore": false,
    "enabled": false,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "useEslint": true,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by sanjaypojo** [comment]
Facing the same issue recently. Prettier has not been following the rules in my eslintrc (semi-colons are back with no code change and simply upgrading prettier)

**Comment by robwise** [comment]
@sanjaypojo Can you verify with prettier run from the CLI versus the atom package? If you've simply upgraded prettier it could be due to them adding editorconfig integration if you've added that or some other API change on their part.

**Comment by sanjaypojo** [comment]
@robwise don't have prettier installed outside atom. I downgraded prettier-atom to `v0.54` and it started respecting eslint rules again (`apm install prettier-atom@0.54.0`)

**Comment by robwise** [comment]
I'm confused, are you bumping prettier or prettier-atom? Are you 100% you do not have prettier in your node modules?

**Comment by sanjaypojo** [comment]
I don't have prettier in node_modules and I don't have a global install of prettier either. I do have `prettier-eslint` in node_modules though. When I'm on `prettier-atom@0.54.0` everything works fine. If I upgrade to the latest version of `prettier-atom`, prettier-atom adds semicolons everywhere and eslint shows warnings that semicolons aren't expected.

Here's my `.eslintrc.js`:
```javascript
const fs = require("fs")
const schema = fs.readFileSync("/path/to/file", "utf8")

module.exports = {
  parser: "babel-eslint",
  env: {
    browser: true,
    amd: true,
    es6: true,
    "react-native/react-native": true
  },
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:flowtype/recommended",
    "plugin:jest/recommended"
  ],
  plugins: ["react", "flowtype", "react-native", "jest", "graphql"],
  rules: {
    quotes: ["warn", "double"],
    semi: ["warn", "never"],
    "valid-jsdoc": ["error"],
    "no-console": ["warn"],
    "max-len": ["warn", { code: 90, ignoreStrings: true }],
    "no-unused-vars": ["error", { args: "none" }],
    "require-yield": ["warn"],
    "graphql/template-strings": [
      "error",
      {
        // Import default settings for your GraphQL client. Supported values:
        // 'apollo', 'relay', 'lokka', 'fraql', 'literal'
        env: "apollo",

        // Import your schema JSON here
        // schemaJson: require("./schema.json")

        // OR provide absolute path to your schema JSON (but not if using `eslint --cache`!)
        // schemaJsonFilepath: path.resolve(__dirname, './schema.json'),

        // OR provide the schema in the Schema Language format
        schemaString: schema

        // tagName is gql by default
      }
    ]
  },
  settings: {
    react: {
      version: "detect"
    }
  }
}
```

I can confirm that the only instance of the word `prettier` in my package.json is `prettier-eslint`.

**Comment by robwise** [comment]
Hmm that's strange, prettier-eslint did have a major bug until recently but we've made a fork that should fix it.

That said, since you're still having an issue, I would definitely recommend just dropping `prettier-eslint` and adopting `eslint-config-prettier` and `eslint-plugin-prettier` and running that way (and disable `eslint-integration` in prettier-atom).

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.
