### ISSUE TITLE
Shorter Stack Trace Option?

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-atom#49]
As per #45 we were discussing whether it would be useful to be able to choose whether you want the long error message with the full stack trace versus a shorter message. Or perhaps we just should change it so it always shows the shorter message.

Anyone have thoughts on this?

**Comment by erbridge** [comment]
I think highlighting the syntax error (when that's the issue) in the code with a short popup to point out that it failed would be my preferred solution.
