### ISSUE TITLE
Error on save of SCSS files if no stylelint config file found

### ISSUE THREAD

**Issue by drewbaker** [prettier/prettier-atom#492]
Whenever I try to save a .SCSS file, I get an error like this error:

```
prettier-atom failed: No configuration provided for /Users/drew/Local Sites/stackhaus/styles/_base.scss
```

I have a `.prettierrc` file in my project root, but if I remove that, I still get the same error. I do not have a a Stlyelint config file. If I uncheck the "Stylelint Integration" checkbox in the Prettier settings, then it doesn't throw the error. So it seems prettier-atom is not handling the missing Stlyelint config file correctly.

It seems to work fine for .JS and .VUE files, and I don't have an ESLint config file I have installed prettier-eslint and prettier-stylelint into my package.json file.

```
  "devDependencies": {
    "node-sass": "^4.11.0",
    "nodemon": "^1.18.9",
    "prettier-eslint": "^8.8.2",
    "prettier-stylelint": "^0.4.2",
    "sass-loader": "^7.1.0"
  }
```

I don't know where to run the `Prettier: Debug` command, but I'd be happy to give more details if someone tells me how/where to run that.

**Comment by robwise** [comment]
Hey @drewbaker, yep stylelint doesn't work without a `.stylelintrc` file, so I would either turn the integration off if you're not using stylelint or add a `.stylelintrc`. 

That error is getting thrown by stylelint itself and prettier-atom is just sort of bubbling it up so you can see it.

**Comment by drewbaker** [comment]
Thanks Rob! Good to know.

But that isn't what the instructions on the checkbox say. It reads to me that if there is no `.stylelintrc` file it will fall back to the "Prettier Options section" which don't exist anymore, so I figured it would use the settings from `.prettierrc` then.

So ideally you need to either make the `.prettierrc` fallback work or change those instructions.

![Screen Shot 2019-04-11 at 11 52 28 AM](https://user-images.githubusercontent.com/475015/55983612-5aadf600-5c50-11e9-8a93-68829c992b06.png)

**Comment by robwise** [comment]
Hmm, yeah, I need to go back and figure out what I used to do here. We've removed the Prettier Options section obviously so at the very least the tooltip is wrong. I wish it gracefully fell back the way prettier-eslint does instead of blowing up. I might have to manually check for the .stylelintrc for them.

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.
