### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by ftaiolivista** [prettier/prettier-atom#493]
[Enter steps to reproduce:]

1. Install prettier-atom
2. restart atom

**Atom**: 1.36.0 x64
**Electron**: 4.1.1
**OS**: linux 5.0.7-zen1-1-zen
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.56.4

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/vista/.atom/packages/prettier-atom/node_modules/prettier/index.js:40036

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at /packages/prettier-atom/node_modules/prettier/index.js:40036:21
    at createCommonjsModule (/packages/prettier-atom/node_modules/prettier/index.js:192:35)
    at /packages/prettier-atom/node_modules/prettier/index.js:39843:18)
    at /packages/prettier-atom/node_modules/prettier/index.js:41849:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/helpers/getPrettierInstance.js:4:25)
    at /packages/prettier-atom/dist/helpers/getPrettierInstance.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/helpers/index.js:9:29)
    at /packages/prettier-atom/dist/helpers/index.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/statusTile/updateStatusTileScope.js:3:56)
```

### Commands

```
```

### Non-Core Packages

```
atom-arc-ui 1.1.0 
atom-beautify 0.33.4 
atom-charcoal-syntax 1.7.0 
atom-debug-ui 1.0.4 
atom-easy-jsdoc 4.12.5 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
base16-syntax 1.8.1 
busy-signal 2.0.1 
cursor-history 0.13.2 
dark-flat-ui 1.2.4 
docblockr 0.13.7 
fast-eslint 4.10.0 
file-icons 2.1.31 
file-types 1.0.1 
genesis-syntax 1.0.9 
genesis-syntax-fbn 1.0.9 
genesis-ui 0.5.0 
genesis-uii-fbn 0.5.0 
git-diff-details 1.4.0 
git-diff-popup 0.1.8 
git-time-machine 2.1.0 
goto-definition 1.3.4 
ide-php 0.7.18 
ide-reason 1.1.9 
intentions 1.1.5 
language-docker 1.1.8 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-htaccess 0.2.0 
language-javascript-jsx 0.3.7 
language-ocaml 1.9.5 
language-reason 0.0.5 
language-twig 1.6.3 
line-ending-converter 1.3.2 
linter 2.3.0 
linter-eslint 8.5.3 
linter-js-standard 6.1.1 
linter-jshint 3.1.15 
linter-phpcs 1.6.13 
linter-phpmd 2.0.1 
linter-ui-default 1.7.1 
local-history 4.3.1 
lorem 4.0.0 
markdown-writer 2.11.5 
material 2.2.0 
material-ui 1.0.10 
minimap 4.29.9 
minimap-pigments 0.2.2 
nucleus-dark-ui 0.12.3 
one-dark-vivid-syntax 1.8.1 
php-debug 0.3.5 
php-twig 4.0.0 
pigments 0.40.2 
prettier-atom 0.56.4 
print-atom 0.1.1 
project-plus 1.0.0 
project-view 0.6.5 
project-viewer 1.3.1 
reason-refmt 0.3.3 
slim-dark-ui 0.12.0 
solarized-dark-ui 0.3.2 
split-diff 1.6.0 
sync-settings 0.8.6 
tablr 1.8.3 
tabs-to-spaces 1.0.5 
tester 1.4.0 
tester-phpunit 1.0.6 
tool-bar 1.1.11 
vim-mode-plus 1.36.0 
```

**Comment by ftaiolivista** [comment]
Workaround by @darekmeco [see here](https://github.com/Glavin001/atom-beautify/issues/2338#issuecomment-482627041)

**Comment by robwise** [comment]
I'm having trouble reproducing this one.

I see Atom just had an update, I updated and restarted my Atom and still not having any error. 

Sometimes the Prettier team puts these types of things in their code not realizing it breaks things for editor integrations and such. I think that happened once in the past.

It looks like others are having this issue also? Any ideas on how to get it to reproduce?

**Comment by robwise** [comment]
I'm thinking that since this just started happening on April 12th and Prettier [just released a major version change on the same date](https://prettier.io/blog/2019/04/12/1.17.0.html) and nothing was changed in prettier-atom or atom-beautify (both of which are getting the same error) that this is due to a change in Prettier itself.

Atom has security measures in it that forbid using `eval` in your plugin's code. We don't use `eval` in prettier-atom, but we use `prettier`, which I'm thinking must have introduced `eval` into their code somewhere. The confusing thing is that `eval` appears all over the code base, but I guess there is something special about the new place it was added. 

I think this is the problem line, but I can't be sure: https://github.com/prettier/prettier/pull/5963/files#diff-d566515bb6fb446710493e62794f89e8R21

This has happened twice before:

- https://github.com/prettier/prettier/issues/1895
- https://github.com/prettier/prettier/issues/4764

They're super busy obviously and there's no good way to protect themselves from this type of a regression AFAICT unfortunately.

I will make an issue at Prettier's repo, but until then you need to use prettier-atom with a version of Prettier that is pre-v1.17. You can do that by manually specifying a local Prettier version.

**Comment by langri-sha** [comment]
I have `prettier@16.4` installed locally and seem to be getting the error. Is there anything I can do?

**Comment by robwise** [comment]
@langri-sha It seems to be a problem with Prettier itself, the bundled version with prettier-atom seems to work okay so I would stick with that.
