### ISSUE TITLE
Once you removed Prettier defaults, this plugin sucked.

### ISSUE THREAD

**Issue by drewbaker** [prettier/prettier-atom#503]
This isn't really a issue, I just thought you might like to know my experiences with this plugin in a 3 person team. 

It was almost impossible to get it to work consistently. All we wanted it to do was format CSS, HTML, JS, PHP and VueJS files on save, with a consistent rule set across all machines and all projects.

The combination of styelint and eslint just seemed to never work. We had all sorts of config files in projects or root folders, and it seemed that constantly it wouldn't format on save or complain about some error. We must have spent hours trouble shooting just this plugin itself.

I really wish you'd go back to central default options, that get overridden by config files if those are present. 

In the meantime we are going to try Atom Beautify.

**Comment by robwise** [comment]
We had it that way and everyone complained about that. You also aren't able to use plugins doing it that way which is a dealbreaker for a lot of users so we were forced to change it to the current architecture.

If you want to have consistent settings for a project, put a `.prettierrc` file in the root of your project. This is how all linters work. I've been using stylelint + eslint + prettier on dozens of projects for 3 years now without any issue. This ensures consistency across developer environments while the way you suggest does not.
