### ISSUE TITLE
Warnings after prettier-atom autolint

### ISSUE THREAD

**Issue by brobee** [prettier/prettier-atom#506]
I installed and turned on the prettier-atom autolint after save and it generates me several errors. Did I miss something?

Errors for instance:
```
warning: Property name "app" is not PascalCase (vue/name-property-casing) at src/App.vue:88:9:
  86 | import { fetchActivies } from '@/api'
  87 | export default {
> 88 |   name: 'app',
     |         ^

```
```
warning: Attribute ":key" should go before "v-bind:activity" (vue/attributes-order) at src/App.vue:75:15:
  73 |               v-for="activity in activities"
  74 |               v-bind:activity="activity"
> 75 |               :key="activity.id"
     |               ^
  76 |             ></activityItem>
  77 |           </div>
  78 |         </div>
```
```
warning: Require self-closing on Vue.js custom components (<activityItem>) (vue/html-self-closing) at src/App.vue:72:13:
  70 |         <div class="column is-9">
  71 |           <div class="box content">
> 72 |             <activityItem
     |             ^
  73 |               v-for="activity in activities"
  74 |               v-bind:activity="activity"
  75 |               :key="activity.id"
```
warning: Attribute "class" should go before "@click"
warning: Attribute "class" should be on a new line

I guess it is too restricted or should I follow these rules? Sorry for my newbie question. Thanks!

**Comment by robwise** [comment]
prettier-atom usually just automatically fixes these errors in JS. In Vue maybe it just provides warnings, but yeah you should follow these rules if you're going to use Prettier as it is pretty intense/opinionated about where to place things. There are only a few configurable rules.
