### ISSUE TITLE
About error "prettier-atom failed: No parser could be inferred for file:"

### ISSUE THREAD

**Issue by mozgbrasil** [prettier/prettier-atom#513]
Good afternoon

Hello my friend

In trying to format the code, the error "prettier-atom failed: No parser could be inferred for file:" is being returned, can you please help me

    $ atom --version
    Atom    : 1.40.0
    Electron: 3.1.10
    Chrome  : 66.0.3359.181
    Node    : 10.2.0

    $ apm list

    Community Packages (32) /home/marcio/.atom/packages
    ├── prettier-atom@0.57.2

    $ npm list -g --depth 0
    /home/marcio/.nvm/versions/node/v12.8.1/lib
    ├── prettier@1.18.2

![Captura de tela de 2019-08-23 16-06-20](https://user-images.githubusercontent.com/17202780/63617558-26fcb880-c5c0-11e9-8809-ca915b85c51e.png)

**Comment by robwise** [comment]
Are you manually invoking prettier via the command, or is this happening on save?

Prettier doesn't format `.ejs` files so it doesn't know what parser to use for that type of file.

**Comment by mozgbrasil** [comment]
Good Morning

Thank you my friend

I tested it with a * .js file and it's working as expected
