### ISSUE TITLE
Editor config

### ISSUE THREAD

**Issue by amk221** [prettier/prettier-atom#514]
I have Format on Save enabled.

When I save, lines are printed at 80 chars.

But when I run prettier on the command line, they are printed at 100 chars.

This is because prettier is respecting the value in my editorconfig.

...but prettier-atom isn't?

<details>
  <summary>debug</summary>
Atom version: 1.40.1
prettier-atom version: 0.57.2
prettier: bundled
prettier version: 1.18.2
prettier-eslint version: 9.0.0
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "isDisabledIfNoConfigFile": true,
    "isDisabledIfNotInPackageJson": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "ignoreNodeModules": true
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "singleQuote": true
  },
  "useStylelint": true,
  "useEslint": false
}
</details>

**Comment by robwise** [comment]
prettier-atom is ripping the desired config settings from the nearest `.prettierrc` from the file in question using `resolveConfig`. It looks like at some point they added the ability to pull in editorconfig settings as well but we have to explicitly tell it to do that:

> If options.editorconfig is true and an .editorconfig file is in your project, Prettier will parse it and convert its properties to the corresponding prettier configuration. This configuration will be overridden by .prettierrc, etc. Currently, the following EditorConfig properties are supported:
>
> end_of_line
> indent_style
> indent_size/tab_width
> max_line_length

https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options


Therefore I think we can add it maybe as a prettier-atom option where you can opt in or out of passing `editorconfig: true` and have prettier respect your options?

**Comment by amk221** [comment]
It's a bit odd that, the default behaviour when running prettier on the command line is to refer to editor config, and you have to specifically opt out, by using `--no-editorconfig`. And your suggestion is I would have to opt in. Would it be better to just do what prettier does by default?

**Comment by robwise** [comment]
Oh hmm that's a good point. I guess the problem lies in that prettier's `resolveConfig` is acting differently (defaults-wise) than the CLI tool. 

But we can "fix" that problem by automatically opting the user in and then allowing them to explicitly opt out via a prettier-atom setting?

**Comment by amk221** [comment]
Yep, it would be 👌 if the prettier-atom editor settings mapped to the prettier cli options

**Comment by amk221** [comment]
Any pointers to help a newbie out getting this sorted?

**Comment by robwise** [comment]
You can look up what the command is to dev on an atom package, I can't remember as I have an alias for it, but it's like `apm develop prettier-atom` or some such which will set you up with a local version of the repo. Then just `yarn install` and `yarn validate`. You can use this version of the package if you do `atom --dev`. You will need to rebuild the dist bundle and reload your window if you make a change and want to see it in Atom.

The gist of the change is that when we ask prettier for its config settings, we now explicitly tell it to respect the editorconfig if it finds one, but only if the user hasn't opted out via the prettier-atom setting (which we also need to add).

The config options live in this file: https://github.com/prettier/prettier-atom/blob/master/src/config-schema.json (this is how it shows up in your package settings in Atom)

We put helpers for accessing these config options here: https://github.com/prettier/prettier-atom/blob/master/src/atomInterface/index.js (so you can figure out whether the user has checked the box or not)

The part where we ask prettier for its config settings is here: https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/executePrettierOnBufferRange.js#L19 (here is where we need to look up the API for resolveConfig from prettier and figure out how to get it to respect the editorconfig, but you need to do it conditionally in case the user has opted out)
