### ISSUE TITLE
compatibility with project eslint@6

### ISSUE THREAD

**Issue by GHLandy** [prettier/prettier-atom#517]
Hello, there, I met the compatibility with my project eslint@6, when call `CTRL+ALT-f` (prettier-atom) to format my js, ts code. It just occur when eslint@6 used in my project. It works fine if I downgrade eslint@5.

Err with my  project setup eslint@6:
![Snipaste_2019-10-14_10-16-27](https://user-images.githubusercontent.com/14830914/66727203-25d56280-ee70-11e9-8ad8-56f150ebcf6c.png)

Can anyone help to solve this? Thanks.

**Comment by GHLandy** [comment]
It occurs on my archlinux book too.

**Comment by robwise** [comment]
I assume this is the same issue as https://github.com/prettier/prettier-atom/issues/505

I would just disable the prettier-eslint integration in prettier-atom and integrate prettier directly into eslint, then use prettier-atom combined with linter-eslint in Atom.
