### ISSUE TITLE
Cannot find module './lib/markup'

### ISSUE THREAD

**Issue by RDee26** [prettier/prettier-atom#563]
I am trying to install the package on my windows laptop and the editor throws an error saying " **Failed to activate the prettier-atom package**  ". Could you please help me with this?

**Comment by robwise** [comment]
Sure, does the error message provide any additional details? If you toggle dev tools, are there errors?

**Comment by RDee26** [comment]
Sorry Robwise, I uninstalled the package and do not have the information on this.
