### ISSUE TITLE
Merging prettier-eslint-atom repo

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-atom#57]
@jlongster Kent Dodds has agreed that we can merge the [prettier-eslint-atom](https://github.com/kentcdodds/prettier-eslint-atom/issues/28) repo in here and just default Eslint to being off. I will have to do a bunch of work to get integrate the two and then I wanted to set up some automated testing. That way it's less code to maintain. I also wanted to turn on some integrations such as Travis CI and Greenkeeper which Kent has set up. Are you still willing to transfer ownership so that I can turn these on?

**Comment by jlongster** [comment]
Definitely willing to, just need to find time to figure out the github permissions stuff to transfer things to the org. Will try to find time today. Sounds exciting, thanks!

**Comment by robwise** [comment]
FYI for other readers: https://github.com/prettier/prettier/issues/758

**Comment by jlongster** [comment]
We moved the other repo but you all are going to merge into this one, right?

You should have access to move this repo over, so you all can do whatever you want!

**Comment by robwise** [comment]
@jlongster I have access to the org but not to this repo specifically as admin?

**Comment by robwise** [comment]
@jlongster okay, merged in the new changes. We're all set. I know you're busy, but when you've got time, can you set me up with whatever it is so that I can turn on CI and stuff like that?

Also, just a heads up that I am going to disconnect the semver of this repo with prettier so that we have more flexibility with releases (sometimes I have bugs and stuff that I need to get released even when there isn't a new version of prettier).

**Comment by robwise** [comment]
@jlongster any word on this one?

**Comment by robwise** [comment]
@jlongster it would be really cool if I could turn on CI and code coverage

**Comment by jlongster** [comment]
@robwise I'm so sorry! I was traveling over the past 2 weeks and not checking notifications too closely. I forgot that we haven't moved this over yet. I can move this repo and then since you have org access I believe you should have more control over it. Sound good?

**Comment by robwise** [comment]
@jlongster sounds good! No worries!

**Comment by jlongster** [comment]
This has now been moved! :) Sorry for the wait.

**Comment by jlongster** [comment]
@robwise Can you check and see if you have perms to set up CI and such now?

**Comment by robwise** [comment]
@jlongster not yet, I think you need to give me admin perms for this repo?

**Comment by jlongster** [comment]
Oh, I thought you already had that, just fixed!

**Comment by robwise** [comment]
@jlongster Awesome!! All set! I will get to work getting CI set up now!
