### ISSUE TITLE
Prettier keeps indenting ad infinitum

### ISSUE THREAD

**Issue by franciscop** [prettier/prettier-atom#700]
Prettier **adds** an indentation level on every save, without a stable/final form. See GIF, where each jumps happens after saving again:

![prettier-unstable](https://user-images.githubusercontent.com/2801252/77016992-831e9400-6979-11ea-85ad-72e7a68c704d.gif)

I would expect it to be formatted to one way, then on every subsequent save it retains that form instead of increasing ad infinitum. It only seems to happen with a template literal inside a `<script>` tag.

Prettier: Debug output:

```
Atom version: 1.41.0
prettier-atom version: 0.56.4
prettier: bundled
prettier version: 1.15.2
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "excludedGlobs": [
      "readme.md",
      "package.json"
    ],
    "showInStatusBar": true,
    "enabled": true,
    "respectEslintignore": true,
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment]
Sorry for the late response.

I'm having trouble reproducing:

![](https://p116.p3.n0.cdn.getcloudapp.com/items/JruWRlPm/Screen%20Recording%202020-03-31%20at%2009.54%20AM.gif?v=6f13b854932eab4a92c5f927b938371c)

**Comment by franciscop** [comment]
It seems I had Atom 1.41.0, let me upgrade first to 1.45.0 and report back because I see the issue with the exact same script as that video you shared:
![repro](https://user-images.githubusercontent.com/2801252/78064976-e1dd0800-7392-11ea-8600-9cf8770e2deb.gif)

Otherwise I'll start checking if it was some extension combination, thanks for following up!

**Comment by franciscop** [comment]
Okay this is fixed, thanks! Updated Atom and it still had the bug, but then updated prettier-atom and now it doesn't happen anymore:

<img width="455" alt="Screen Shot 2020-04-07 at 12 54 07 AM" src="https://user-images.githubusercontent.com/2801252/78612820-8ca96680-786a-11ea-9036-1b09c3bea948.png">
