### ISSUE TITLE
ESLint Integration option shouldn't crash without ESLint config

### ISSUE THREAD

**Issue by silvenon** [prettier/prettier-atom#71]
I have one project which uses ESLint and the other one which doesn't, but I want to cover both without having to switch the "ESLint Integration" option on and off. I suggest altering the behavior of it to not crash without ESLint config, but instead to fall back to regular prettier.

What do you think?

**Comment by robwise** [comment]
Yeah absolutely, we should do this. I would almost consider it a bug. Do we need an option like `Fallback to prettier if no ESlint configuration found`?

**Comment by silvenon** [comment]
I don't think the option is necessary, it's very intuitive and in my opinion always desired behavior. Unless there's an edge case that I'm overlooking.

**Comment by robwise** [comment]
@silvenon I was thinking that it might be confusing if they check "ESlint Integration" and then we don't actually do the integration in some cases, but I can just maybe add that in the description and skip the option?

**Comment by silvenon** [comment]
That would make sense to me, yes.

**Comment by robwise** [comment]
The more I think about this one, the more I think we should probably implement this in prettier-eslint itself. I will look into that.

**Comment by robwise** [comment]
I'm going to close this because right now prettier-eslint does this automatically. Keep an eye out for this though: https://github.com/prettier/prettier-eslint/issues/72
