### ISSUE TITLE
Atom-Prettier doesn't follow the .editorconfig options

### ISSUE THREAD

**Issue by tjapro** [prettier/prettier-atom#715]
I have a `.editorconfig` file like this:
```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
indent_size = 4
```

But when I'm saving a *.md file, `prettier on save` doesn't follow the rule `indent_size=4`.
I don't have any `.prettierrc` or `.eslint` file.

<details>
  Atom version: 1.45.0
prettier-atom version: 0.58.2
prettier: bundled
prettier version: 1.18.2
prettier-eslint version: 9.0.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "showInStatusBar": true,
    "enabled": false,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false,
    "ignoreNodeModules": true
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "useEslint": true,
  "useStylelint": true,
  "useEditorConfig": true
}
</details>

**Comment by TJProgrammer** [comment]
I receive a error messange when `prettier`try to style a css file:
`prettier-atom failed: No configuration provided for .../assets/css/extra.css`.

But, as you can see, all files must be indented with 2 spaces.

**Comment by robwise** [comment]
Do you have the `editorconfig` integration option checked in prettier-atom?

**Comment by TJProgrammer** [comment]
Yup. And changing the file to the following doesn't work.
```
[*.md]
trim_trailing_whitespace = false
indent_size = 4
indent_style = space
```

**Comment by robwise** [comment]
Hmm, that's strange, mine is definitely working. Have you tried reloading atom after changing the settings? They get cached.

**Comment by TJProgrammer** [comment]
Yes, I tried.
And here is my configuration:
```
"prettier-atom": {
			"formatOnSaveOptions": {
				"enabled": true,
				"showInStatusBar": true
			},
			"prettierEslintOptions": {},
			"useEslint": true,
			"useStylelint": true
		},
```

**Comment by TJProgrammer** [comment]
This bug still occurs, but without errors now.
I write a `.md` file with 4 spaces and Prettier formats it to 2 spaces only (not accordingly to `.editorconfig`).

**Comment by TJProgrammer** [comment]
I make some research and [this line](https://github.com/prettier/prettier-atom/blob/114818c68b9ac9e34a7c316c8e27c64646d09b15/src/executePrettier/executePrettierOnBufferRange.js#L21) gets the editorconfig option.
This option will be getted by executition itself.
So, where is the bug: in getting the value or execute it?

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.
