### ISSUE TITLE
Prettier-atom failed: Couldn't resolve parser 'postcss'

### ISSUE THREAD

**Issue by robbymarston** [prettier/prettier-atom#718]
Prettier is using the bundled version (1.18.2) instead of the version from `/node_modules`. I have confirmed prettier is present in the `node_modules` directory and in both `package.json` and `package-lock.json` (see screenshots). This is causing parser resolution errors such as [this one ](https://github.com/prettier/prettier-atom/issues/388)downstream. 

![Screen Shot 2020-03-31 at 4 36 10 PM](https://user-images.githubusercontent.com/806456/78077370-e511cd00-736d-11ea-816d-8549637ad7f0.png)
![Screen Shot 2020-03-31 at 4 35 34 PM](https://user-images.githubusercontent.com/806456/78077374-e642fa00-736d-11ea-8977-6b536968e677.png)

```
Atom version: 1.45.0
prettier-atom version: 0.58.2
prettier: bundled
prettier version: 1.18.2
prettier-eslint version: 9.0.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "isDisabledIfNotInPackageJson": true,
    "isDisabledIfNoConfigFile": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "ignoreNodeModules": true
  },
  "useEslint": true,
  "useStylelint": true,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment]
Are you using the prettier-eslint integration? If so, prettier-eslint is the one that's doing the prettier resolution and the bug lies there.

**Comment by robbymarston** [comment]
@robwise I am indeed. I'm using prettier-stylelint as well.

**Comment by iamkeir** [comment]
I am experiencing this issue too. I have `prettier-atom` version `0.60.1` installed for Atom. It also prompted me to install `linter`, which is at version `2.3.1`.

We also have `prettier` in our `package.json`:
```
"prettier": "2.0.5",
"prettier-package-json": "2.1.3",
"prettier-stylelint": "0.4.2",
"eslint-config-prettier": "6.11.0",
"eslint-plugin-prettier": "3.1.4",
```
I am a bit out of my depth here so I am not sure how to resolve - any guidance greatly appreciated.

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.

**Comment by sygnas** [comment]
Thanks for the useful plugin.
I have the same problem.

It happened after I updated the prettier of my project from 1.19.1 to 2.5.1.

ATOM 1.58.0 x64
prettier-atom@0.60.1

Please let me know if there is a way to deal with this.
