### ISSUE TITLE
Instalation problems in 1.45.0 Ubuntu 19.04

### ISSUE THREAD

**Issue by felipeferreiraads** [prettier/prettier-atom#719]
Hello!

I have this error trying to install in 1.45.0 version:

npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`

I run Atom in Ubuntu 19.04.

Tks!

**Comment by robwise** [comment]
Hmm, I've never seen that error before. Looks like it's an issue with core-js. I would try over at that repo to see if anyone has the issue there.
