### ISSUE TITLE
atom-prettier not using .prettierrc config file

### ISSUE THREAD

**Issue by followalter** [prettier/prettier-atom#735]
Hi,
I have installed prettier version 2.0.2 so it still works on atom through npm using: npm install prettier@2.0.2. I also just installed atom-prettier which is on version 0.59.0. You can see my settings here:
<img width="743" alt="Screenshot 2020-04-16 at 17 11 24" src="https://user-images.githubusercontent.com/7997344/79473448-6f605f00-8005-11ea-89ce-325517e285ff.png">

I have a .prettierrc file in the root of my project:
<img width="254" alt="Screenshot 2020-04-16 at 17 10 26" src="https://user-images.githubusercontent.com/7997344/79473530-8bfc9700-8005-11ea-8db8-a725b6d3d9ed.png">

The file has this content:
{
    "useTabs": false,
    "printWidth": 60,
    "tabWidth": 1,
    "singleQuote": true,
    "trailingComma": "none",
    "jsxBracketSameLine": false,
    "parser": "babylon",
    "semi": false,
    "rcVerbose": true
}

Whenever I save a .js file, it does run prettier, but it doesn't use my settings from the .prettierrc file. I've tried different settings in the .prettierrc file, but  it keeps using some kind of default setting.

Am I doing something wrong here? Thanks.

**Comment by robwise** [comment]
@followalter Try restarting Atom as the lookup for the prettierrc gets cached for performance reasons. Let me know if you still are having the issue.

**Comment by followalter** [comment]
Hi Rob, that fixed it :')
I was sure I already did that, but hey.
Thanks for the help, love my pretty js.

**Comment by bassamanator** [comment]
I think this is the issue that I'm having but mine isn't solved. Prettier is using it's own default settings and ignore the .prettierrc file that I have in the root project folder.

```
{
  "trailingComma": "es5",
  "useTabs": true,
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "jsxSingleQuote": true,
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "avoid",
}
```
