### ISSUE TITLE
Installing “prettier-atom@0.60.1” failed

### ISSUE THREAD

**Issue by Pulkitg8055** [prettier/prettier-atom#812]
When installing getting this error

npm ERR! Unexpected end of JSON input while parsing near '...s.org/core-js/-/core-'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pulkit\.atom\.apm\_logs\2020-06-23T04_54_18_430Z-debug.log

**Comment by Kiryusha** [comment]
Similar issue:
npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! Unexpected end of JSON input while parsing near '.../WPjuds/wMLCCl7ArlmfE'

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.

**Comment by BoltSurfer** [comment]
I have this issue when installing also

npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably
npm ERR! Unexpected end of JSON input while parsing near '...512-H1lehnjqVzZr4nswn'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BoltSurfer\.atom\.apm\_logs\2022-05-13T13_34_24_346Z-debug.log
