### ISSUE TITLE
editorconfig integration

### ISSUE THREAD

**Issue by fredrikekelund** [prettier/prettier-atom#90]
Hi, thanks for a very neat project! Looking forward to using it more.

I noted quickly however that the `tabWidth` setting doesn't seem to pick up the value as I've configured it in my `.editorconfig` file (see http://editorconfig.org/ for more details on that project). Would be great if the `tabWidth: auto` setting could pick up the value from there – that would make for a very portable workflow!

**Comment by robwise** [comment]
Hmm, this sounds like a bug, I'll look into it!

**Comment by MerlinBB** [comment]
I noticed this issue too... As a work-around, if you're using eslint you can explicitly set rules on tab-width: http://eslint.org/docs/rules/indent
