### ISSUE TITLE
Spacing between brackets

### ISSUE THREAD

**Issue by jaycetan** [prettier/prettier-atom#99]
Although I have the Bracket Spacing option set to true, formatting code removes space between brackets. 

Before: 
{ type: GraphQLString }

After:
{type: GraphQLString}

**Comment by robwise** [comment]
@jaycetan do you have the eslint integration enabled?

**Comment by michalkvasnicak** [comment]
I had this problem too. Disabling eslint integration fixed the problem.

**Comment by robwise** [comment]
Okay closing for now

**Comment by darahak** [comment]
Is `bracketSpacing` supposed to work for both array and object literals?
It only works for curly braces as mentioned in prettier's `README.md`.

**Comment by robwise** [comment]
Oh they must have changed that at some point, we should update our settings description, added here: https://github.com/prettier/prettier-atom/issues/106

**Comment by darahak** [comment]
Yup, that was discussed in https://github.com/prettier/prettier/issues/296
