### ISSUE TITLE
 js comment causes error

### ISSUE THREAD

**Issue by myyellowshoe** [prettier/prettier-atom#991]
I started getting this error with js comments yesterday. Prohibits prettier from doing its awesomeness.

![image](https://user-images.githubusercontent.com/518084/107685861-834f0e80-6c72-11eb-8e75-fe8a1422559a.png)

```
  const onInputChange = (e) => {
    // both of these create saddness
    /* both of these create sadness */
    trigger();
  };

```

Debug details:
```
Atom version: 1.54.0
prettier-atom version: 0.60.1
prettier: bundled
prettier version: 2.0.5
prettier-eslint version: 9.0.1
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false,
    "ignoreNodeModules": true
  },
  "useEslint": false,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

**Comment by robwise** [comment]
Hmm, I'm unable to reproduce locally. Can you try using the latest version of prettier by installing it in your node modules in the repo in which this code resides?

**Comment by myyellowshoe** [comment]
Ok well thats encouraging actually, wonder if something is up with my local atom setup. Let me check

**Comment by myyellowshoe** [comment]
Hmm still no luck there. Wonder If something is up in atom. May try removing atom and starting over just to see.

**Comment by myyellowshoe** [comment]
Full reinstall didn't help. Don't think its your package specifically, but maybe something with prettier or eslint? Oddly enough tried installing prettier and eslint on vscode and got the same darn error.
I recently upgraded to the latest mac version, big sur (11.2.1) and wondering if that created the issue. le sigh...

**Comment by robwise** [comment]
If you run prettier directly from the command line instead of through Atom, that will tell you whether it's Prettier vs. the Atom integration (this repo).

**Comment by myyellowshoe** [comment]
I'm closing this issue as this seamed to be related not to prettier-atom but something under the hood with prettier / eslint. If i find out more details i'll post it here just for reference. :)
